### ISSUE TITLE
No more logs when using setErrorHandler after 1.10.0 patch

### ISSUE THREAD

**Issue by fox1t** [fastify/fastify#1117]
Hi to all.
I have a problem with this specific [1073 fix](https://github.com/fastify/fastify/pull/1073): it completely breaks errors logging. Here's a dummy repository that show the problem:

https://github.com/fox1t/fastify-errors-handler-test

```
{"level":30,"time":1535552922845,"msg":"incoming request","pid":47492,"hostname":"Maksims-MacBook-Pro.local","reqId":1,"req":{"id":1,"method":"GET","url":"/api/v1/error","remoteAddress":"127.0.0.1","remotePort":50699},"v":1}
{"level":30,"time":1535552922856,"msg":"request completed","pid":47492,"hostname":"Maksims-MacBook-Pro.local","reqId":1,"res":{"statusCode":500},"responseTime":10.98310899734497,"v":1}
```

On fastify 1.8.0 it worked and still works as expected.
```
{"level":30,"time":1535552052901,"msg":"incoming request","pid":45814,"hostname":"Maksims-MacBook-Pro.local","reqId":1,"req":{"id":1,"method":"GET","url":"/api/v1/error","remoteAddress":"127.0.0.1","remotePort":65469},"v":1}
{"level":50,"time":1535552052905,"msg":"/error route","pid":45814,"hostname":"Maksims-MacBook-Pro.local","reqId":1,"req":{"id":1,"method":"GET","url":"/api/v1/error","remoteAddress":"127.0.0.1","remotePort":65469},"res":{"statusCode":500},"err":{"type":"Error","message":"/error route","stack":"Error: /error route\n    at Object.fastify.get (/Users/maksim/Projects/fox1t/error-test/routes.js:3:11)\n    at preHandlerCallback (/Users/maksim/Projects/fox1t/error-test/node_modules/fastify/lib/handleRequest.js:91:30)\n    at handler (/Users/maksim/Projects/fox1t/error-test/node_modules/fastify/lib/handleRequest.js:75:5)\n    at handleRequest (/Users/maksim/Projects/fox1t/error-test/node_modules/fastify/lib/handleRequest.js:18:5)\n    at onRunMiddlewares (/Users/maksim/Projects/fox1t/error-test/node_modules/fastify/fastify.js:440:5)\n    at middlewareCallback (/Users/maksim/Projects/fox1t/error-test/node_modules/fastify/fastify.js:428:7)\n    at Object.routeHandler [as handler] (/Users/maksim/Projects/fox1t/error-test/node_modules/fastify/fastify.js:286:7)\n    at Router.lookup (/Users/maksim/Projects/fox1t/error-test/node_modules/find-my-way/index.js:319:17)\n    at Server.emit (events.js:182:13)\n    at parserOnIncoming (_http_server.js:652:12)"},"v":1}
{"level":30,"time":1535552052910,"msg":"request completed","pid":45814,"hostname":"Maksims-MacBook-Pro.local","reqId":1,"res":{"statusCode":500},"responseTime":9.093263000249863,"v":1}
```

The only solution for me seems to add explicit call to `req.log.error(err)` inside my custom handler. Is this the way that is expected to work?

* *node version*: > 10
* *fastify version*: >=1.11.0 
* *os*: Mac

Thanks in advance.

**Comment by mcollina** [comment]
No it's a bug. I'll work on a fix.

**Comment by fox1t** [comment]
I think i found it,
https://github.com/fastify/fastify/pull/1073/commits/482c534ea64a7635edd67cbdb9b6878c2e1646b8?utf8=%E2%9C%93&diff=unified#diff-d2fdf63c1d7f1d9f68270b6dfa8c930cL307
there is a return if customErrorHandler is set. Is it correct?

**Comment by mcollina** [comment]
That needs to return, but we should log the thing somewhere else as well.

**Comment by fox1t** [comment]
Yea, we agree on that return. :)

**Comment by mixecan** [comment]
> The only solution for me seems to add explicit call to req.log.error(err) inside my custom handler

Another solution would have been to `reply.send` the Error instance with the expected properties.
Here's your errorHandler with the last line changed
```js
const errorHandler = (error, req, reply) => {
  ...
  const response = { ... }

  reply.send(Object.assign(error, response))
}
```

```
{"level":30,"time":1535618894082,"msg":"incoming request","pid":69680,"hostname":"Crono.local","reqId":1,"req":{"id":1,"method":"GET","url":"/api/v1/error","remoteAddress":"127.0.0.1","remotePort":62754},"v":1}
{"level":50,"time":1535618894087,"msg":"Something went wrong. Try again later.","pid":69680,"hostname":"Crono.local","reqId":1,"req":{"id":1,"method":"GET","url":"/api/v1/error","remoteAddress":"127.0.0.1","remotePort":62754},"res":{"statusCode":500},"err":{"type":"Error","message":"Something went wrong. Try again later.","stack":"Error: Something went wrong. Try again later.\n    at Object.fastify.get (~/fastify-errors-handler-test/routes.js:3:11)\n ....","statusCode":500},"v":1}
{"level":30,"time":1535618894117,"msg":"request completed","pid":69680,"hostname":"Crono.local","reqId":1,"res":{"statusCode":500},"responseTime":35.23115700483322,"v":1}
```

**Comment by fox1t** [comment]
I think that this is not user friendly at all: you have to explain to someone why he needs to send a response with merged error, only if custom error handler is set.
:/
