### ISSUE TITLE
SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by AsimRamay** [fastify/fastify#1302]
hi , i m new to fastify , im getting a SyntaxError: Unexpected token P in JSON at position 0 - 500 (Internal Server Error)
im using fastify-postgres and pg native (tho ive tried turning this off and there is no change)

i think ive misunderstood something when it comes to doing a PUT request

{"level":30,"time":1543981552459,"msg":"incoming request","pid":29156,"hostname":"AsimPC","reqId":1,"req":{"id":1,"method":"PUT","url":"/Customers/Update/62960/Wecare%20NSW%2F/Fred%20Ridgeway-Right/32%20Saint%20Andrews%20Street%20Maitland%202320/null/null/04317364
01(Amanda)/3/null/null/1xAdult/null","hostname":"localhost:3101","remoteAddress":"127.0.0.1","remotePort":64925},"v":1}
[ '62960' ] [ 'Wecare NSW/' ] [ 'Fred Ridgeway-Right' ] [ '32 Saint Andrews Street Maitland 2320' ] [ 'null' ] [ 'null' ] [ '0431736401(Amanda)' ] [ '3' ] [ 'null' ] [ 'null' ] [ '1xAdult' ] [ 'null' ]
F:\Projects 2018\parkmanager18\node_modules\pg\lib\query.js:142
return this.callback(err)

ive tried sync, async and normal req reply,
all other routes work 

```
fastify.put('/Customers/Update/:id/:fn/:ln/:add/:em/:tel/:mob/:idt/:idd/:ida/:com/:dob', (req, reply) => {
    console.log([decodeURIComponent(req.params.id)], [decodeURIComponent(req.params.fn)], [decodeURIComponent(req.params.ln)], [decodeURIComponent(req.params.add)], [decodeURIComponent(req.params.em)], [decodeURIComponent(req.params.tel)], [decodeURIComponent(req.params.mob)], [decodeURIComponent(req.params.idt)], [decodeURIComponent(req.params.idd)], [decodeURIComponent(req.params.ida)], [decodeURIComponent(req.params.com)], [decodeURIComponent(req.params.dob)]);
    var ID = decodeURIComponent(req.params.id);
    var FN = decodeURIComponent(req.params.fn);
    var LN = decodeURIComponent(req.params.ln);
    var ADD = decodeURIComponent(req.params.add);
    var EM = decodeURIComponent(req.params.em);
    var TEL = decodeURIComponent(req.params.tel);
    var MOB = decodeURIComponent(req.params.mob);
    var IDT = decodeURIComponent(req.params.idt);
    var IDD = decodeURIComponent(req.params.idd);
    var IDA = decodeURIComponent(req.params.ida);
    var COM = decodeURIComponent(req.params.com);
    var DOB = decodeURIComponent(req.params.dob);
    if (ID === 'null' || ID === null || ID === undefined ) {
        ID = null;
    }
    if (FN === 'null' || FN === null || FN === undefined ) {
        FN = null;
    }
    if (LN === 'null' || LN === null || LN === undefined ) {
        LN = null;
    }
    if (ADD === 'null' || ADD === null || ADD === undefined ) {
        ADD = null;
    }
    if (EM === 'null' || EM === null || EM === undefined ) {
        EM = null;
    }
    if (TEL === 'null' || TEL === null || TEL === undefined ) {
        TEL = null;
    }
    if (MOB === 'null' || MOB === null || MOB === undefined ) {
        MOB = null;
    }
    if (IDT === 'null' || IDT === null || IDT === undefined ) {
        IDT = null;
    }
    if (IDD === 'null' || IDD === null || IDD === undefined ) {
        IDD = null;
    }
    if (IDA === 'null' || IDA === null || IDA === undefined ) {
        IDA = null;
    }
    if (COM === 'null' || COM === null || COM === undefined ) {
        COM = null;
    }
    if (DOB === 'null' || DOB === null || DOB === undefined ) {
        DOB = null;
    }
    fastify.pg.connect(onConnect)

    function onConnect (err, client, release) {
        if (err) return reply.send(err)

        client.query(
            'UPDATE "public"."Customers" SET ("First_Name", "Last_Name", "Address", "Email", "Telephone", "Mobile", "ID_Type", "ID_Details", "ID_Address", "Comments", "DOB")=($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) WHERE "public"."Customers"."Customer_ID" = $1 RETURNING "public"."Customers"."Customer_ID"', [ID], [FN], [LN], [ADD], [EM], [TEL], [MOB], [IDT], [IDD], [IDA], [COM], [DOB],
            function onResult (err, result) {
                release()
                reply.send(err || result)
            }
        )
    }

    // const client = await fastify.pg;
    // client.connect(function(err) {
    //     if(err) throw err;
    //     var rowdata = undefined;
    //     const rows = client.query('UPDATE "public"."Customers" SET ("First_Name", "Last_Name", "Address", "Email", "Telephone", "Mobile", "ID_Type", "ID_Details", "ID_Address", "Comments", "DOB")=(Wecare NSW/','Fred Ridgeway-Right,32 Saint Andrews Street Maitland 2320,'+null+','+null+',0431736401(Amanda),3,'+null+','+null+',1xAdult,'+null+') WHERE "public"."Customers"."Customer_ID" = 62960 RETURNING "public"."Customers"."Customer_ID"', function(err, rows) {
    //         if(err) throw err;
    //         console.log(err);
    //         rowdata = rows;
    //         console.log(rows[0])
    //         });
    //     console.log(rows);
    //     console.log(rowdata);
    //     console.log(client);
    //     client.end(function() {
    //         console.log('ended')
    //     })
    // })

    // const client = await fastify.pg.connect();
    // const {rows} = await client.query(
    //     'UPDATE "public"."Customers" SET ("First_Name", "Last_Name", "Address", "Email", "Telephone", "Mobile", "ID_Type", "ID_Details", "ID_Address", "Comments", "DOB")=($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) WHERE "public"."Customers"."Customer_ID" = $1 RETURNING "public"."Customers"."Customer_ID"', [ID], [FN], [LN], [ADD], [EM], [TEL], [MOB], [IDT], [IDD], [IDA], [COM], [DOB],
    //     );
    // client.release();
    // console.log(rows);
    // return rows
    // ~error undefined row cannot be deconstructed
});
```

**Comment by mcollina** [comment]
Can you add:

1. the full stacktrace
2. a full example to reproduce

**Comment by delvedor** [comment]
Quick tip, you don't need to use `decodeURIComponent`, we are already doing it for you internally, and with super performances! :)

**Comment by AsimRamay** [comment]
**Console Output**
> parkmanager18@0.1.0 fastify-start F:\Projects 2018\parkmanager18
> node server/server

{"level":30,"time":1543981542855,"msg":"Server listening at http://127.0.0.1:3101","pid":29156,"hostname":"AsimPC","v":1}
server listening on 3101
{"level":30,"time":1543981552459,"msg":"incoming request","pid":29156,"hostname":"AsimPC","reqId":1,"req":{"id":1,"method":"PUT","url":"/Customers/Update/62960/Wecare%20NSW%2F/Fred%20Ridgeway-Right/32%20Saint%20Andrews%20Street%20Maitland%202320/null/null/04317364
01(Amanda)/3/null/null/1xAdult/null","hostname":"localhost:3101","remoteAddress":"127.0.0.1","remotePort":64925},"v":1}
[ '62960' ] [ 'Wecare NSW/' ] [ 'Fred Ridgeway-Right' ] [ '32 Saint Andrews Street Maitland 2320' ] [ 'null' ] [ 'null' ] [ '0431736401(Amanda)' ] [ '3' ] [ 'null' ] [ 'null' ] [ '1xAdult' ] [ 'null' ]
F:\Projects 2018\parkmanager18\node_modules\pg\lib\query.js:142
    return this.callback(err)
                ^

TypeError: this.callback is not a function
    at Query.handleError (F:\Projects 2018\parkmanager18\node_modules\pg\lib\query.js:142:17)
    at Connection.connectedErrorMessageHandler (F:\Projects 2018\parkmanager18\node_modules\pg\lib\client.js:159:17)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (F:\Projects 2018\parkmanager18\node_modules\pg\lib\connection.js:124:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parkmanager18@0.1.0 fastify-start: `node server/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parkmanager18@0.1.0 fastify-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asim\AppData\Roaming\npm-cache\_logs\2018-12-05T03_45_52_522Z-debug.log

**Fastify Server.js**
```
const fastify = require('fastify')({
    logger: true
});

fastify.register(require('fastify-postgres'), {
    connectionString: 'postgres://postgres@localhost/ParkManager'
    // native: true
});

fastify.get('/Customers/:id', async (req, reply) => {
    const client = await fastify.pg.connect();
    const {rows} = await client.query(
        'SELECT   "public"."Customers"."Customer_ID" AS "Customer ID",\n' +
        '         "public"."Customers"."First_Name" AS "First Name",\n' +
        '         "public"."Customers"."Last_Name" AS "Last Name",\n' +
        '         "public"."Customers"."Address" ,\n' +
        '         "public"."Customers"."Email",\n' +
        '         "public"."Customers"."Telephone",\n' +
        '         "public"."Customers"."Mobile",\n' +
        '         "public"."ID_type"."ID_Name" AS "ID Name",\n' +
        '         "public"."Customers"."ID_Details" AS "ID Details",\n' +
        '         "public"."Customers"."ID_Address" AS "ID Address",\n' +
        '         "public"."Customers"."Comments",\n' +
        '         "public"."Customers"."DOB"\n' +
        'FROM     "public"."Customers" \n' +
        'INNER JOIN "public"."ID_type"  ON "public"."Customers"."ID_Type" = "public"."ID_type"."ID" WHERE "public"."Customers"."Customer_ID"=$1', [req.params.id],
    );
    client.release();
    return rows
});

fastify.get('/Customers', async (req, reply) => {
    const client = await fastify.pg.connect();
    const {rows} = await client.query(
        'SELECT   "public"."Customers"."Customer_ID" AS "Customer ID",\n' +
        '         "public"."Customers"."First_Name" AS "First Name",\n' +
        '         "public"."Customers"."Last_Name" AS "Last Name",\n' +
        '         "public"."Customers"."Address",\n' +
        '         "public"."Customers"."Email",\n' +
        '         "public"."Customers"."Telephone",\n' +
        '         "public"."Customers"."Mobile",\n' +
        '         "public"."ID_type"."ID_Name" AS "ID Name",\n' +
        '         "public"."Customers"."ID_Details" AS "ID Details",\n' +
        '         "public"."Customers"."ID_Address" AS "ID Address",\n' +
        '         "public"."Customers"."Comments",\n' +
        '         "public"."Customers"."DOB"\n' +
        'FROM     "public"."Customers" \n' +
        'INNER JOIN "public"."ID_type"  ON "public"."Customers"."ID_Type" = "public"."ID_type"."ID"',
    );
    client.release();
    return rows
});

fastify.get('/Residents', async (req, reply) => {
    const client = await fastify.pg.connect();
    const {rows} = await client.query(
        'SELECT C."Customer_ID" AS "Customer ID", B."Cabin_Id" AS "Cabin ID",C."First_Name" AS "First Name", C."Last_Name" AS "Last Name", C."Address", C."Email", C."Telephone", C."Mobile", ID."ID_Name" AS "ID Name", C."ID_Details" AS "ID Details", C."ID_Address"  AS "ID Address", C."Comments", C."DOB"\n' +
    'FROM "public"."Customers" C \n' +
    'INNER JOIN "public"."ID_type" ID ON ( C."ID_Type" = ID."ID")\n' +
     'INNER JOIN "public"."Bookings" B ON ( C."Customer_ID" = B."Customer_Id"  )\n' +
    'WHERE B."Check_In" is not null AND B."Check_Out" is null\n' +
    'ORDER BY B."Cabin_Id" ASC',
    );
    client.release();
    return rows
});

fastify.get('/IDType', async (req, reply) => {
    const client = await fastify.pg.connect();
    const {rows} = await client.query(
        'SELECT   "public"."ID_type"."ID",\n' +
        '         "public"."ID_type"."ID_Name" AS "ID Name"\n' +
        'FROM "public"."ID_type"',
    );
    client.release();
    return rows
});
fastify.put('/Customers/Update/:id/:fn/:ln/:add/:em/:tel/:mob/:idt/:idd/:ida/:com/:dob', (req, reply) => {
    console.log([decodeURIComponent(req.params.id)], [decodeURIComponent(req.params.fn)], [decodeURIComponent(req.params.ln)], [decodeURIComponent(req.params.add)], [decodeURIComponent(req.params.em)], [decodeURIComponent(req.params.tel)], [decodeURIComponent(req.params.mob)], [decodeURIComponent(req.params.idt)], [decodeURIComponent(req.params.idd)], [decodeURIComponent(req.params.ida)], [decodeURIComponent(req.params.com)], [decodeURIComponent(req.params.dob)]);
    var ID = decodeURIComponent(req.params.id);
    var FN = decodeURIComponent(req.params.fn);
    var LN = decodeURIComponent(req.params.ln);
    var ADD = decodeURIComponent(req.params.add);
    var EM = decodeURIComponent(req.params.em);
    var TEL = decodeURIComponent(req.params.tel);
    var MOB = decodeURIComponent(req.params.mob);
    var IDT = decodeURIComponent(req.params.idt);
    var IDD = decodeURIComponent(req.params.idd);
    var IDA = decodeURIComponent(req.params.ida);
    var COM = decodeURIComponent(req.params.com);
    var DOB = decodeURIComponent(req.params.dob);
    if (ID === 'null' || ID === null || ID === undefined ) {
        ID = null;
    }
    if (FN === 'null' || FN === null || FN === undefined ) {
        FN = null;
    }
    if (LN === 'null' || LN === null || LN === undefined ) {
        LN = null;
    }
    if (ADD === 'null' || ADD === null || ADD === undefined ) {
        ADD = null;
    }
    if (EM === 'null' || EM === null || EM === undefined ) {
        EM = null;
    }
    if (TEL === 'null' || TEL === null || TEL === undefined ) {
        TEL = null;
    }
    if (MOB === 'null' || MOB === null || MOB === undefined ) {
        MOB = null;
    }
    if (IDT === 'null' || IDT === null || IDT === undefined ) {
        IDT = null;
    }
    if (IDD === 'null' || IDD === null || IDD === undefined ) {
        IDD = null;
    }
    if (IDA === 'null' || IDA === null || IDA === undefined ) {
        IDA = null;
    }
    if (COM === 'null' || COM === null || COM === undefined ) {
        COM = null;
    }
    if (DOB === 'null' || DOB === null || DOB === undefined ) {
        DOB = null;
    }
    fastify.pg.connect(onConnect);

    function onConnect (err, client, release) {
        if (err) return reply.send(err);

        client.query(
            'UPDATE "public"."Customers" SET ("First_Name", "Last_Name", "Address", "Email", "Telephone", "Mobile", "ID_Type", "ID_Details", "ID_Address", "Comments", "DOB")=($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) WHERE "public"."Customers"."Customer_ID" = $1 RETURNING "public"."Customers"."Customer_ID"', [ID], [FN], [LN], [ADD], [EM], [TEL], [MOB], [IDT], [IDD], [IDA], [COM], [DOB],
            function onResult (err, result) {
                release();
                reply.send(err || result)
            }
        )
    }

    // const client = await fastify.pg;
    // client.connect(function(err) {
    //     if(err) throw err;
    //     var rowdata = undefined;
    //     const rows = client.query('UPDATE "public"."Customers" SET ("First_Name", "Last_Name", "Address", "Email", "Telephone", "Mobile", "ID_Type", "ID_Details", "ID_Address", "Comments", "DOB")=(Wecare NSW/','Fred Ridgeway-Right,32 Saint Andrews Street Maitland 2320,'+null+','+null+',0431736401(Amanda),3,'+null+','+null+',1xAdult,'+null+') WHERE "public"."Customers"."Customer_ID" = 62960 RETURNING "public"."Customers"."Customer_ID"', function(err, rows) {
    //         if(err) throw err;
    //         console.log(err);
    //         rowdata = rows;
    //         console.log(rows[0])
    //         });
    //     console.log(rows);
    //     console.log(rowdata);
    //     console.log(client);
    //     client.end(function() {
    //         console.log('ended')
    //     })
    // })

    // const client = await fastify.pg.connect();
    // const {rows} = await client.query(
    //     'UPDATE "public"."Customers" SET ("First_Name", "Last_Name", "Address", "Email", "Telephone", "Mobile", "ID_Type", "ID_Details", "ID_Address", "Comments", "DOB")=($2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) WHERE "public"."Customers"."Customer_ID" = $1 RETURNING "public"."Customers"."Customer_ID"', [ID], [FN], [LN], [ADD], [EM], [TEL], [MOB], [IDT], [IDD], [IDA], [COM], [DOB],
    //     );
    // client.release();
    // console.log(rows);
    // return rows
    // ~error undefined row cannot be deconstructed
});

// fastify.get('/user', (req, reply) => {
//     fastify.pg.query(
//         'SELECT "Customer_ID","Last_Name","First_Name","Address","Email","Telephone","Mobile","ID_Type","ID_Details","ID_Address","Comments","DOB" FROM "Customers"',
//         function onResult (err, result) {
//             reply.send(err || result)
//         }
//     )
// })

fastify.listen(3101, err => {
    if (err) throw err;
    console.log(`server listening on ${fastify.server.address().port}`)
});
```

**client side put code**
```
    PostApi = async() => {
        const settings = {
            method: 'PUT'
        };
        console.log(this.state.Mobile);
        console.log('/Customers/Update/'+encodeURIComponent(this.state.CustomerID)+'/'+encodeURIComponent(this.state.FirstName)+'/'+encodeURIComponent(this.state.LastName)+'/'+encodeURIComponent(this.state.Address)+'/'+encodeURIComponent(this.state.Email)+'/'+encodeURIComponent(this.state.Telephone)+'/'+encodeURIComponent(this.state.Mobile)+'/'+encodeURIComponent(this.state.IDName)+'/'+encodeURIComponent(this.state.IDDetails)+'/'+encodeURIComponent(this.state.IDAddress)+'/'+encodeURIComponent(this.state.Comments)+'/'+encodeURIComponent(this.state.DOB),settings);
        const response = await fetch('/Customers/Update/'+encodeURIComponent(this.state.CustomerID)+'/'+encodeURIComponent(this.state.FirstName)+'/'+encodeURIComponent(this.state.LastName)+'/'+encodeURIComponent(this.state.Address)+'/'+encodeURIComponent(this.state.Email)+'/'+encodeURIComponent(this.state.Telephone)+'/'+encodeURIComponent(this.state.Mobile)+'/'+encodeURIComponent(this.state.IDName)+'/'+encodeURIComponent(this.state.IDDetails)+'/'+encodeURIComponent(this.state.IDAddress)+'/'+encodeURIComponent(this.state.Comments)+'/'+encodeURIComponent(this.state.DOB),settings);
        const body = await response.json();

        if (response.status !== 200) throw Error(body.message);

        return body;
    };

    async SaveClick() {
            this.PostApi()
                .then(res => {
                    notify(`Customer ` + this.state.FirstName + ' ' + this.state.LastName + ' was Updated, Server Response: ' + res);
                    console.log(`Customer ` + this.state.FirstName + ' ' + this.state.LastName + ' was Updated, Server Response: ' + res);
                    history.push('.');
                })
                .catch(err => {
                    console.log(err);
                    notify(err);
                });
    }
```

**Comment by AsimRamay** [comment]
> Quick tip, you don't need to use `decodeURIComponent`, we are already doing it for you internally, and with super performances! :)

ahh ok ill change that i didn't originally have it but i added it thinking maybe my url was cuasing missformed sql or something so just added it in chase that was the problem

**Comment by AsimRamay** [comment]
> Can you add:
> 
> 1. the full stacktrace
> 2. a full example to reproduce

for 2, did i need something more than the section of code i used or is what i posted above enough ?

**Comment by mcollina** [comment]
It’s a problem either in fastify-postgres or in the pg library itself. There is an error that is happening on the error path.

I’d recommend to use a the inspector/debugger and find out exactly what is the issue.

**Comment by mcollina** [comment]
I'll move this to fastify/help, you can keep using this issue.
