### ISSUE TITLE
Memory leak with 1.13.2

### ISSUE THREAD

**Issue by goliatone** [fastify/fastify#1332]
## 🐛 Bug Report

Memory leak under load testing. Error:

```
(node:92681) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:223:19)
    at Socket.addListener (events.js:240:10)
    at Socket.Readable.on (_stream_readable.js:775:35)
    at Socket.socketOnWrap [as on] (_http_server.js:668:37)
    at first (.../project/src/node_modules/ee-first/index.js:43:10)
    at onSocket (.../project/src/node_modules/on-finished/index.js:114:16)
    at attachFinishedListener (.../project/src/node_modules/on-finished/index.js:119:5)
    at attachListener (.../project/src/node_modules/on-finished/index.js:146:5)
    at onFinished (.../project/src/node_modules/on-finished/index.js:52:3)
    at SendStream.stream (.../project/src/node_modules/send/index.js:802:3)
    at SendStream.send (.../project/src/node_modules/send/index.js:708:8)
    at onstat (.../project/src/node_modules/send/index.js:730:10)
    at FSReqWrap.oncomplete (fs.js:167:5)
```

## To Reproduce

```
npx autocannon -c 100 -d 5 -p 10 localhost:3003
```

The Fastify router:

```js
'use strict';
const path = require('path');

module.exports = async function routes(fastify, options) {
    console.log('dashboard.routes');

    fastify.get('/health', async function(req, res) {
        res.type('application/json').code(200);
        res.send({ status: 'ok' });
    });

    fastify.setNotFoundHandler(function(req, res) {
        res.sendFile('404.html');
    });

    fastify.register(require('fastify-static'), {
        root: path.join(__dirname, '../public'),
        prefix: ''
    });
  
    fastify.get('/', function(req, res) {
        res.sendFile('index.html');
    });
};
```
## Environment

- *node*: v9.2.0
- *npm*: 5.5.1
- *fastify*: ^1.13.2
- *fastify-static*: ^1.0.0
- *os*: Mac

**Comment by cemremengu** [comment]
I didn't test but suspecting whether this can be due to node `v9.2.0` (regardless of this please note that Fastify only *officially* supports LTS releases of nodejs)

**Comment by mcollina** [comment]
Node 9 is not supported by Node.js anymore. However we support it, mainly because it was released during our LTS cycle. This means we support the latest (ever) version of Node.js 9, which is 9.11.2. I would recommend you to upgrade to the latest Node 10 anyway (10.14.2), as it contains some important security vulnerabilities fix.

Can you please provide a full example to reproduce it? A github repo that we could clone would be perfect.

**Comment by cemremengu** [comment]
@goliatone any updates here? I am curious to see if we could reproduce this

**Comment by goliatone** [comment]
Not really, I basically started the project over and fixed some dependencies in order to use node 10. Thanks!
