### ISSUE TITLE
JSON Schema Error: missing id schema when set $schema

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#1353]
## 🐛 Bug Report

I'm working on [issue 1329](https://github.com/fastify/fastify/issues/1329) and so I'm trying the docs I'm writing, but I got this error when using the following schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "someKey": {
      "type": "string"
    }
  }
}

Error:
FastifyError [FST_ERR_SCH_NOT_PRESENT]: FST_ERR_SCH_NOT_PRESENT: Schema with id 'http://json-schema.org/draft-07/schema' does not exist!
    at Schemas.resolve (C:\Users\behem\workspace\fastify\lib\schemas.js:30:11)
    at Schemas.traverse (C:\Users\behem\workspace\fastify\lib\schemas.js:76:26)
    at Schemas.traverse (C:\Users\behem\workspace\fastify\lib\schemas.js:80:12)
    at Schemas.resolveRefs (C:\Users\behem\workspace\fastify\lib\schemas.js:49:10)
    at build (C:\Users\behem\workspace\fastify\lib\validation.js:29:28)
    at afterRouteAdded (C:\Users\behem\workspace\fastify\fastify.js:636:9)
    at C:\Users\behem\workspace\fastify\fastify.js:596:7
```

## To Reproduce

```js
const fastify = require('fastify')({ logger: true })
const { FluentSchema } = require('fluent-schema')

const bodySchema = FluentSchema()
  .prop(
    'someKey',
    FluentSchema()
      .asString()
  )

const schema = { body: bodySchema.valueOf() }

fastify.post('/the/url', { schema }, (request, reply) => {
  reply.send({ hello: 'world' })
})

fastify.listen(3000, (err, address) => {
  if (err) throw err
  fastify.log.info(`server listening on ${address}`)
})
```

## Expected behavior

I don't expect the thrown's error. The `$schema` is raccomended by the [standard](https://json-schema.org/understanding-json-schema/reference/schema.html) so, maybe I'm missing something or this field should be ignored?

If I remove the `$schema` field, all is working:

```js
delete schema.body.$schema
```

## Your Environment

- *node version*: 8.14.0
- *fastify version*: 2.0.0-rc.3
- *os*: Windows 10
- *fluent-schema*: 0.4.0

**Comment by mcollina** [comment]
I've moved this issue from `fastify/help`  to `fastify/fastify`  as it's actually a bug.
