### ISSUE TITLE
TLS / socket hang up / ECONNRESET

### ISSUE THREAD

**Issue by rtvv** [fastify/fastify#1361]
After every request from client i got a server error after a minute (TLS / socket hang up / ECONNRESET), here is the pino logs:
```
[nodemon] starting `node test.js`
INFO  [2019-01-03 12:21:10.894 +0000] (11508 on PredatorRTW):
    msg: "Server listening at https://127.0.0.1:3001"
GO
INFO  [2019-01-03 12:23:55.652 +0000] (11508 on PredatorRTW):
    msg: "incoming request"
    reqId: 1
    req: {
      "method": "GET",
      "url": "/",
      "hostname": "localhost:3001",
      "remoteAddress": "127.0.0.1",
      "remotePort": 53161
    }
INFO  [2019-01-03 12:23:55.658 +0000] (11508 on PredatorRTW):
    msg: "request completed"
    reqId: 1
    res: {
      "statusCode": 200
    }
    responseTime: 4.617481000721455
ERROR [2019-01-03 12:24:09.858 +0000] (11508 on PredatorRTW):
    msg: "client error"
    err: {
      "type": "Error",
      "message": "socket hang up",
      "stack":
          Error: socket hang up
              at TLSSocket.onSocketClose (_tls_wrap.js:737:23)
              at TLSSocket.emit (events.js:187:15)
              at _handle.close (net.js:616:12)
              at Socket.done (_tls_wrap.js:384:7)
              at Object.onceWrapper (events.js:273:13)
              at Socket.emit (events.js:182:13)
              at TCP._handle.close (net.js:616:12)
      "code": "ECONNRESET"
    }
```

Simple server configuration ("fastify": "^2.0.0-rc.3", node v11.2.0)
```
let fs = require('fs')

const fastify = require('fastify')({
  logger: {
    prettyPrint: {
      levelFirst: true,
      translateTime: true,
      messageKey: 'errStack'
    }
  },
  https: {
    key: fs.readFileSync('./tls/cert.key'),
    cert: fs.readFileSync('./tls/cert.pem')
  }
})

fastify.listen(3001, 'localhost', async (err, address) => {
  err ? console.log(err) : console.log('GO')
})

fastify.get('/', async (request, res) => {
  res.send({ hello: 'world' })
})
```

What does this error mean? Is there something wrong with my configuration?

**Comment by mcollina** [comment]
Can you please include instructions on how to get the above error? Which client are you using?

**Comment by BofEmptiness** [comment]
It's fastify "^2.0.0-rc.3" and node v11.2.0
You just need to make a GET at any url and wait for one minute @mcollina

**Comment by cemremengu** [comment]
Looks like your client closes the connection (timeout) before Fastify can send the response

**Comment by BofEmptiness** [comment]
Hm, i think without http2 i've got no errors. Will tell you after 5 min to be sure.

**Comment by BofEmptiness** [comment]
I've deleted http2 and have same error.

**Comment by cemremengu** [comment]
@BofEmptiness what about https?

**Comment by BofEmptiness** [comment]
Ok, i will try just http, give me a minute. Here is the curl something if it will help:

```
C:\Users\acer>curl -v https://localhost:3001
* Rebuilt URL to: https://localhost:3001/
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3001 (#0)
* schannel: SSL/TLS connection with localhost port 3001 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 174 bytes...
* schannel: sent initial handshake data: sent 174 bytes
* schannel: SSL/TLS connection with localhost port 3001 (step 2/3)
* schannel: encrypted data got 1409
* schannel: encrypted data buffer: offset 1409 length 4096
* schannel: sending next handshake data: sending 117 bytes...
* schannel: SSL/TLS connection with localhost port 3001 (step 2/3)
* schannel: encrypted data got 298
* schannel: encrypted data buffer: offset 298 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with localhost port 3001 (step 3/3)
* schannel: stored credential handle in session cache
> GET / HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 213
* schannel: encrypted data buffer: offset 213 length 103424
* schannel: decrypted data length: 164
* schannel: decrypted data added: 164
* schannel: decrypted data cached: offset 164 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 164 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 164
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 17
< Date: Thu, 03 Jan 2019 12:30:59 GMT
< Connection: keep-alive
<
{"hello":"world"}* Connection #0 to host localhost left intact
```

**Comment by BofEmptiness** [comment]
With only http i have no errors =>
If delete this:
`
  https: {
    key: fs.readFileSync('./tls/cert.key'),
    cert: fs.readFileSync('./tls/cert.pem')
  }`
@cemremengu

**Comment by jsumners** [comment]
This looks like expected behavior to me.

1.
> < Connection: keep-alive

2.
> {"hello":"world"}* Connection #0 to host localhost left intact

So the client is keeping the TLS connection alive to avoid redoing the handshake on the next connection. But since you are not sending another request, that connection is timing out. By default, the server will [timeout the connection after 2 minutes](https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback).

**Comment by BofEmptiness** [comment]
This line looks strange for me to, but how do i change this behavior? It's some https setting or tls keys problem?

**Comment by mcollina** [comment]
The error comes from here: https://github.com/fastify/fastify/blob/master/fastify.js#L823-L831.

I think we could: move that error to log level debug, as it's a very low level condition. I think it's likely better than ignoring ECONNRESETs, as those might be needed for other stuff as well.

@BofEmptiness would you like to send a PR?

**Comment by BofEmptiness** [comment]
I will. Will be my first PR on github :) @mcollina

**Comment by cemremengu** [comment]
@BofEmptiness let's keep this open until the PR lands :) Please reference this issue from the PR.
