### ISSUE TITLE
[Fastify v2] fastify-plugin checkVersion fn throws error

### ISSUE THREAD

**Issue by lfurzewaddock** [fastify/fastify#1481]
## To Reproduce

install fastify v2 and start server.

To work around the error further below it was necessary to comment out error thrown in checkVersion function, './node_modules/fastify-plugin/index.js'.

## Expected behavior

Should start without error.

Paste the results here:

```bash
/mnt/d/project/src/api/store-front/node_modules/fastify-plugin/index.js:1
Error: fastify-plugin - expected '^1.0.0' fastify version, '2.0.0' is installed
    at checkVersion (/mnt/d/project/src/api/store-front/node_modules/fastify-plugin/index.js:79:11)
    at plugin (/mnt/d/project/src/api/store-front/node_modules/fastify-plugin/index.js:40:5)
    at Object.<anonymous> (/mnt/d/project/src/api/store-front/node_modules/fastify-formbody/formbody.js:21:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactstor-store-api@0.1.0 devStart: `NODE_ENV=development DEBUG=reactstor:* node -r esm -r dotenv/config ./bin/dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactstor-store-api@0.1.0 devStart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/SysMan/.npm/_logs/2019-02-25T14_59_49_356Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactstor@0.1.0 devStartApi: `cd ./src/api/store-front && npm run devStart`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactstor@0.1.0 devStartApi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/SysMan/.npm/_logs/2019-02-25T14_59_49_424Z-debug.log
```

## Your Environment

- *node version*: 8.11.2
- *npm version*: 6.80
- *fastify version*: >=2.0.0
- *os*:  Windows 10 (WSL)
- *any other relevant information*

**Comment by mcollina** [comment]
you’ll need to update your fastify-formbody dependency.

**Comment by lfurzewaddock** [comment]
fastify-formbody is at v2.1.0

Bug is still present when fastify-formbody is not in use too.

**Comment by mcollina** [comment]
You need to use v3 of fastify-formbody https://github.com/fastify/fastify-formbody/blob/master/package.json#L3.

**Comment by lfurzewaddock** [comment]
Ok, cheers - that's fixed it.
