### ISSUE TITLE
The stream has been destroyed - ERR_HTTP2_INVALID_STREAM

### ISSUE THREAD

**Issue by ReTWi** [fastify/fastify#1494]
If you will push F5 in browser few times fast, you will get this error:
```js
fastify errorHandler
    err: {
      "type": "NodeError",
      "message": "The stream has been destroyed",
      "stack":
          Error [ERR_HTTP2_INVALID_STREAM]: The stream has been destroyed
              at Http2ServerResponse.writeHead (internal/http2/compat.js:567:13)
              at onSendEnd (D:\apps\node_modules\fastify\lib\reply.js:308:7)
              at onSendHook (D:\apps\node_modules\fastify\lib\reply.js:261:5)
              at preserializeHookEnd (D:\apps\node_modules\fastify\lib\reply.js:247:3)
              at preserializeHook (D:\apps\node_modules\fastify\lib\reply.js:234:5)
              at _Reply.Reply.send (D:\apps\node_modules\fastify\lib\reply.js:133:5)
              at Object.handler (D:\apps\backend\api\with_session\reader.js:14:11)
              at processTicksAndRejections (internal/process/next_tick.js:81:5)
    }
```

## Expected behavior
There should be no logged errors.

## Your Environment
- *node version*: 11.9.0
- *fastify version*: >=2.0.0
- *os*: Windows

Is there a way to skip this error?

**Comment by mcollina** [comment]
This looks like a bug in Node.js core.

**Comment by mcollina** [comment]
Confirmed, in http1: https://github.com/nodejs/node/blob/9edce1e12a7b69e7986dd15fce18d6e46590161a/lib/_http_outgoing.js#L245-L250

in http2:
https://github.com/nodejs/node/blob/9edce1e12a7b69e7986dd15fce18d6e46590161a/lib/internal/http2/compat.js#L564-L567

I'll issue a PR there.

**Comment by mcollina** [comment]
As a temporary measure we should add an if on that error code, and if that's the case ignore that error.

**Comment by t4nz** [comment]
Hi guys, any news about this issue? Thanks

**Comment by mcollina** [comment]
This is going to be solved by https://github.com/nodejs/node/pull/27682.

Can you upload a script to reproduce so I can verify that solves the actual issue?

**Comment by ReTWi** [comment]
I don't really know what part of my server to take for example :/  Simple fastify server don't want to produce error. I will try to add some file read or await in code and see if error will come up.

**Comment by ReTWi** [comment]
Checked in node.js 12.3.0 - all fine, thanks!

**Comment by mokimo** [comment]
I'm on node 12.12.0 and still regularly getting this problem:

```
Error [ERR_HTTP2_INVALID_STREAM] [ERR_HTTP2_INVALID_STREAM]: The stream has been destroyed
    at Http2ServerResponse.write (internal/http2/compat.js:637:19)
    at IncomingMessage.ondata (_stream_readable.js:726:22)
    at IncomingMessage.emit (events.js:210:5)
    at IncomingMessage.Readable.read (_stream_readable.js:524:10)
    at flow (_stream_readable.js:999:34)
    at resume_ (_stream_readable.js:980:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
 {
  code: 'ERR_HTTP2_INVALID_STREAM'
}
```

### Your Environment
node version: 12.12.0
fastify version: >=2.9.0
os: macOS High Sierra

**Comment by ReTWi** [comment]
@mokimo I don't have this error anymore, so I suggest you to open a new bug, with link here.

**Comment by JinHengyu** [comment]
let me show u the final solution：
listen the uncaughtException on process and then the error won't make the process exit :)
`
process.on('uncaughtException',err=>{
    // err.code === 'ERR_HTTP2_INVALID_STREAM'
    // err.message === 'The stream has been destroyed'
    console.log(`someone is keep pushing F5...`)
})
`
