### ISSUE TITLE
[help] Usage with nginx unit

### ISSUE THREAD

**Issue by academici** [fastify/fastify#1536]
Hi! Not so long ago, [nginx unit](http://unit.nginx.org) had the opportunity to run nodejs applications. The official documentation has an example of [use with express](http://unit.nginx.org/howto/express/).
I rewrote the script under fastify.
```js
#!/usr/bin/env node

const { createServer, IncomingMessage, ServerResponse } = require("unit-http");

require("http").ServerResponse = ServerResponse;
require("http").IncomingMessage = IncomingMessage;

// Require the framework and instantiate it
const fastify = require('fastify')({
  logger: true
})

// Declare a route
fastify.get('/', function (request, reply) {
  reply.send({ hello: 'world' })
})

createServer(fastify).listen();
```
Unit configure
```json
{
    "applications": {
        "node": {
            "type": "external",
            "working_directory": "/var/www/node",
            "executable": "server.js"
        }
    },
    "listeners": {
        "*:8086": {
            "pass": "applications/node"
        }
    }
}
```

At startup get an error:
```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at _addListener (events.js:200:11)
    at Server.addListener (events.js:259:10)
    at new Server (/usr/local/lib/node_modules/unit-http/http_server.js:355:14)
    at createServer (/usr/local/lib/node_modules/unit-http/http.js:13:12)
    at Object.<anonymous> (/home/vostrikov/apps/carsalon-unit/frontend/server.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
2019/03/14 16:51:55 [notice] 1018#1018 process 21073 exited with code 1
2019/03/14 16:51:55 [info] 21080#21080 "carsalon_frontend" application started
events.js:200
    throw new errors.ERR_INVALID_ARG_TYPE('listener', 'Function', listener);
```
Can i get fastify function for unit server?

Thanks.

**Comment by delvedor** [comment]
Hello!
You can accomplish this by using the [`serverFactory`](https://www.fastify.io/docs/latest/Server/#serverfactory) option :)

**Comment by academici** [comment]
@delvedor, thanks, is my server.js
```js
const { createServer, IncomingMessage, ServerResponse } = require("unit-http");

require("http").ServerResponse = ServerResponse;
require("http").IncomingMessage = IncomingMessage;

const serverFactory = (handler, opts) => {
  const server = createServer((req, res) => {
    console.log(req);
    handler(req, res);
  });
  return server;
};

const fastify = require("fastify")({ serverFactory });

fastify.get("/", (req, reply) => {
  reply.send({ hello: "world" });
});
```
All requests return 400 code:
```json
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```
This is request console log:
```js
ServerRequest {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  server:
   Server {
     _events:
      [Object: null prototype] {
        request: [Function],
        clientError: [Function: handleClientError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     unit: Unit { server: [Circular] },
     socket: [Function: Socket],
     request: [Function: ServerRequest],
     response: [Function: ServerResponse],
     buffer: <Buffer > },
  socket:
   Socket {
     _events: [Object: null prototype] {},
     _eventsCount: 0,
     _maxListeners: undefined,
     readable: true,
     writable: true,
     req_pointer: 40781680 },
  headers:
   { Host: 'localhost',
     Connection: 'close',
     'Cache-Control': 'max-age=0',
     'Upgrade-Insecure-Requests': '1',
     'User-Agent':
      'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36',
     Accept:
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
     'Accept-Encoding': 'gzip, deflate, br',
     'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' },
  rawHeaders:
   [ 'Host',
     'localhost',
     'Connection',
     'close',
     'Cache-Control',
     'max-age=0',
     'Upgrade-Insecure-Requests',
     '1',
     'User-Agent',
     'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36',
     'Accept',
     'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
     'Accept-Encoding',
     'gzip, deflate, br',
     'Accept-Language',
     'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' ],
  httpVersion: 'HTTP/1.0',
  method: 'GET',
  url: '/',
  res:
   ServerResponse {
     _events: [Object: null prototype] {},
     _eventsCount: 0,
     _maxListeners: undefined,
     headers: {},
     socket:
      Socket {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        readable: true,
        writable: true,
        req_pointer: 40781680 },
     _req_point: 40781680,
     server:
      Server {
        _events:
         [Object: null prototype] {
           request: [Function],
           clientError: [Function: handleClientError] },
        _eventsCount: 2,
        _maxListeners: undefined,
        unit: Unit { server: [Circular] },
        socket: [Function: Socket],
        request: [Function: ServerRequest],
        response: [Function: ServerResponse],
        buffer: <Buffer > },
     req: [Circular] } }
```
What could be the problem?

**Comment by mcollina** [comment]
I _think_ you should call the `ready()` method.

**Comment by academici** [comment]
@mcollina did not understand how use ready, wrap fastify.get - did not work?

**Comment by delvedor** [comment]
@academici you should also call `fastify.listen`.
`fastify.ready` loads all the plugins, and you should use it only if the server that you have passed is already listening.

**Comment by academici** [comment]
@delvedor , nginx unit listen port from unit json config and starts the server.js itself
```js
function Server(requestListener) {
    EventEmitter.call(this);

    this.unit = new unit_lib.Unit();
    this.unit.server = this;

    this.unit.createServer();

    this.socket = Socket;
    this.request = ServerRequest;
    this.response = ServerResponse;

    if (requestListener) {
        this.on('request', requestListener);
    }
}

function createServer (requestHandler) {
    return new Server(requestHandler);
}

const serverFactory = (handler, opts) => {
  const server = createServer((req, res) => {
    handler(req, res);
  });
  return server;
};
```
If add fastify.listen
```js
const { createServer, IncomingMessage, ServerResponse } = require("unit-http");

require("http").ServerResponse = ServerResponse;
require("http").IncomingMessage = IncomingMessage;

const serverFactory = (handler, opts) => {
  const server = createServer((req, res) => {
    handler(req, res);
  });
  return server;
};

const fastify = require("fastify")({ serverFactory });

fastify.get("/", (req, reply) => {
  reply.send({ hello: "world" });
});

fastify.listen(8081, (err, address) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```
get an error
```bash
TypeError: Cannot read property 'remoteAddress' of undefined
    at _ipAsRemoteAddress (/home/vostrikov/site/frontend/node_modules/fastify/fastify.js:281:29)
    at Object.routeHandler [as handler] (/home/vostrikov/site/frontend/node_modules/fastify/fastify.js:303:5)
    at Router.lookup (/home/vostrikov/site/frontend/node_modules/find-my-way/index.js:338:14)
    at Router.defaultRoute (/home/vostrikov/site/frontend/node_modules/fastify/fastify.js:864:16)
    at Router._defaultRoute (/home/vostrikov/site/frontend/node_modules/find-my-way/index.js:516:14)
    at Router.lookup (/home/vostrikov/site/frontend/node_modules/find-my-way/index.js:336:36)
    at Server.createServer (/home/vostrikov/site/frontend/server.js:21:5)
    at Server.emit (events.js:189:13)
    at Server.emit_events (/usr/lib/node_modules/unit-http/http_server.js:382:12)
2019/03/15 22:42:19 [notice] 29941#29941 process 30009 exited with code 1
2019/03/15 22:42:19 [info] 30029#30029 "site_frontend" application started
```
if use unit server listen from official example with express js get an error:
```js
const serverFactory = (handler, opts) => {
  const server = createServer((req, res) => {
    handler(req, res);
  }).listen();
  return server;
```
```bash
TypeError: Cannot read property 'on' of undefined
    at build (/home/vostrikov/carsalon/frontend/node_modules/fastify/fastify.js:161:12)
    at Object.<anonymous> (/home/vostrikov/carsalon/frontend/server.js:26:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2019/03/15 22:50:09 [notice] 31498#31498 process 31621 exited with code 1
2019/03/15 22:50:09 [info] 31632#31632 "carsalon_frontend" application started
```

**Comment by mcollina** [comment]
Try:

```js
const { createServer, IncomingMessage, ServerResponse } = require("unit-http");

require("http").ServerResponse = ServerResponse;
require("http").IncomingMessage = IncomingMessage;

const serverFactory = (handler, opts) => {
  const server = createServer((req, res) => {
    console.log(req);
    handler(req, res);
  });
  return server;
};

const fastify = require("fastify")({ serverFactory });

fastify.get("/", (req, reply) => {
  reply.send({ hello: "world" });
});

fastify.ready();
```

**Comment by academici** [comment]
@mcollina, not work:
```bash
TypeError: Cannot read property 'remoteAddress' of undefined
    at _ipAsRemoteAddress (/home/vostrikov/carsalon/frontend/node_modules/fastify/fastify.js:281:29)
    at Object.routeHandler [as handler] (/home/vostrikov/carsalon/frontend/node_modules/fastify/fastify.js:303:5)
    at Router.lookup (/home/vostrikov/carsalon/frontend/node_modules/find-my-way/index.js:338:14)
    at Server.createServer (/home/vostrikov/carsalon/frontend/server.js:36:5)
    at Server.emit (events.js:189:13)
    at Server.emit_events (/usr/lib/node_modules/unit-http/http_server.js:382:12)
```

**Comment by mcollina** [comment]
It's an issue with `unit-http`: they need to add  [`req.connection`](https://nodejs.org/api/http.html#http_request_connection) property, as it's defined in Node.js core and used in https://github.com/fastify/fastify/blob/9c3f03f1aebd68bdd4500c0d413f72dbde5ee579/fastify.js#L262.

You should open it there.
