### ISSUE TITLE
Make ./server.sock in test random / and ensure it's removed at the end

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#1708]
## 🐛 Bug Report

In CITGM, we have spurious failures because of:

```
# Subtest: listen on socket
         1..3
         not ok 1 - listen EADDRINUSE: address already in use /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/npm_config_tmp/server.sock
           ---
           found:
             name: Error
             stack: >-
               Error: listen EADDRINUSE: address already in use
               /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/npm_config_tmp/server.sock
                   at Server.setupListenHandle [as _listen2] (net.js:1211:19)
                   at listenInCluster (net.js:1276:12)
                   at Server.listen (net.js:1375:5)
                   at /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/lib/server.js:136:14
                   at Object._encapsulateThreeParam (/home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/node_modules/avvio/boot.js:410:13)
                   at Boot.callWithCbOrNextTick (/home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/node_modules/avvio/boot.js:341:5)
                   at release (/home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/node_modules/fastq/queue.js:127:16)
                   at Object.resume (/home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/node_modules/fastq/queue.js:61:7)
                   at /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/node_modules/avvio/boot.js:155:20
                   at /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/fastify/node_modules/avvio/plugin.js:178:7
             message: >-
               listen EADDRINUSE: address already in use
               /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/npm_config_tmp/server.sock
             code: EADDRINUSE
             errno: EADDRINUSE
             syscall: listen
             address: >-
               /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/npm_config_tmp/server.sock
             port: -1
           at:
             line: 199
             column: 9
             file: test/listen.test.js
           stack: |
             test/listen.test.js:199:9
             Server.wrap (lib/server.js:77:9)
           source: |
             t.error(err)
           ...
         
         ok 2 - should be equal
         not ok 3 - should be equal
           ---
           found: null
           wanted: >-
             /home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/3d90567c-ae42-4ceb-b355-cbfcc3a27be1/npm_config_tmp/server.sock
           compare: ===
           at:
             line: 201
             column: 9
             file: test/listen.test.js
           stack: |
             test/listen.test.js:201:9
             Server.wrap (lib/server.js:77:9)
           source: |
             t.equal(address, sockFile)
           ...
         
         # failed 2 of 3 tests
     not ok 15 - listen on socket # time=93.783ms
````

## Expected behavior

No failures

## Your Environment

- *node version*: master
- *fastify version*: >=2.5.0
- *os*: Linux

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1856.
