### ISSUE TITLE
SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by mudivili** [fastify/fastify#1758]
I face this error with fastify. I am not able to debug as well.
Any one else faced this issue. I am able to debug till that the issue is not specific to fastify. But, to a module called `flatstr`.

Here is the error message:
```
(node:12702) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token %
    at handleError (/path/to/project/node_modules/fastify/lib/reply.js:345:3)
    at _Reply.Reply.send (/path/to/project/node_modules/fastify/lib/reply.js:68:5)
    at /path/to/project/node_modules/fastify/lib/wrapThenable.js:19:15
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:12702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:12702) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token %
    at handleError (/path/to/project/node_modules/fastify/lib/reply.js:345:3)
    at _Reply.Reply.send (/path/to/project/node_modules/fastify/lib/reply.js:68:5)
    at /path/to/project/node_modules/fastify/lib/wrapThenable.js:19:15
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:12702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:12702) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token %
    at handleError (/path/to/project/node_modules/fastify/lib/reply.js:345:3)
    at _Reply.Reply.send (/path/to/project/node_modules/fastify/lib/reply.js:68:5)
    at /path/to/project/node_modules/fastify/lib/wrapThenable.js:19:15
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:12702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:12702) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token %
    at handleError (/path/to/project/node_modules/fastify/lib/reply.js:345:3)
    at _Reply.Reply.send (/path/to/project/node_modules/fastify/lib/reply.js:68:5)
    at /path/to/project/node_modules/fastify/lib/wrapThenable.js:19:15
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:12702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```
This issue happens randomly.

In `reply.js`, at lines 104 & 345, stringified payload is passed to something called `flatstr`.

That throws this error. The `%` is in the source of `flatstr`.

It is:
```
'use strict'

if (!process.versions || !process.versions.node || parseInt(process.versions.node.split('.')[0]) >= 8) {
  try { 
    var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
  } catch (e) {
    try { 
      var v8 = require('v' + '8')
      v8.setFlagsFromString('--allow-natives-syntax')
      var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
      v8.setFlagsFromString('--no-allow-natives-syntax')
    } catch (e) {
      var flatstr = function flatstr(s) {
        Number(s)
        return s
      }
    }
  }
} else flatstr = function flatstr(s) {
  Number(s)
  return s
}

module.exports = flatstr
```

I have experienced this issue in both remote environment & also locally.
As this appears randomly, I am not able to provide with exact steps to reproduce this issue.

Even at time of writing this issue, I have debugger open & able to see the string passed to the `flatstr` function call. But, I am not able to find nothing more. If I restart the server, it might appear or not appear at all. 

I will post back, when I have more information.

## Your Environment

- *node version*: v12.0.0,v12.4.0
- *fastify version*: 1.14.6
- *os*: Linux

**Comment by mcollina** [comment]
What’s your setup? are you transpiling by any chance? If you could provide a “npm ls” or a script to reproduce it would be fantastic.


This has been fixed by later changes in flatstr, we might just need to bump the dependency.

**Comment by mudivili** [comment]
Operating System(Issue appears in 2 machines, same OS):
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
Node:
```
$ node -v
v12.4.0
$ npm -v 
6.9.0
```
```
$ node -v
v12.0.0
$ npm -v 
6.9.0
```

Usual Node.js setup. No trans-piling is happening. I have not yet found a way to reproduce the issue consistently. It happens randomly. I copied the string that throwed error & passed it to `flatstr` for a while. The issue did not appeared at all.  

```
$ npm ls
+-- chalk@2.4.2
| +-- ansi-styles@3.2.1
| | `-- color-convert@1.9.3
| |   `-- color-name@1.1.3
| +-- escape-string-regexp@1.0.5
| `-- supports-color@5.5.0
|   `-- has-flag@3.0.0
+-- config@3.1.0
| `-- json5@1.0.1
|   `-- minimist@1.2.0
+-- debug@4.1.1
| `-- ms@2.1.1
+-- eslint@5.16.0
| +-- @babel/code-frame@7.0.0
| | `-- @babel/highlight@7.0.0
| |   +-- chalk@2.4.2 deduped
| |   +-- esutils@2.0.2 deduped
| |   `-- js-tokens@4.0.0
| +-- ajv@6.10.0
| | +-- fast-deep-equal@2.0.1
| | +-- fast-json-stable-stringify@2.0.0
| | +-- json-schema-traverse@0.4.1
| | `-- uri-js@4.2.2
| |   `-- punycode@2.1.1
| +-- chalk@2.4.2 deduped
| +-- cross-spawn@6.0.5
| | +-- nice-try@1.0.5
| | +-- path-key@2.0.1
| | +-- semver@5.6.0 deduped
| | +-- shebang-command@1.2.0
| | | `-- shebang-regex@1.0.0
| | `-- which@1.3.1
| |   `-- isexe@2.0.0
| +-- debug@4.1.1 deduped
| +-- doctrine@3.0.0
| | `-- esutils@2.0.2 deduped
| +-- eslint-scope@4.0.3
| | +-- esrecurse@4.2.1
| | | `-- estraverse@4.2.0 deduped
| | `-- estraverse@4.2.0
| +-- eslint-utils@1.3.1
| +-- eslint-visitor-keys@1.0.0
| +-- espree@5.0.1
| | +-- acorn@6.1.1
| | +-- acorn-jsx@5.0.1
| | `-- eslint-visitor-keys@1.0.0 deduped
| +-- esquery@1.0.1
| | `-- estraverse@4.2.0 deduped
| +-- esutils@2.0.2
| +-- file-entry-cache@5.0.1
| | `-- flat-cache@2.0.1
| |   +-- flatted@2.0.0
| |   +-- rimraf@2.6.3
| |   | `-- glob@7.1.3 deduped
| |   `-- write@1.0.3
| |     `-- mkdirp@0.5.1 deduped
| +-- functional-red-black-tree@1.0.1
| +-- glob@7.1.3
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | +-- once@1.4.0 deduped
| | | `-- wrappy@1.0.2 deduped
| | +-- inherits@2.0.3
| | +-- minimatch@3.0.4 deduped
| | +-- once@1.4.0 deduped
| | `-- path-is-absolute@1.0.1
| +-- globals@11.11.0
| +-- ignore@4.0.6
| +-- import-fresh@3.0.0
| | +-- parent-module@1.0.1
| | | `-- callsites@3.1.0
| | `-- resolve-from@4.0.0
| +-- imurmurhash@0.1.4
| +-- inquirer@6.3.1
| | +-- ansi-escapes@3.2.0
| | +-- chalk@2.4.2 deduped
| | +-- cli-cursor@2.1.0
| | | `-- restore-cursor@2.0.0
| | |   +-- onetime@2.0.1
| | |   | `-- mimic-fn@1.2.0
| | |   `-- signal-exit@3.0.2 deduped
| | +-- cli-width@2.2.0
| | +-- external-editor@3.0.3
| | | +-- chardet@0.7.0
| | | +-- iconv-lite@0.4.24
| | | | `-- safer-buffer@2.1.2
| | | `-- tmp@0.0.33
| | |   `-- os-tmpdir@1.0.2
| | +-- figures@2.0.0
| | | `-- escape-string-regexp@1.0.5 deduped
| | +-- lodash@4.17.11 deduped
| | +-- mute-stream@0.0.7
| | +-- run-async@2.3.0
| | | `-- is-promise@2.1.0
| | +-- rxjs@6.5.1
| | | `-- tslib@1.9.3
| | +-- string-width@2.1.1
| | | +-- is-fullwidth-code-point@2.0.0
| | | `-- strip-ansi@4.0.0 deduped
| | +-- strip-ansi@5.2.0
| | | `-- ansi-regex@4.1.0
| | `-- through@2.3.8
| +-- js-yaml@3.13.1
| | +-- argparse@1.0.10
| | | `-- sprintf-js@1.0.3
| | `-- esprima@4.0.1
| +-- json-stable-stringify-without-jsonify@1.0.1
| +-- levn@0.3.0
| | +-- prelude-ls@1.1.2
| | `-- type-check@0.3.2
| |   `-- prelude-ls@1.1.2 deduped
| +-- lodash@4.17.11 deduped
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- natural-compare@1.4.0
| +-- optionator@0.8.2
| | +-- deep-is@0.1.3
| | +-- fast-levenshtein@2.0.6
| | +-- levn@0.3.0 deduped
| | +-- prelude-ls@1.1.2 deduped
| | +-- type-check@0.3.2 deduped
| | `-- wordwrap@1.0.0
| +-- path-is-inside@1.0.2
| +-- progress@2.0.3
| +-- regexpp@2.0.1
| +-- semver@5.6.0
| +-- strip-ansi@4.0.0
| | `-- ansi-regex@3.0.0
| +-- strip-json-comments@2.0.1
| +-- table@5.2.3
| | +-- ajv@6.10.0 deduped
| | +-- lodash@4.17.11 deduped
| | +-- slice-ansi@2.1.0
| | | +-- ansi-styles@3.2.1 deduped
| | | +-- astral-regex@1.0.0
| | | `-- is-fullwidth-code-point@2.0.0 deduped
| | `-- string-width@3.1.0
| |   +-- emoji-regex@7.0.3
| |   +-- is-fullwidth-code-point@2.0.0 deduped
| |   `-- strip-ansi@5.2.0
| |     `-- ansi-regex@4.1.0
| `-- text-table@0.2.0
+-- eslint-plugin-security@1.4.0
| `-- safe-regex@1.1.0
|   `-- ret@0.1.15
+-- fastify-multipart@0.7.0
| +-- busboy@0.3.0
| | `-- dicer@0.3.0
| |   `-- streamsearch@0.1.2
| +-- deepmerge@3.2.0
| +-- end-of-stream@1.4.1
| | `-- once@1.4.0 deduped
| `-- fastify-plugin@1.5.0
|   `-- semver@5.6.0 deduped
+-- husky@1.3.1
| +-- cosmiconfig@5.1.0
| | +-- import-fresh@2.0.0
| | | +-- caller-path@2.0.0
| | | | `-- caller-callsite@2.0.0
| | | |   `-- callsites@2.0.0
| | | `-- resolve-from@3.0.0
| | +-- is-directory@0.3.1
| | +-- js-yaml@3.12.2
| | | +-- argparse@1.0.10 deduped
| | | `-- esprima@4.0.1 deduped
| | +-- lodash.get@4.4.2
| | `-- parse-json@4.0.0
| |   +-- error-ex@1.3.2
| |   | `-- is-arrayish@0.2.1
| |   `-- json-parse-better-errors@1.0.2
| +-- execa@1.0.0
| | +-- cross-spawn@6.0.5 deduped
| | +-- get-stream@4.1.0
| | | `-- pump@3.0.0 deduped
| | +-- is-stream@1.1.0
| | +-- npm-run-path@2.0.2
| | | `-- path-key@2.0.1 deduped
| | +-- p-finally@1.0.0
| | +-- signal-exit@3.0.2
| | `-- strip-eof@1.0.0
| +-- find-up@3.0.0
| | `-- locate-path@3.0.0
| |   +-- p-locate@3.0.0
| |   | `-- p-limit@2.2.0
| |   |   `-- p-try@2.0.0
| |   `-- path-exists@3.0.0
| +-- get-stdin@6.0.0
| +-- is-ci@2.0.0
| | `-- ci-info@2.0.0
| +-- pkg-dir@3.0.0
| | `-- find-up@3.0.0 deduped
| +-- please-upgrade-node@3.1.1
| | `-- semver-compare@1.0.0
| +-- read-pkg@4.0.1
| | +-- normalize-package-data@2.5.0
| | | +-- hosted-git-info@2.7.1
| | | +-- resolve@1.10.0
| | | | `-- path-parse@1.0.6
| | | +-- semver@5.6.0 deduped
| | | `-- validate-npm-package-license@3.0.4
| | |   +-- spdx-correct@3.1.0
| | |   | +-- spdx-expression-parse@3.0.0 deduped
| | |   | `-- spdx-license-ids@3.0.3
| | |   `-- spdx-expression-parse@3.0.0
| | |     +-- spdx-exceptions@2.2.0
| | |     `-- spdx-license-ids@3.0.3 deduped
| | +-- parse-json@4.0.0 deduped
| | `-- pify@3.0.0
| +-- run-node@1.0.0
| `-- slash@2.0.0
+-- lodash@4.17.11
+-- /**** REDACTED ****/
| `-- pino@5.12.3
|   +-- fast-redact@1.5.0
|   +-- fast-safe-stringify@2.0.6
|   +-- flatstr@1.0.9
|   +-- pino-std-serializers@2.4.0
|   +-- quick-format-unescaped@3.0.2
|   `-- sonic-boom@0.7.3
|     `-- flatstr@1.0.9 deduped
+-- mocha@5.2.0
| +-- browser-stdout@1.3.1
| +-- commander@2.15.1
| +-- debug@3.1.0
| | `-- ms@2.0.0
| +-- diff@3.5.0
| +-- escape-string-regexp@1.0.5 deduped
| +-- glob@7.1.2
| | +-- fs.realpath@1.0.0 deduped
| | +-- inflight@1.0.6 deduped
| | +-- inherits@2.0.3 deduped
| | +-- minimatch@3.0.4 deduped
| | +-- once@1.4.0 deduped
| | `-- path-is-absolute@1.0.1 deduped
| +-- growl@1.10.5
| +-- he@1.1.1
| +-- minimatch@3.0.4 deduped
| +-- mkdirp@0.5.1 deduped
| `-- supports-color@5.4.0
|   `-- has-flag@3.0.0 deduped
+-- /**** REDACTED ****/
| +-- /**** REDACTED ****/
| | `-- /**** REDACTED ****/
| +-- debug@4.1.1 deduped
| +-- mongodb@3.2.3 deduped
| `-- /**** REDACTED ****/
+-- mongodb@3.2.3
| +-- mongodb-core@3.2.3
| | +-- bson@1.1.1
| | +-- require_optional@1.0.1
| | | +-- resolve-from@2.0.0
| | | `-- semver@5.6.0 deduped
| | +-- safe-buffer@5.1.2 deduped
| | `-- saslprep@1.0.2
| |   `-- sparse-bitfield@3.0.3
| |     `-- memory-pager@1.5.0
| `-- safe-buffer@5.1.2
+-- nyc@13.3.0
| +-- archy@1.0.0
| +-- arrify@1.0.1
| +-- caching-transform@3.0.1
| | +-- hasha@3.0.0
| | | `-- is-stream@1.1.0
| | +-- make-dir@1.3.0 deduped
| | +-- package-hash@3.0.0
| | | +-- graceful-fs@4.1.15
| | | +-- hasha@3.0.0 deduped
| | | +-- lodash.flattendeep@4.4.0
| | | `-- release-zalgo@1.0.0
| | |   `-- es6-error@4.1.1
| | `-- write-file-atomic@2.4.2
| |   +-- graceful-fs@4.1.15 deduped
| |   +-- imurmurhash@0.1.4
| |   `-- signal-exit@3.0.2 deduped
| +-- convert-source-map@1.6.0
| | `-- safe-buffer@5.1.2
| +-- find-cache-dir@2.0.0
| | +-- commondir@1.0.1
| | +-- make-dir@1.3.0 deduped
| | `-- pkg-dir@3.0.0
| |   `-- find-up@3.0.0 deduped
| +-- find-up@3.0.0
| | `-- locate-path@3.0.0
| |   +-- p-locate@3.0.0
| |   | `-- p-limit@2.1.0
| |   |   `-- p-try@2.0.0
| |   `-- path-exists@3.0.0
| +-- foreground-child@1.5.6
| | +-- cross-spawn@4.0.2
| | | +-- lru-cache@4.1.5
| | | | +-- pseudomap@1.0.2
| | | | `-- yallist@2.1.2
| | | `-- which@1.3.1 deduped
| | `-- signal-exit@3.0.2 deduped
| +-- glob@7.1.3
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | +-- once@1.4.0 deduped
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | +-- minimatch@3.0.4
| | | `-- brace-expansion@1.1.11
| | |   +-- balanced-match@1.0.0
| | |   `-- concat-map@0.0.1
| | +-- once@1.4.0
| | | `-- wrappy@1.0.2 deduped
| | `-- path-is-absolute@1.0.1
| +-- istanbul-lib-coverage@2.0.3
| +-- istanbul-lib-hook@2.0.3
| | `-- append-transform@1.0.0
| |   `-- default-require-extensions@2.0.0
| |     `-- strip-bom@3.0.0
| +-- istanbul-lib-instrument@3.1.0
| | +-- @babel/generator@7.3.4
| | | +-- @babel/types@7.3.4 deduped
| | | +-- jsesc@2.5.2
| | | +-- lodash@4.17.11 deduped
| | | +-- source-map@0.5.7
| | | `-- trim-right@1.0.1
| | +-- @babel/parser@7.3.4
| | +-- @babel/template@7.2.2
| | | +-- @babel/code-frame@7.0.0 deduped
| | | +-- @babel/parser@7.3.4 deduped
| | | `-- @babel/types@7.3.4 deduped
| | +-- @babel/traverse@7.3.4
| | | +-- @babel/code-frame@7.0.0 deduped
| | | +-- @babel/generator@7.3.4 deduped
| | | +-- @babel/helper-function-name@7.1.0
| | | | +-- @babel/helper-get-function-arity@7.0.0
| | | | | `-- @babel/types@7.3.4 deduped
| | | | +-- @babel/template@7.2.2 deduped
| | | | `-- @babel/types@7.3.4 deduped
| | | +-- @babel/helper-split-export-declaration@7.0.0
| | | | `-- @babel/types@7.3.4 deduped
| | | +-- @babel/parser@7.3.4 deduped
| | | +-- @babel/types@7.3.4 deduped
| | | +-- debug@4.1.1 deduped
| | | +-- globals@11.11.0 deduped
| | | `-- lodash@4.17.11 deduped
| | +-- @babel/types@7.3.4
| | | +-- esutils@2.0.2 deduped
| | | +-- lodash@4.17.11 deduped
| | | `-- to-fast-properties@2.0.0
| | +-- istanbul-lib-coverage@2.0.3
| | `-- semver@5.6.0 deduped
| +-- istanbul-lib-report@2.0.4
| | +-- istanbul-lib-coverage@2.0.3 deduped
| | +-- make-dir@1.3.0 deduped
| | `-- supports-color@6.1.0
| |   `-- has-flag@3.0.0
| +-- istanbul-lib-source-maps@3.0.2
| | +-- debug@4.1.1
| | | `-- ms@2.1.1
| | +-- istanbul-lib-coverage@2.0.3 deduped
| | +-- make-dir@1.3.0 deduped
| | +-- rimraf@2.6.3 deduped
| | `-- source-map@0.6.1
| +-- istanbul-reports@2.1.1
| | `-- handlebars@4.1.0
| |   +-- async@2.6.2
| |   | `-- lodash@4.17.11
| |   +-- optimist@0.6.1
| |   | +-- minimist@0.0.10
| |   | `-- wordwrap@0.0.3
| |   +-- source-map@0.6.1
| |   `-- uglify-js@3.4.9
| |     +-- commander@2.17.1
| |     `-- source-map@0.6.1
| +-- make-dir@1.3.0
| | `-- pify@3.0.0
| +-- merge-source-map@1.1.0
| | `-- source-map@0.6.1
| +-- resolve-from@4.0.0
| +-- rimraf@2.6.3
| | `-- glob@7.1.3 deduped
| +-- signal-exit@3.0.2
| +-- spawn-wrap@1.4.2
| | +-- foreground-child@1.5.6 deduped
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | +-- os-homedir@1.0.2
| | +-- rimraf@2.6.3 deduped
| | +-- signal-exit@3.0.2 deduped
| | `-- which@1.3.1
| |   `-- isexe@2.0.0
| +-- test-exclude@5.1.0
| | +-- arrify@1.0.1 deduped
| | +-- minimatch@3.0.4 deduped
| | +-- read-pkg-up@4.0.0
| | | +-- find-up@3.0.0 deduped
| | | `-- read-pkg@3.0.0
| | |   +-- load-json-file@4.0.0
| | |   | +-- graceful-fs@4.1.15 deduped
| | |   | +-- parse-json@4.0.0
| | |   | | +-- error-ex@1.3.2
| | |   | | | `-- is-arrayish@0.2.1
| | |   | | `-- json-parse-better-errors@1.0.2
| | |   | +-- pify@3.0.0 deduped
| | |   | `-- strip-bom@3.0.0 deduped
| | |   +-- normalize-package-data@2.5.0
| | |   | +-- hosted-git-info@2.7.1
| | |   | +-- resolve@1.10.0
| | |   | | `-- path-parse@1.0.6
| | |   | +-- semver@5.6.0
| | |   | `-- validate-npm-package-license@3.0.4
| | |   |   +-- spdx-correct@3.1.0
| | |   |   | +-- spdx-expression-parse@3.0.0 deduped
| | |   |   | `-- spdx-license-ids@3.0.3
| | |   |   `-- spdx-expression-parse@3.0.0
| | |   |     +-- spdx-exceptions@2.2.0
| | |   |     `-- spdx-license-ids@3.0.3 deduped
| | |   `-- path-type@3.0.0
| | |     `-- pify@3.0.0 deduped
| | `-- require-main-filename@1.0.1
| +-- uuid@3.3.2
| +-- yargs@12.0.5
| | +-- cliui@4.1.0
| | | +-- string-width@2.1.1 deduped
| | | +-- strip-ansi@4.0.0
| | | | `-- ansi-regex@3.0.0
| | | `-- wrap-ansi@2.1.0
| | |   +-- string-width@1.0.2
| | |   | +-- code-point-at@1.1.0
| | |   | +-- is-fullwidth-code-point@1.0.0
| | |   | | `-- number-is-nan@1.0.1
| | |   | `-- strip-ansi@3.0.1 deduped
| | |   `-- strip-ansi@3.0.1
| | |     `-- ansi-regex@2.1.1
| | +-- decamelize@1.2.0
| | +-- find-up@3.0.0 deduped
| | +-- get-caller-file@1.0.3
| | +-- os-locale@3.1.0
| | | +-- execa@1.0.0
| | | | +-- cross-spawn@6.0.5
| | | | | +-- nice-try@1.0.5
| | | | | +-- path-key@2.0.1
| | | | | +-- semver@5.6.0 deduped
| | | | | +-- shebang-command@1.2.0
| | | | | | `-- shebang-regex@1.0.0
| | | | | `-- which@1.3.1 deduped
| | | | +-- get-stream@4.1.0
| | | | | `-- pump@3.0.0
| | | | |   +-- end-of-stream@1.4.1
| | | | |   | `-- once@1.4.0 deduped
| | | | |   `-- once@1.4.0 deduped
| | | | +-- is-stream@1.1.0 deduped
| | | | +-- npm-run-path@2.0.2
| | | | | `-- path-key@2.0.1 deduped
| | | | +-- p-finally@1.0.0
| | | | +-- signal-exit@3.0.2 deduped
| | | | `-- strip-eof@1.0.0
| | | +-- lcid@2.0.0
| | | | `-- invert-kv@2.0.0
| | | `-- mem@4.1.0
| | |   +-- map-age-cleaner@0.1.3
| | |   | `-- p-defer@1.0.0
| | |   +-- mimic-fn@1.2.0
| | |   `-- p-is-promise@2.0.0
| | +-- require-directory@2.1.1
| | +-- require-main-filename@1.0.1 deduped
| | +-- set-blocking@2.0.0
| | +-- string-width@2.1.1
| | | +-- is-fullwidth-code-point@2.0.0
| | | `-- strip-ansi@4.0.0 deduped
| | +-- which-module@2.0.0
| | +-- y18n@4.0.0
| | `-- yargs-parser@11.1.1 deduped
| `-- yargs-parser@11.1.1
|   +-- camelcase@5.0.0
|   `-- decamelize@1.2.0 deduped
+-- pump@3.0.0
| +-- end-of-stream@1.4.1 deduped
| `-- once@1.4.0
|   `-- wrappy@1.0.2
+-- /**** REDACTED ****/
| +-- ajv@6.10.0 deduped
| +-- ajv-keywords@3.4.0
| +-- lodash@4.17.11 deduped
| +-- /**** REDACTED ****/
| `-- /**** REDACTED ****/
|   +-- file-type@10.11.0
|   +-- moment@2.24.0
|   `-- read-chunk@3.2.0
|     +-- pify@4.0.1
|     `-- with-open-file@0.1.6
|       +-- p-finally@1.0.0 deduped
|       +-- p-try@2.2.0
|       `-- pify@4.0.1 deduped
+-- /**** REDACTED ****/
| +-- fastify@1.14.6
| | +-- @types/pino@4.16.1
| | | +-- @types/events@3.0.0
| | | `-- @types/node@11.13.7
| | +-- abstract-logging@1.0.0
| | +-- ajv@6.10.0 deduped
| | +-- avvio@5.9.0
| | | +-- debug@3.2.6
| | | | `-- ms@2.1.1 deduped
| | | `-- fastq@1.6.0
| | |   `-- reusify@1.0.4 deduped
| | +-- bourne@1.1.2
| | +-- end-of-stream@1.4.1 deduped
| | +-- fast-json-stringify@1.15.2
| | | +-- ajv@6.10.0 deduped
| | | `-- deepmerge@3.2.0 deduped
| | +-- find-my-way@1.18.1
| | | +-- fast-decode-uri-component@1.0.1
| | | +-- safe-regex@1.1.0 deduped
| | | `-- semver-store@0.3.0
| | +-- flatstr@1.0.9 deduped
| | +-- light-my-request@3.3.0
| | | +-- ajv@6.10.0 deduped
| | | `-- readable-stream@3.3.0
| | |   +-- inherits@2.0.3 deduped
| | |   +-- string_decoder@1.2.0
| | |   | `-- safe-buffer@5.1.2 deduped
| | |   `-- util-deprecate@1.0.2 deduped
| | +-- middie@3.2.1
| | | +-- path-to-regexp@2.4.0
| | | `-- reusify@1.0.4
| | +-- pino@4.17.6
| | | +-- chalk@2.4.2 deduped
| | | +-- fast-json-parse@1.0.3
| | | +-- fast-safe-stringify@1.2.3
| | | +-- flatstr@1.0.9 deduped
| | | +-- pino-std-serializers@2.4.0 deduped
| | | +-- pump@3.0.0 deduped
| | | +-- quick-format-unescaped@1.1.2
| | | | `-- fast-safe-stringify@1.2.3 deduped
| | | `-- split2@2.2.0
| | |   `-- through2@2.0.5
| | |     +-- readable-stream@2.3.6
| | |     | +-- core-util-is@1.0.2 deduped
| | |     | +-- inherits@2.0.3 deduped
| | |     | +-- isarray@1.0.0 deduped
| | |     | +-- process-nextick-args@2.0.0 deduped
| | |     | +-- safe-buffer@5.1.2 deduped
| | |     | +-- string_decoder@1.1.1
| | |     | | `-- safe-buffer@5.1.2 deduped
| | |     | `-- util-deprecate@1.0.2 deduped
| | |     `-- xtend@4.0.1
| | +-- proxy-addr@2.0.5
| | | +-- forwarded@0.1.2
| | | `-- ipaddr.js@1.9.0
| | +-- rfdc@1.1.2
| | `-- tiny-lru@2.0.0
| `-- /**** REDACTED ****/
+-- /**** REDACTED ****/
+-- /**** REDACTED ****/
| +-- axios@0.18.0
| | +-- follow-redirects@1.7.0
| | | `-- debug@3.2.6
| | |   `-- ms@2.1.1 deduped
| | `-- is-buffer@1.1.6
| +-- debug@4.1.1 deduped
| +-- fastify@1.14.6 deduped
| `-- /**** REDACTED ****/
+-- should@13.2.3
| +-- should-equal@2.0.0
| | `-- should-type@1.4.0 deduped
| +-- should-format@3.0.3
| | +-- should-type@1.4.0 deduped
| | `-- should-type-adaptors@1.1.0 deduped
| +-- should-type@1.4.0
| +-- should-type-adaptors@1.1.0
| | +-- should-type@1.4.0 deduped
| | `-- should-util@1.0.0 deduped
| `-- should-util@1.0.0
+-- sinon@7.3.2
| +-- @sinonjs/commons@1.4.0
| | `-- type-detect@4.0.8
| +-- @sinonjs/formatio@3.2.1
| | +-- @sinonjs/commons@1.4.0 deduped
| | `-- @sinonjs/samsam@3.3.1 deduped
| +-- @sinonjs/samsam@3.3.1
| | +-- @sinonjs/commons@1.4.0 deduped
| | +-- array-from@2.1.1
| | `-- lodash@4.17.11 deduped
| +-- diff@3.5.0 deduped
| +-- lolex@4.0.1
| +-- nise@1.4.10
| | +-- @sinonjs/formatio@3.2.1 deduped
| | +-- @sinonjs/text-encoding@0.7.1
| | +-- just-extend@4.0.2
| | +-- lolex@2.7.5
| | `-- path-to-regexp@1.7.0
| |   `-- isarray@0.0.1
| `-- supports-color@5.5.0 deduped
+-- stream-meter@1.0.4
| `-- readable-stream@2.3.6
|   +-- core-util-is@1.0.2
|   +-- inherits@2.0.3 deduped
|   +-- isarray@1.0.0
|   +-- process-nextick-args@2.0.0
|   +-- safe-buffer@5.1.2 deduped
|   +-- string_decoder@1.1.1
|   | `-- safe-buffer@5.1.2 deduped
|   `-- util-deprecate@1.0.2
+-- /**** REDACTED ****/
| `-- sinon@7.3.2 deduped
`-- uuid@3.3.2
```

**Comment by mcollina** [comment]
This is fixed in the latest version of flatstr. Update your dependencies (remove node_modules and remove package-lock.json).
