### ISSUE TITLE
'Multipart: Boundary not found

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify#1784]
i use "fastify": "^2.7.1", node js 12.7.0

Hello, my server down

Error

```
D:\js\mongodb\node_modules\busboy\lib\types\multipart.js:58
    throw new Error('Multipart: Boundary not found');
    ^

Error: Multipart: Boundary not found
    at new Multipart (D:\js\mongodb\node_modules\busboy\lib\types\multipart.js:58:11)
    at Multipart (D:\js\mongodb\node_modules\busboy\lib\types\multipart.js:26:12)
    at Busboy.parseHeaders (D:\js\mongodb\node_modules\busboy\lib\main.js:71:22)
    at new Busboy (D:\js\mongodb\node_modules\busboy\lib\main.js:22:10)
    at processMultipart (D:\js\mongodb\node_modules\express-fileupload\lib\processMultipart.js:31:12)
    at D:\js\mongodb\node_modules\express-fileupload\lib\index.js:25:5
    at Holder.done (D:\js\mongodb\node_modules\middie\middie.js:112:11)
    at Object.run (D:\js\mongodb\node_modules\middie\middie.js:59:12)
    at middlewareCallback (D:\js\mongodb\node_modules\fastify\lib\route.js:356:27)
    at Object.routeHandler [as handler] (D:\js\mongodb\node_modules\fastify\lib\route.js:336:7)
    at Router.lookup (D:\js\mongodb\node_modules\find-my-way\index.js:338:14)
    at Server.emit (events.js:203:13)
    at parserOnIncoming (_http_server.js:733:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
[nodemon] app crashed - waiting for file changes before starting...

```

Server

```
//HTTP SERVER
const fastify = require('fastify')({
    logger: false,
    http2: false,
});

const fileUpload = require('fastify-file-upload')
fastify.register(fileUpload)
fastify.use(require('cors')());
fastify.use('/public', serveStatic(path.join(serverDirectory, '/public')))

fastify.post('/load', async (request, reply) => {
    console.log( 'load load load load load' )
    reply.send( { 'reply': 'send' } )
});

fastify.listen(3000, '127.0.0.1', (err, address) => {
    console.log(address)
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
})

```
i send data on this server use axios, and bahhh... always

**Comment by mcollina** [comment]
Can you add a full example? You should probably use fastify-multipart instead of express-fileupload.

**Comment by borodadada** [comment]
```
                let formData = new formdata();
                formData.append("query", JSON.stringify( { aaaa:'aaaaaaaaa' } ) );
                formData.append("data", JSON.stringify( { bbbb:'bbbbbbbbb' } ) );
        
                axios.post( 'http://127.0.0.1:3000/load', formData, {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'multipart/form-data'
                    }
                })
                .then( (response)=> {
                    console.log(response)
                })
                .catch( (error)=> {
                    console.log('error')
                }); 
```

**Comment by jsumners** [comment]
A full example of your server, not your request. Just a bare minimum amount of code to replicate the failing server code.

**Comment by borodadada** [comment]
update first comment, all that i have

**Comment by mcollina** [comment]
I would recommend you to open this issue in https://github.com/huangang/fastify-file-upload or use fastify-multipart instead.

fastify-file-upload is not maintained by us.

**Comment by borodadada** [comment]
i tested, result
`
let formData = new formdata();

                axios.post( 'http://localhost:3000/load', formData, {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'multipart/form-data'
                    }
                })
`
formData not work. Data does not come to the server

**Comment by YuriFontella** [comment]
I have a question related to FormData but without this error message.
I was making the request using FormData ()

```
  const onChange = async (e) => {
    e.preventDefault()

    let data = new FormData()

    data.append('file', e.target.files[0])
    data.append('client_id', state.client.id)

    await request('/uploads', { method: 'post', data: data })

  }
```

I get the data like that, and the upload was going perfectly. However, the body data client_id was not coming.

```
  app.post('/', async (request, reply) => {

    const data = await request.file()

    await pump(data.file, fs.createWriteStream(path.resolve('public/uploads', data.filename)))

    reply.code(201).send(true)
  })
```

Checking the documentation, I realized that I had to add the object ```{ attachFieldsToBody: true }``` to the fastify-multipart register parameter. 

Now I have access to the value of client_id, but i'm not able to save the image in the folder.
How do I access the image to save to the folder?  I tried ```request.body.file.file``` but there is an invalid image for the folder.

request.body.file content

```
{
  fieldname: 'file',
  filename: 'luffy-op.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  file: FileStream {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: true,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      finish: [Function: onfinish],
      error: [Function: onerror],
      close: [Function: onclose],
      readable: [Function: bound onReadable]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    truncated: false,
    _read: [Function],
    [Symbol(kCapture)]: false
  },
  fields: {
    file: [Circular],
    client_id: {
      fieldname: 'client_id',
      value: '1000',
      fieldnameTruncated: false,
      valueTruncated: false,
      fields: [Circular]
    }
  },
  _buf: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 02 00 1c 00 1c 00 00 ff db 00 43 00 03 02 02 03 02 02 03 03 03 03 04 03 03 04 05 08 05 05 04 04 05 0a 07 07 06 ... 47655 more bytes>,
  toBuffer: [AsyncFunction: toBuffer]
}
```

Thanks.

**Comment by mcollina** [comment]
You should use https://github.com/fastify/fastify-multipart#handle-multiple-file-streams-and-fields.

**Comment by mirzagirl** [comment]
const onSubmit=async (data)=>{
      var formData = new FormData();
      formData.append('file',data.file[0]);
    //worked fine for me in post man add  "Content-Type": "multipart/form-data" and in form data key-> file 

      const res = await axios.post("http://localhost:4000/uploadFile",
         formData,
         {
           headers: {
                 'Accept': 'application/json',
                "Content-Type": "multipart/form-data",
                'authorization': userToken,
                'Access-Control-Allow-Origin': '*'
              }
          }
          ).then((res) =>console.log("res",res)).catch((error)=>{console.log(error.message);});
  }
  return (
    <div className="App">
    <form onSubmit={handleSubmit(onSubmit)}>
        <input type="file" {...register("file")} />

        <input type="submit" />
    </form>
</div>
  );
};
export default UploadFile;
