### ISSUE TITLE
Hello world with a error handler throws 404

### ISSUE THREAD

**Issue by sarneeh** [fastify/fastify#1822]
## 🐛 Bug Report

I've created a simple "Hello World" `fastify` example with a errorHandler, and it always throws a 404. Why?

## To Reproduce

```js
const fastify = require("fastify");

const server = fastify();

server.setErrorHandler(error => {
  console.log("hello error!", error);
});

server.get("/test", (request, reply) => {
  reply.send({ hello: "world" });
});

server.listen(8080, error => {
  if (error) throw error;
  console.log("Listening...");
});

```

## Expected behavior

The response is sent successfully so I'd not expect any errors here, especially a 404.

Paste the results here:

```js
hello error! Error: Not Found
    at Context.basic404 [as handler] (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/lib/fourOhFour.js:52:26)
    at preHandlerCallback (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/lib/handleRequest.js:112:30)
    at preValidationCallback (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/lib/handleRequest.js:101:5)
    at handler (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/lib/handleRequest.js:70:5)
    at handleRequest (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/lib/handleRequest.js:19:5)
    at onRunMiddlewares (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/fastify.js:357:7)
    at middlewareCallback (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/fastify.js:338:7)
    at Object.routeHandler [as handler] (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/fastify.js:324:7)
    at Router.lookup (/home/jsarnowski/Workshop/fastify-static-error/node_modules/find-my-way/index.js:338:14)
    at Router.defaultRoute (/home/jsarnowski/Workshop/fastify-static-error/node_modules/fastify/fastify.js:635:23)
```

## Your Environment

- *node version*: 12.6.0
- *fastify version*: 2.7.1
- *os*: Linux

**Comment by mcollina** [comment]
I think you should use https://www.fastify.io/docs/latest/Server/#setnotfoundhandler.

**Comment by sarneeh** [comment]
@mcollina I know I could use `setNotFoundHandler`, my question is why this error has been thrown in the first place? The request has been completed with a 200, and I get a 404 error in my logs. This is weird :smile:

**Comment by jsumners** [comment]
Did you issue the test request with a web browser? If so, the error is probably a favicon request.

**Comment by sarneeh** [comment]
@jsumners Oh god! You're right. I guess I need to stop creating GitHub requests while my brain is off already :sweat_smile: Sorry for this!
