### ISSUE TITLE
Using custom AJV breaks resolving references

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify#1855]
## 🐛 Bug Report

When using a custom AJV instance as described in the documentation (https://www.fastify.io/docs/latest/Validation-and-Serialization/#schema-compiler) one cannot provide a schema with references as a response schema.

## To Reproduce

```js
'use strict';

const AJV = require('ajv');
const ajv = new AJV();

ajv.addSchema({
  $id: 'urn:schema:foo',
  definitions: {
    foo: { type: 'string' }
  },

  type: 'object',
  properties: {
    foo: { $ref: '#/definitions/foo' }
  }
});

ajv.addSchema({
  $id: 'urn:schema:response',
  type: 'object',
  properties: {
    foo: { $ref: 'urn:schema:foo#/definitions/foo' }
  }
});

const fastify = require('fastify')();
fastify.setSchemaCompiler(schema => ajv.compile(schema));

fastify.route({
  path: '/',
  method: 'GET',
  schema: {
    response: {
      '2xx': ajv.getSchema('urn:schema:response').schema
    }
  },
  handler(req, reply) {
    reply.send({ foo: 'bar' });
  }
});

fastify.inject({ url: '/' }, (err, response) => {
  if (err) {
    throw err;
  }
  console.log(response.body);
});
```

## Expected behavior

The route should register and resolve references correctly.

Paste the results here:

```js
/private/tmp/17/fastify-custom-ajv/index.js:44
    throw err;
    ^
FastifyError [FST_ERR_SCH_BUILD]: FST_ERR_SCH_BUILD: Failed building the schema for GET: /, due error Cannot read property '$ref' of undefined
    at Object.afterRouteAdded (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/fastify/2.8.0/node_modules/fastify/lib/route.js:224:37)
    at after (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/fastify/2.8.0/node_modules/fastify/lib/route.js:165:25)
    at Object._encapsulateThreeParam (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/avvio/6.2.2/node_modules/avvio/boot.js:417:7)
    at Boot.callWithCbOrNextTick (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/avvio/6.2.2/node_modules/avvio/boot.js:339:5)
    at Boot._after (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/avvio/6.2.2/node_modules/avvio/boot.js:230:26)
    at Plugin.exec (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/avvio/6.2.2/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/avvio/6.2.2/node_modules/avvio/plugin.js:175:10)
    at Task.release (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/fastq/1.6.0/node_modules/fastq/queue.js:127:16)
    at worked (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/fastq/1.6.0/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/private/tmp/17/fastify-custom-ajv/node_modules/.registry.npmjs.org/avvio/6.2.2/node_modules/avvio/plugin.js:178:7)
```

## Your Environment

- *node version*: 10.16.3
- *fastify version*: 2.8.0
- *os*: Mac

**Comment by jsumners** [comment]
I'd also accept being able to supply an already compiled schema for route schemas.

**Comment by Eomm** [comment]
To solve you need to add the schema to fastify:

```
ajv.addSchema(a)
ajv.addSchema(b)
fastify.addSchema(a)
fastify.addSchema(b)
```

> one cannot provide a schema with references as a response schema

The response serializer cannot be customized, for this reason we need to get the schemas from the user:

https://github.com/fastify/fastify/blob/13a228331af956573bff071df305f0c5d2d1791e/lib/validation.js#L14

I was thinking that an `onAddSchema` hook could ease the dev-life and create new opportunities for plugins

**Comment by jsumners** [comment]
I’m not storing anything other than route schemas on the Fastify instance. My custom AJV instance is populated by reading a directory of schemas in another module and AJV does not expose the list of registered schemas. When Fastify has a custom complier it should be using that compiler to look up references.

**Comment by jsumners** [comment]
Also, I am not customizing the response serializer. Merely providing a schema for the standard one.

**Comment by Eomm** [comment]
We should integrate this automation then:

```
fastify.addSchema(ajv.getSchema('urn:schema:response').schema)
fastify.addSchema(ajv.getSchema('urn:schema:foo').schema)
```

But we can't use the `.setSchemaCompiler` because its value is only a function and not an instance of an object.

Maybe a `fastify.setSchemaResolver(fn)`, where fn is `function($ref): JSON schema` could solve this for v2

**Comment by jsumners** [comment]
That sounds like a fair solution.

**Comment by jsumners** [comment]
If you’re able to get to it before me then feel free. The _earliest_ I’ll even be able to look at it is Saturday. And I’m not very familiar with the code around validation.

**Comment by bneigher** [comment]
Can you guys patch fastify v1 with this? :)

**Comment by prenaissance** [comment]
If anyone is still encountering this, here is what fixed this in my project:

```diff
app.addSchema(ChildSchema); // this errors as not resolving
app.addSchema(MySchema); // this is using "ChildSchema"
app.get(
  "",
  {
    schema: {
      response: {
-        200: MixinUsing(MySchema),
+        200: MixinUsing(Type.Ref(MySchema)),
      },
    },
  }, /* some handler */);
```

Swagger does not encounter any errors, but AJV does, making this harder to catch without integration/manual testing.
