### ISSUE TITLE
UnhandledPromiseRejectionWarning: RangeError 

### ISSUE THREAD

**Issue by blacksmoke26** [fastify/fastify#1920]
## 🐛 Bug Report

I was redirecting from one URL to another. I can't describe it now because I am still investigating this issue. Once done, I will try to write the steps.

```js
(node:16808) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:241:11)
    at onSendEnd (/api/node_modules/fastify/lib/reply.js:343:9)
    at wrapOnSendEnd (/api/node_modules/fastify/lib/reply.js:325:5)
    at next (/api/node_modules/fastify/lib/hooks.js:101:7)
    at handleResolve (/api/node_modules/fastify/lib/hooks.js:112:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:16808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```

## Your Environment

- *node version*: 12.11.1
- *fastify version*: >=2.10.0
- *os*: Linux

**Comment by mcollina** [comment]
It would be very helpful to have a way to reproduce this. It's a bit hard to fix without a repro.
