### ISSUE TITLE
TypeError View is not a constructor when using Express middleware with fastify-normalize-request-reply

### ISSUE THREAD

**Issue by kevzettler** [fastify/fastify#2062]
## 🐛 Bug Report

I'm trying to use an express middleware https://github.com/vcapretz/bull-board in a fastify server.

Fastify is throwing the following error from fastify-normalize-request-reply

```
ypeError: View is not a constructor
    at Object.render (/Users/kevzettler/code/geneva/talk-node/node_modules/fastify-normalize-request-reply/create-app.js:121:14)
    at ServerResponse.render (/Users/kevzettler/code/geneva/talk-node/node_modules/fastify-normalize-request-reply/normalize-reply.js:998:9)
    at module.exports (/Users/kevzettler/code/geneva/talk-node/node_modules/bull-board/routes/index.js:3:7)
    at /Users/kevzettler/code/geneva/talk-node/node_modules/express-async-router/index.js:92:32
    at Layer.handle [as handle_request] (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/kevzettler/code/geneva/talk-node/node_modules/express/lib/router/index.js:335:12)
```

This is stemming from this line:

https://github.com/ericrglass/fastify-normalize-request-reply/blob/master/create-app.js#L119

What does this plugin expect that `app.get('view')` value to be?

**Comment by kevzettler** [comment]
meant to file this at fastify-normalize-request-reply repo

**Comment by gustawdaniel** [comment]
This is good general question:

> How to use express middleware in fastify? Is there any algorithm to convert express middleware to fastify compatible version?

**Comment by RafaelGSS** [comment]
We have this answer on the [doc middleware](https://github.com/fastify/fastify/blob/master/docs/Middleware.md#middleware)
