### ISSUE TITLE
Expose is404 in request object

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify#2143]
## 🚀 Feature Proposal

In some cases, it might be useful for our users to know if they are inside a 404 handling or not. We can quickly check it internally via the `kFourOhFourContext` symbol, but I think it would be great to expose it in our public API via the request object.

## Motivation

A use case example can be found [here](https://twitter.com/ThisIsMissEm/status/1240644657970806791).
TL;DR, you may not want to parse the body in case of a 404 request and close the request as soon as possible.

## Example

```js
fastify.addHook('onRequest', (req, reply, done) => {
  if (req.is404) {
    // specific handling
  }
  done()
})
```

The `is404` should always be present in the request object defaulting to `false`, and should be set to `true` automatically by Fastify.

**Comment by mcollina** [comment]
I would write this as a getter instead, so we don't have to do set anything on the actual object. All the relevant info is already there.

@delvedor can you post your snippet on how the info can be found?

**Comment by delvedor** [comment]
If we want to add this in the request object, it can't be exposed as a getter, as the context object that holds this information lives in the reply object.

The snippet:
https://gist.github.com/delvedor/d560e6805e325c546a21b0b4a97268cd

**Comment by ThisIsMissEm** [comment]
<details>
<summary>So the actual error we saw in our logs was these events, clearly, it's for a route that doesn't exist in a node.js server, as it's a spam/hacking bot in action.</summary>

```
{
	"id": "AQAAAXCu79SHrZ0BPAAAAABBWEN1NzlYQngzVVQwby1pbmdBQQ",
	"content": {
		"timestamp": "2020-03-06T08:21:58.023Z",
		"tags": [
			"[sanitised]"
		],
		"host": "[sanitised]",
		"service": "[sanitised]",
		"attributes": {
			"pid": 38,
			"msg": "request completed",
			"res": {
				"statusCode": 415
			},
			"hostname": "[sanitised]",
			"level": 30,
			"responseTime": 3.5231821537017822,
			"v": 1,
			"module": "Application",
			"name": "[sanitised]",
			"time": 1583482918022,
			"reqId": 169106
		}
	}
}

{
	"id": "AQAAAXCu79SFrZ0BOwAAAABBWEN1NzlYQngzVVQwby1pbmNBQQ",
	"content": {
		"timestamp": "2020-03-06T08:21:58.021Z",
		"tags": [
			"[sanitised]"
		],
		"host": "[sanitised]",
		"service": "[sanitised]",
		"attributes": {
			"pid": 38,
			"msg": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: application/x-www-form-urlencoded",
			"res": {
				"statusCode": 415
			},
			"hostname": "[sanitised]",
			"err": {
				"stack": "FastifyError [FST_ERR_CTP_INVALID_MEDIA_TYPE]: FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: application/x-www-form-urlencoded\n    at ContentTypeParser.run (node_modules/fastify/lib/contentTypeParser.js:92:16)\n    at handleRequest (node_modules/fastify/lib/handleRequest.js:36:39)\n    at onRunMiddlewares (node_modules/fastify/lib/middleware.js:22:5)\n    at middlewareCallback (node_modules/fastify/lib/route.js:365:5)\n    at next (node_modules/fastify/lib/hooks.js:66:7)\n    at Object.fastifyCookieOnReqHandler (node_modules/fastify-cookie/plugin.js:37:3)\n    at hookIterator (node_modules/fastify/lib/hooks.js:124:10)\n    at next (node_modules/fastify/lib/hooks.js:70:20)\n    at node_modules/dd-trace/packages/datadog-plugin-fastify/src/fastify.js:32:65\n    at node_modules/dd-trace/packages/dd-trace/src/plugins/util/web.js:67:60",
				"code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
				"name": "FastifyError [FST_ERR_CTP_INVALID_MEDIA_TYPE]",
				"type": "FastifyError",
				"message": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: application/x-www-form-urlencoded",
				"statusCode": 415
			},
			"level": 30,
			"v": 1,
			"module": "Application",
			"name": "[sanitised]",
			"time": 1583482918020,
			"reqId": 169106
		}
	}
}

{
	"id": "AQAAAXCu79SDrZ0BOgAAAABBWEN1NzlYQngzVVQwby1pbllBQQ",
	"content": {
		"timestamp": "2020-03-06T08:21:58.019Z",
		"tags": [ "[sanitised]" ],
		"host": "[sanitised]",
		"service": "[sanitised]",
		"attributes": {
			"pid": 38,
			"msg": "incoming request",
			"hostname": "[sanitised]",
			"level": 30,
			"v": 1,
			"module": "Application",
			"name": "[sanitised]-service",
			"time": 1583482918019,
			"reqId": 169106,
			"req": {
				"hostname": "[sanitised]",
				"method": "POST",
				"remotePort": 64723,
				"url": "/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php",
				"remoteAddress": "10.104.0.38"
			}
		}
	}
}
```</details>

So, essentially it'd be very nice to catch that it was a 404 and just don't care about parsing the content-type or message body because it's already an invalid request based on route not matching alone.

**Comment by santonocito** [comment]
I'd like to work on this

**Comment by delvedor** [comment]
@ThisIsMissEm yes, it looks like so!
I think the best approach would be to expose the `is404` in a nice way and let you handle the issue, or even build a plugin.
I would avoid adding yet another option to the framework itself as we should try to keep them at the minimum and suggest to use a plugin instead :)

**Comment by davidmarkclements** [comment]
are there any other status codes where you would have an overlapping use case? For instance.. what about a 400?

**Comment by ThisIsMissEm** [comment]
@davidmarkclements for me, it's really about just rejecting requests from all those automated bots that try to attack & pwn literally any HTTP server on the internet, so for our use case, 404 or route not found could be a very first step: it'd allow us to kill off bot requests very early on in their lifecycle.

I'd be happy with this being a plugin too, but I don't think a plugin should use internal APIs

**Comment by mcollina** [comment]
I think the name should be isNotFound because of parity with the serNotFoundHandler.

**Comment by Eomm** [comment]
> what about a 400?

At that stage, the body has been already parsed (assuming the schema validation in action)

I would act in a different way, using `reply.statusCode`, since the 404 is a response domain:

In a 404 case I have
```
fastify.addHook('onRequest', (req, reply, done) => {
  console.log('onRequest', reply.statusCode) // 200
  done()
})
fastify.addHook('onResponse', (req, reply, done) => {
  console.log('onResponse', reply.statusCode) // 404
  done()
})
```

The routing should be already executed at that stage and in the `onRequest` the status code could/should (?) be already set to 404

**Comment by delvedor** [comment]
@Eomm that could work, but I fear it is not robust enough. As soon as someone (you or an hook) changes the status code you no longer know that you were handling a 404.

I think we should provide a reliable way to tell the users that they are inside a 404 handling.
In this way also external plugins will be more robust, as we are guaranteeing if it is a 404 handling or not.

**Comment by zhangwinning** [comment]
Is there need a 404 plugin now, if need, I will work for it 😁

**Comment by mcollina** [comment]
No, we need a fresh PR that implements https://github.com/fastify/fastify/pull/2153.
