### ISSUE TITLE
PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by rtatarinov** [fastify/fastify#2232]
Hello. Thanks for your server. I have strange problem. I have certificate and I try connect it to my server. My server code:
```js
const path = require('path');

const fastify = require('fastify')({
  logger: true,
  http2: true,
  https: {
    cert: path.join(__dirname, 'somecert.crt'),
    key: path.join(__dirname, 'somekey.key'),
  },
});

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'build'),
});

fastify.get('/', function (req, reply) {
  reply.sendFile('index.html', path.join(__dirname, 'build'));
});

fastify.get('/env.js', function (req, reply) {
  reply
    .header('Content-Type', 'application/javascript; charset=utf-8')
    .send(`window.__CONFIG__ = ${JSON.stringify(require('./env'))};`);
});

fastify.setNotFoundHandler(function (request, reply) {
  reply.sendFile('index.html', path.join(__dirname, 'build'));
});

fastify.listen(443, '0.0.0.0', function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }

  fastify.log.info(`server listening on ${address}`);
});
```
I convinced all paths to cert and key correct. This files correct also. But I try to run my server I get next error:

```
_tls_common.js:135
      c.context.setCert(cert);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:135:17)
    at new Server (_tls_wrap.js:873:27)
    at new Http2SecureServer (internal/http2/core.js:2839:5)
    at Object.createSecureServer (internal/http2/core.js:2963:10)
    at createServer (/app/node_modules/fastify/lib/server.js:21:24)
    at build (/app/node_modules/fastify/fastify.js:129:30)
    at Object.<anonymous> (/app/server.js:7:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/lo
```
Actually, I confused :( because I don't know how I can resolve this issue. Help me please.

**Comment by rtatarinov** [comment]
So, I can resolve my problem. I think `path` doesn't work correctly. Than I used `fs` and it works now.
Code for server with http to https redirect:

```js
const redirect = require('fastify')({
  logger: true,
});

const path = require('path');
const fs = require('fs');

const fastify = require('fastify')({
  logger: true,
  http2: true,
  https: {
    cert: fs.readFileSync('someCert.crt', 'utf8'),
    key: fs.readFileSync('someKey.key', 'utf8'),
  },
});

fastify.register(require('fastify-static'), {
  root: path.join(__dirname, 'build'),
});

fastify.get('/', function (req, reply) {
  reply.sendFile('index.html', path.join(__dirname, 'build'));
});

fastify.get('/env.js', function (req, reply) {
  reply
    .header('Content-Type', 'application/javascript; charset=utf-8')
    .send(`window.__CONFIG__ = ${JSON.stringify(require('./env'))};`);
});

fastify.setNotFoundHandler(function (request, reply) {
  reply.sendFile('index.html', path.join(__dirname, 'build'));
});

redirect.all('/*', (req, res) => {
  res.redirect(`https://${req.hostname}${req.req.url}`);
});

redirect.listen(80, '0.0.0.0');

fastify.listen(443, '0.0.0.0', function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }

  fastify.log.info(`server listening on ${address}`);
});
```
I will close this issue.

**Comment by sbscan** [comment]
worked for me too

**Comment by Eomm** [comment]
Those options are standard node.js ones: https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions

They do not accept a string path, but a string/buffer content, so this would be even 1 micronanolittle second faster:

```
    cert: fs.readFileSync('someCert.crt'),
    key: fs.readFileSync('someKey.key'),

```
