### ISSUE TITLE
Problem encapsulation during close

### ISSUE THREAD

**Issue by allevo** [fastify/fastify#237]
Hi,
  I have encountered a bug in encapsulation during the [fastify-example-twitter](https://github.com/fastify/fastify-example-twitter) development. My code is like this:

```js
'use strict'

const fastify = require('fastify')()
const fp = require('fastify-plugin')
const fm = require('fastify-mongodb')

fastify.register(function(f, o, done) {
  f.register(fm, { url: 'mongodb://localhost/yyy' }, err => {
    if(err) return done(err)
      fastify.get('/', (req, reply) => reply.send({}))
      done()
  })
})

fastify.listen(3008, err => {
  console.log('fastify is up!', err)
  setTimeout(() => {
    console.log('closing...')
    fastify.close(err => {
      console.log('closed', err)
    })
  }, 1000)
})
```

`fastify-mongodb` plugin [registers an `onClose` hook](https://github.com/fastify/fastify-mongodb/blob/master/index.js#L25)
When `fastify` is going to shut down, the plugin refers to the decorators that has set for the cleaning up. But it seems that there the fastify instance is not the instance used in the start up!

In fact the script exits with a non-0 code and prints this error:
```
/Users/allevo/repos/fastify-example-twitter/server/node_modules/fastify-mongodb/index.js:32
  fastify.mongo.db.close(done)
               ^

TypeError: Cannot read property 'db' of undefined
    at close (/Users/allevo/repos/fastify-example-twitter/server/node_modules/fastify-mongodb/index.js:32:16)
    at Boot.closeWithCbOrNextTick (/Users/allevo/repos/fastify-example-twitter/server/node_modules/avvio/boot.js:239:7)
    at release (/Users/allevo/repos/fastify-example-twitter/server/node_modules/fastq/queue.js:127:16)
    at Object.resume (/Users/allevo/repos/fastify-example-twitter/server/node_modules/fastq/queue.js:61:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by delvedor** [comment]
Ouch, this is a bug.
The `onClose` is not encapsulated because we are [using avvio](https://github.com/fastify/fastify/blob/master/lib/hooks.js#L25) to handle the closing phase.

I'll think about this.

**Comment by delvedor** [comment]
`ready` is affected by the same problem.

**Comment by thedeveloperr** [comment]
I think I am Facing the same problem. 
Using console.log I have ensured that:
**Before closing event the fastify have the mongoose decorator defined.**
```
 TypeError: Cannot read property 'connection' of undefined
        at fastify.addHook (/home/backend/plugins/dbConnector.js:17:36)
        at Object._encapsulateTwoParam (/home/backend/node_modules/avvio/boot.js:385:7)
        at Boot.closeWithCbOrNextTick (/home/backend/node_modules/avvio/boot.js:365:7)
        at Task.release (/home/rentomojo/backend/node_modules/fastq/queue.js:127:16)
        at worked (/home/rentomojo/backend/node_modules/fastq/queue.js:169:10)
        at fastify.onClose (/home/backend/node_modules/fastify/fastify.js:288:9)
        at Object._encapsulateTwoParam (/home/backend/node_modules/avvio/boot.js:387:7)
        at Boot.closeWithCbOrNextTick (/home/backend/node_modules/avvio/boot.js:365:7)
        at release (/home/rentomojo/backend/node_modules/fastq/queue.js:127:16)
        at Object.resume (/home/rentomojo/backend/node_modules/fastq/queue.js:61:7)
        at _combinedTickCallback (internal/process/next_tick.js:132:7)
        at process._tickCallback (internal/process/next_tick.js:181:9)

```

My code:
```
  1 const mongoose = require('mongoose');                                                                                                                                                                     
  2 const fp = require('fastify-plugin');                                                                                                                            
  3                                                                                                                                         
  4 async function dbConnector(fastify) {                                                                                                                            
  5   const env = process.env.NODE_ENV || 'development';                                                                                                                            
  6   const autoIndex = env !== 'production' && env !== 'staging';                                                                                                                            
  7   let connectionString = '';                                                                                                                            
  8   if (env === 'testing') connectionString = fastify.mongodb_in_memory_conn_str;                                                                                                                            
  9   else connectionString = process.env.MONGO_CONNECTION_STRING;                                                                                                                            
 10   await mongoose.connect(                                                                                                                                                         
 11     connectionString,                                                                                                                                   
 12     { autoIndex, useUnifiedTopology: true, useNewUrlParser: true },                                                                                                                            
 13   );                                                                                                                            
 14   // will be available to the whole app as fastify.mongoose                                                                                                                            
 15   fastify.decorate('mongoose', mongoose);                                                                                                                                                                      
 16   fastify.addHook('onClose', async (fastifyInstance) => {
 17     await fastifyInstance.mongoose.connection.close();                                                                                                                                     
 18   });                                                                                                                                                                                
 19 }
 20 module.exports = fp(dbConnector);

```

**Comment by Eomm** [comment]
Did you tried `fastify` variable instead of `fastifyInstance`?

**Comment by thedeveloperr** [comment]
> Did you tried `fastify` variable instead of `fastifyInstance`?

I tried it but then my test timedout.
I removed the fasifyInstance variable from callback argument list completely and used fastify variable then, it worked !!
No idea how.

My current code.

```
  1 const mongoose = require('mongoose');                                         
  2 const fp = require('fastify-plugin');                                         
  3                                          
  4 async function dbConnector(fastify) {                                         
  5   const env = process.env.NODE_ENV || 'development';                                         
  6   const autoIndex = env !== 'production' && env !== 'staging';                                         
  7   let connectionString = '';                                         
  8   if (env === 'testing') connectionString = fastify.mongodb_in_memory_conn_str;                                         
  9   else connectionString = process.env.MONGO_CONNECTION_STRING;                                         
 10   await mongoose.connect(                                         
 11     connectionString,                                         
 12     { autoIndex, useUnifiedTopology: true, useNewUrlParser: true },                                         
 13   );                                         
 14   // will be available to the whole app as fastify.mongoose                                         
 15   fastify.decorate('mongoose', mongoose);                                         
 16   fastify.addHook('onClose', async () => {                                                        
 17     await fastify.mongoose.connection.close();                                                  
 18   });                                                                                          
 19 }                                         
 20 module.exports = fp(dbConnector);  
```
