### ISSUE TITLE
server.Inject() unexpected behaviour on deprecation warning

### ISSUE THREAD

**Issue by zekth** [fastify/fastify#2438]
## 🐛 Bug Report

The `FastifyDeprecation` message makes `server.inject` crashes while the runtime is properly working. In runtime shows this in std out:
```
(node:9180) [FSTDEP001] FastifyDeprecation [FSTDEP001]: You are accessing the Node.js core request object via "request.req", Use "request.raw" instead.
```

But when running the same sequence in `server.inject()` i end up having this:
```
"type":"FastifyError","message":"Reply was already sent."
```
```
  console.log
    TypeError [ERR_INVALID_ARG_TYPE]: The "warning" argument must be one of type Error or string. Received type object
        at process.emitWarning (internal/process/warning.js:147:13)
        at emitWarning (/project/node_modules/fastify/lib/warnings.js:63:11)
```
```
   : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
```

## To Reproduce

Just trigger the deprecation flag in a hook and run the `server.inject()` in a test.

## Your Environment

- *node version*: 10
- *fastify version*: 3.0.3
- *os*: Mac
- Test Engine: Jest 26.1.0

So is it expected or not?

**Comment by mcollina** [comment]
Can you paste a full example to reproduce? I thought we caught all of them? Otherwise, can you run the example with `--trace-warnings`?

**Comment by zekth** [comment]
> Can you paste a full example to reproduce? I thought we caught all of them? Otherwise, can you run the example with `--trace-warnings`?

Haven't recopied the code because it's embedded in a way bigger project but i can setup a example project for this purpose.

**Comment by zekth** [comment]
```js
// app.js
const fastify = require("fastify")({
  logger: true,
});

fastify.get("/", (request, reply) => {
  reply.send({ hello: "world" });
});

fastify.addHook("preHandler", (r) => {
  const u = r.req.url;
});

module.exports = {
  server: fastify,
};
```
```js
// app.spec.js
const { server } = require("./app");

describe("App", () => {
  beforeAll(async () => {
    await server.ready();
  });
  afterAll(async () => {
    await server.close();
  });

  test("bug", async () => {
    const r = await server.inject({ method: "GET", url: "/" });
    expect(r.statusCode).toBe(200);
  });
});
```
```js
// server.js
const { server } = require("./app");

server.listen(3000, (err, address) => {
  if (err) throw err;
  server.log.info(`server listening on ${address}`);
});
```
```json
// package.json
{
  "name": "testfastify",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "fastify": "3.0.3",
    "jest": "26.1.0"
  }
}
```

**Comment by mcollina** [comment]
You have a bug in your code:

```js
fastify.addHook("preHandler", async (r) => { // this should be async or use the callback
  const u = r.req.url;
});
```

**Comment by zekth** [comment]
Sorry example was wrong. Even corrected `preHandler` still go the error:

```
    TypeError [ERR_INVALID_ARG_TYPE]: The "warning" argument must be one of type Error or string. Received type object

       8 | 
       9 | fastify.addHook("preHandler", (r,reply,done) => {
    > 10 |   const u = r.req.url;
         |               ^
      11 |   done()
      12 | });
      13 | 

      at emitWarning (node_modules/fastify/lib/warnings.js:63:11)
      at _Request.req (node_modules/fastify/lib/request.js:90:7)
      at Object.fastify.addHook (app.js:10:15)
      at hookIterator (node_modules/fastify/lib/hooks.js:218:10)
      at next (node_modules/fastify/lib/hooks.js:159:20)
      at hookRunner (node_modules/fastify/lib/hooks.js:178:3)
      at preValidationCallback (node_modules/fastify/lib/handleRequest.js:95:5)
      at handler (node_modules/fastify/lib/handleRequest.js:69:5)
      at handleRequest (node_modules/fastify/lib/handleRequest.js:18:5)
```

**Comment by mcollina** [comment]
You must change your code:

```js
fastify.addHook("preHandler", async (r) => { // this should be async or use the callback
  const u = r.raw.url;
});
```

There is a bug in jest that causes the warning to throw :/

**Comment by zekth** [comment]
> You must change your code:
> 
> ```js
> fastify.addHook("preHandler", async (r) => { // this should be async or use the callback
>   const u = r.raw.url;
> });
> ```
> 
> There is a bug in jest that causes the warning to throw :/

Ok i wanted to know if it was expected or not. Unfornatunately i can't change the code as it's in a package, there is currently a PR for it: https://github.com/SerayaEryn/fastify-session/pull/109

Closing. Thanks!
