### ISSUE TITLE
stripe method call causes FastifyError - Promise may not be fulfilled with 'undefined' when statusCode is not 204

### ISSUE THREAD

**Issue by eadsjr** [fastify/fastify#2510]
## 🐛 Bug Report

When attempting to make a call on the stripe package API, a FastifyError is thrown, though the call appears to work.

## To Reproduce

```js
  params = {}
  params.payment_method_types = [`card`]
  params.mode = `payment`
  params.line_items = [ { price: `price_xyz` , quantity: 1 } ]
  params.success_url = config.fastify.hostpath + `/purchase/success?session_id={CHECKOUT_SESSION_ID}`
  params.cancel_url = config.fastify.hostpath + `/purchase/cancelled`
  let session = await stripe.checkout.sessions.create(params)
```

## Expected behavior

```txt
Expected to see no errors, and get a session object back from the create() call
```

## Actual behavior

```txt
Got the following error, and a session object back from the create() call

[1598047311897] ERROR (50323 on <PRIV>-MacBook-Pro.local): Promise may not be fulfilled with 'undefined' when statusCode is not 204
    reqId: 2
    err: {
      "type": "FastifyError",
      "message": "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
      "stack":
          FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204
              at /<PRIV>/node_modules/fastify/lib/wrapThenable.js:30:30
              at processTicksAndRejections (internal/process/task_queues.js:93:5)
      "name": "FastifyError",
      "code": "FST_ERR_PROMISE_NOT_FULLFILLED",
      "statusCode": 500
    }
```

## Your Environment

- *node version*: v14.8.0
- *fastify version*: 3.2.1
- *os*: Mac OS X 10.15.3
- *browser*: Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by eadsjr** [comment]
When creating a better example I found the issue did not persist, so I dug deeper.

It turns out this isn't related to Stripe at all... it's the result of allowing a route to terminate and sending a response asynchronously.

## To Reproduce

```js
const routes = async (fastify, options) => {
  fastify.post(`/purchase`, async (request, reply) => {
    createCheckoutSession( reply )
  })
}

const createCheckoutSession = async ( reply ) => {
  /* <<< checkout code here >>> */
  reply.send( session )
}
```

## Apparent Solution

```js
const routes = async (fastify, options) => {
  fastify.post(`/purchase`, async (request, reply) => {
    const session = await createCheckoutSession( reply )
    reply.send( session )
  })
}

const createCheckoutSession = async ( reply ) => {
  /* <<< checkout code here >>> */
  return session
}
```

Is this worthy of a more specific error message?

**Comment by jsumners** [comment]
`await reply.send`. This is all documented.

**Comment by fox1t** [comment]
I think the message is already specific enough:
Here you are returning `undefined`:
```
const routes = async (fastify, options) => {
  fastify.post(`/purchase`, async (request, reply) => {
    createCheckoutSession( reply )
  })
}
```
and it is used as the response payload.

**Comment by jsumners** [comment]
https://www.fastify.io/docs/v3.2.x/Routes/#async-await
