### ISSUE TITLE
throw new FST_ERR_MISSING_MIDDLEWARE()

### ISSUE THREAD

**Issue by chenchuraviteja** [fastify/fastify#2541]
Any one help me, how to use keycloak middleware in  fastify 3 version

```js
const keycloak = require("./src/config/keycloak");

fastify.use(keycloak.middleware());
```

## Expected behavior

I need to execute the keycloak middle-ware in execute time. i am trying code like(below) this also getting same error

```js
fastify.register(require('middie'));
fastify.use(keycloak.middleware());
```

## Your Environment
- *node version*:  12
- *fastify version*: >=3
- *os*: Linux

## getting error
/home/ibytecode/git-repos/sub-pjt/iam/iam-api/node_modules/fastify/fastify.js:404
    throw new FST_ERR_MISSING_MIDDLEWARE()
    ^
FastifyError [Error]: You must register a plugin for handling middlewares, visit fastify.io/docs/latest/Middleware/ for more info.
    at Object.use (/home/ibytecode/git-repos/sub-pjt/iam/iam-api/node_modules/fastify/fastify.js:404:11)
    at Object.<anonymous> (/home/ibytecode/git-repos/sub-pjt/iam/iam-api/index.js:51:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  name: 'FastifyError',
  code: 'FST_ERR_MISSING_MIDDLEWARE',
  message: 'You must register a plugin for handling middlewares, visit fastify.io/docs/latest/Middleware/ for more info.',
  statusCode: 500
}

**Comment by fox1t** [comment]
I think that the error message is pretty straightforward: "You must register a plugin for handling middlewares, visit [fastify.io/docs/latest/Middleware/](fastify.io/docs/latest/Middleware/) for more info"

As of version 3 you need to install a plugin in order to be able to use middlewares.
