### ISSUE TITLE
Fastify does seem to swallow error traces for async plugins init

### ISSUE THREAD

**Issue by mgcrea** [fastify/fastify#2694]
## 🐛 Bug Report

When an error is thrown inside an async plugin during the init step, somehow the error is swallowed and you loose the trace. Maybe I've got something mis-configured, might be related to #850.

## To Reproduce

```ts
import createFastify, { FastifyInstance, FastifyPluginAsync, FastifyServerOptions } from 'fastify';
import { NODE_HOST, NODE_PORT } from './config/env';

const someAsyncPlugin: FastifyPluginAsync = async (fastify): Promise<void> => {
  throw new Error('PluginError');
};

export const buildFastify = (options: FastifyServerOptions = {}): FastifyInstance => {
  const fastify = createFastify({ logger: { prettyPrint: true }, ...options });
  fastify.register(someAsyncPlugin);
  return fastify;
};

try {
  const server = buildFastify();
  server.listen(NODE_PORT, NODE_HOST, (err) => {
    if (err) {
      server.log.error(err.message, err.stack);
      process.exit(1);
    }
  });
} catch (err) {
  console.dir({ err });
}
```

You end up with only the error message with no trace without the try catch block being called.

```
[1605695268566] ERROR	 (49126 on mgcrea.localdomain): PluginError
```

And that's it, no trace and no crash.

## Expected behavior

Show the trace at least or better properly re-throw the error to properly exit the process (if uncaught)

## Your Environment

- *node version*: 14.15.0
- *fastify version*: 3.8.0
- *os*: Mac

**Comment by zekth** [comment]
in this case `server.ready()` should reject.

**Comment by mcollina** [comment]
Confirmed, this is a bug:

```js
import createFastify from './fastify.js';

const someAsyncPlugin = async (fastify) => {
  throw new Error('PluginError');
};

export const buildFastify = (options) => {
  const fastify = createFastify({ logger: { prettyPrint: false }, ...options });
  fastify.register(someAsyncPlugin);
  return fastify;
};

try {
  const server = buildFastify();
  server.listen(3000, '0.0.0.0', (err) => {
    if (err) {
      server.log.error(err.message, err.stack);
      process.exit(1);
    }
  });
} catch (err) {
  console.dir({ err });
}
```

It does not include a stacktrace:

```
{"level":50,"time":1605697694548,"pid":58681,"hostname":"MacBook-Pro.local","msg":"PluginError"}
```

**Comment by zekth** [comment]
Isn't due to pino 6 ? https://github.com/pinojs/pino/releases/tag/v6.0.0

` server.log.error(err)` outputs:
```json
{"level":50,"time":1605698906677,"pid":19620,"hostname":"DESKTOP-SSLSSQS","stack":"Error: PluginError\n    at someAsyncPlugin (F:\\github\\fastify\\s.js:4:9)\n    at Plugin.exec (F:\\github\\fastify\\node_modules\\avvio\\plugin.js:131:17)\n   
 at Boot.loadPlugin (F:\\github\\fastify\\node_modules\\avvio\\plugin.js:266:10)\n    at Task.release (F:\\github\\fastify\\node_modules\\fastq\\queue.js:140:16)\n    at worked (F:\\github\\fastify\\node_modules\\fastq\\queue.js:182:10)\n    at F:\\github\\fastify\\node_modules\\avvio\\plugin.js:269:7\n    at done (F:\\github\\fastify\\node_modules\\avvio\\plugin.js:201:5)\n    at check (F:\\github\\fastify\\node_modules\\avvio\\plugin.js:225:9)\n    at internal/process/task_queues.js:149:7\n    at AsyncResource.runInAsyncScope (async_hooks.js:189:9)","type":"Error","msg":"PluginError"}
```

**Comment by mcollina** [comment]
We are using pino v6: https://github.com/fastify/fastify/blob/2f46d9a4b957a9b1c30d380eb2df9e2fd374a4ce/package.json#L180.

I guess we are doing something odd somewhere and we just do:

```js
server.log.error(err.message))
```

**Comment by AyoubElk** [comment]
I'd like to work on this, any thoughts on where I should start looking?

**Comment by mgcrea** [comment]
Regarding the proper behaviour, I'd rather have a thrown Error thrown out that a logged but "silent" plugin failure. Not sure if everyone agrees.

**Comment by mcollina** [comment]
I'm sorry, this is not a problem in Fastify.

The problem is the following line:

```js
      server.log.error(err.message, err.stack);
```

Note that pino does handle multiple arguments only for format-like purposes (i.e. printf).

Instead do:


```js
      server.log.error({ err });
```

or

```js
      server.log.error(err.message  + err.stack);
```

**Comment by mgcrea** [comment]
@mcollina thanks ! indeed it does work correctly, sorry for the noise.
