### ISSUE TITLE
reply.view() throws inside async function

### ISSUE THREAD

**Issue by iCyberon** [fastify/fastify#271]
Basically you can't use reply.view ([point-of-view](https://github.com/fastify/point-of-view) plugin) inside async function.
```javascript
const fastify = require('fastify')();

fastify.register(require('point-of-view'), {
  engine: {
      handlebars: require('handlebars')
  },
  templates: './templates'
});

fastify.get('/view', async function (request, reply) {
    var vars = await new Promise(function (resolve) {
      setTimeout(resolve, 200, { text: 'hello there' })
    })

    reply.view('index.hbs',vars)
})

fastify.listen(3000);
```

throws error
```
_http_outgoing.js:489
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:489:11)
    at ServerResponse.setHeader (_http_outgoing.js:496:3)
    at Reply.header (/Volumes/Test/Fastify/node_modules/fastify/lib/reply.js:110:12)
    at _readCallback (/Volumes/Test/Fastify/node_modules/point-of-view/index.js:59:14)
    at tryToString (fs.js:514:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
```

**Comment by mcollina** [comment]
are you using 0.28?

**Comment by iCyberon** [comment]
Yes, just updated fastify to 0.28 5 minutes ago to verify.

**Comment by mcollina** [comment]
Should be good in 0.28.1.
