### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by shaikh-shahid** [fastify/fastify#2771]
i took this benchmark code to test out fastify for my new project.

```
'use strict'

const fastify = require('fastify')()

const schema = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          hello: {
            type: 'string'
          }
        }
      }
    }
  }
}

fastify.get('/', schema, function (req, reply) {
  reply.send({ hello: 'world' })
})

fastify.listen(3000)
```

and got this error upon running

```
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/shahidshaikh/projects/ismailvalid/node_modules/queue-microtask/index.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/shahidshaikh/projects/ismailvalid/node_modules/avvio/plugin.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)

```
My node version is v11.15.0

**Comment by jsumners** [comment]
Node v11 is unsupported both by us and Node core.

**Comment by Eomm** [comment]
The error doesn't seem triggered by fastify: that script actually works

**Comment by shaikh-shahid** [comment]
> Node v11 is unsupported both by us and Node core.

Ok, updating Node.

**Comment by shaikh-shahid** [comment]
Yup, was the version issue.
