### ISSUE TITLE
Schema with key or id "<$id>" already exists

### ISSUE THREAD

**Issue by boyander** [fastify/fastify#2901]
## 🐛 Bug Report

When using [`oneOf`](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof) fastify fails with `FST_ERR_SCH_VALIDATION_BUILD` when a request is injected.

## To Reproduce

```js
const app = fastify();
const first_schema = {
  $id: "example1",
  type: "object",
  properties: {
    name: {
      type: "string",
    },
  },
};

app.addSchema(first_schema);

const reused_schema = {
  $id: "example2",
  type: "object",
  properties: {
    name: {
      oneOf: [
        {
          $ref: "example1",
        },
      ],
    },
  },
};

app.get(
  "/a",
  {
    schema: {
      body: reused_schema,
      response: {
        200: reused_schema,
      },
    },
  },
  async () => "OK-A"
);
app.get(
  "/b",
  {
    schema: {
      body: reused_schema,
      response: {
        200: reused_schema,
      },
    },
  },
  async () => "OK-B"
);

await app.inject().get("/");
```

## Expected behavior

I'm expecting an error before request is handled. Maybe schema resolvers are not well referencing the used schemas? Not sure about the issue behind this.

## Your Environment

- *node version*: v15.11.0
- *fastify version*: >= 3.13.0
- *os*: Mac

**Comment by mcollina** [comment]
cc @eomm

**Comment by Eomm** [comment]
Looking at it 👍

**Comment by Eomm** [comment]
An issue on `fast-json-stringify` causes this one:

- the route `a` is processed, ajv acts first then fjs replace `$ref: example1`
- the route `b` is processed and ajv trigger a misleading error

Here what happen under the hood on ajv:

```
const Ajv = require('ajv')
const ajv = new Ajv()

const externalSchema = {
  $id: 'example1',
  type: 'object',
  properties: {
    name: { type: 'string' }
  }
}
ajv.addSchema(externalSchema)
const reusedSchema = {
  $id: 'example2',
  type: 'object',
  properties: {
    name: {
      oneOf: [{ $ref: 'example1' }]
    }
  }
}
ajv.compile(reusedSchema)

reusedSchema.properties.name.oneOf[0] = externalSchema // comment this line to avoid the error
ajv.compile(reusedSchema)
// Error: schema with key or id "example2" already exists
```

**Comment by boyander** [comment]
Cool, thanks for your quick answer. 👍🏻

**Comment by madx** [comment]
I think I encountered the same bug using the following code:

```javascript
import fastify from "fastify"
import fastifyPlugin from "fastify-plugin"
import S from "fluent-json-schema"

const ShowSchema = S.object().id("ShowSchema").prop("name", S.string())
const ListSchema = S.array().id("ListSchema").items(S.ref("ShowSchema#"))

const app = fastify({
  logger: true,
})

app.addSchema(ListSchema)
app.addSchema(ShowSchema)

const defaultRouteOptions = {
  schema: { response: { 200: S.ref("ListSchema#") } },
}

app.get("/prefix1/resource/", defaultRouteOptions, () => ({}))
app.get("/prefix2/resource/", defaultRouteOptions, () => ({}))

try {
  await app.listen(4000)
} catch (err) {
  app.log.error(err)
  process.exit(1)
}
```

It yields the following error:

```
[1615109152663] ERROR (361840 on winter): schema with key or id "ShowSchema" already exists
    Error: schema with key or id "ShowSchema" already exists
        at checkUnique (/home/madx/tmp/fastify-server-repro/node_modules/ajv/lib/ajv.js:481:11)
        at Ajv.addSchema (/home/madx/tmp/fastify-server-repro/node_modules/ajv/lib/ajv.js:136:3)
        at ValidatorCompiler (/home/madx/tmp/fastify-server-repro/node_modules/fastify/lib/schema-compilers.js:48:9)
        at Object.buildCompilerFromPool [as buildValidator] (/home/madx/tmp/fastify-server-repro/node_modules/fastify/lib/schema-compilers.js:20:22)
        at SchemaController.setupValidator (/home/madx/tmp/fastify-server-repro/node_modules/fastify/lib/schema-controller.js:88:52)
        at Boot.<anonymous> (/home/madx/tmp/fastify-server-repro/node_modules/fastify/lib/route.js:297:30)
        at Object.onceWrapper (node:events:484:28)
        at Boot.emit (node:events:390:22)
        at /home/madx/tmp/fastify-server-repro/node_modules/avvio/boot.js:153:12
        at /home/madx/tmp/fastify-server-repro/node_modules/avvio/plugin.js:269:7
```

While trying to trace it down I noticed that indeed the `$ref`-ed schemas were expanded instead of kept in place. I tried downgrading fastify as my code was working before and I narrowed it down to 3.12.0, which is a release that had a lot of changes regarding schema handling as it is the one introducing the schema controller layer (#2755).

**Comment by Eomm** [comment]
> I tried downgrading fastify as my code was working before and I narrowed it down to 3.12.0, which is a release that had a lot of changes regarding schema handling as it is the one introducing the schema controller layer (#2755).

Tried on fastify 3.11.0 and 3.10.0 and the issue is there: https://runkit.com/embed/k9oir9mrss7m

Please, providing an [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) would help much more than an assumption that demotivates me to help.

**Comment by madx** [comment]
Sorry if my investigation was misleading. My app was running fine in 3.9.2 and stopped working after upgrading to 3.13 so I tried every previous version and 3.12.0 was the one that started raising the issue so it seems I incorrectly figured it was the faulty version.

```
lvdc/server master*:3b905f0  130
↳ npm install fastify@3.11.0

added 2 packages, removed 2 packages, changed 2 packages, and audited 477 packages in 1s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
lvdc/server master*:3b905f0
↳ npm start

> server@0.1.0 start
> ./scripts/dev

Already up to date
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node -r dotenv/config server.js`
[1615113154813] INFO (369904 on winter): Server listening at http://127.0.0.1:4000
^C
lvdc/server master*:3b905f0  130
↳ npm install fastify@3.12.0

added 2 packages, removed 2 packages, changed 2 packages, and audited 477 packages in 2s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
lvdc/server master*:3b905f0
↳ npm start

> server@0.1.0 start
> ./scripts/dev

Already up to date
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node -r dotenv/config server.js`
[1615113173241] ERROR (370157 on winter): schema with key or id "CircleEventShow" already exists
    Error: schema with key or id "CircleEventShow" already exists
        at checkUnique (/home/madx/repos/lvdc/lvdc/server/node_modules/ajv/lib/ajv.js:481:11)
        at Ajv.addSchema (/home/madx/repos/lvdc/lvdc/server/node_modules/ajv/lib/ajv.js:136:3)
        at ValidatorCompiler (/home/madx/repos/lvdc/lvdc/server/node_modules/fastify/lib/schema-compilers.js:48:9)
        at Object.buildCompilerFromPool [as buildValidator] (/home/madx/repos/lvdc/lvdc/server/node_modules/fastify/lib/schema-compilers.js:20:22)
        at SchemaController.setupValidator (/home/madx/repos/lvdc/lvdc/server/node_modules/fastify/lib/schema-controller.js:88:52)
        at Boot.<anonymous> (/home/madx/repos/lvdc/lvdc/server/node_modules/fastify/lib/route.js:297:30)
        at Object.onceWrapper (node:events:484:28)
        at Boot.emit (node:events:390:22)
        at /home/madx/repos/lvdc/lvdc/server/node_modules/avvio/boot.js:153:12
        at /home/madx/repos/lvdc/lvdc/server/node_modules/avvio/plugin.js:269:7
```

**Comment by madx** [comment]
@Eomm I found a way for this code to work in 3.11.0, and it's actually closer to my actual code:

```javascript
import fastify from "fastify"
import fastifyPlugin from "fastify-plugin"
import S from "fluent-json-schema"

const ShowSchema = S.object().id("ShowSchema").prop("name", S.string())
const ListSchema = S.array().id("ListSchema").items(S.ref("ShowSchema#"))

const app = fastify({
  logger: true,
})

app.addSchema(ListSchema)
app.addSchema(ShowSchema)

const defaultRouteOptions = {
  schema: { response: { 200: S.ref("ListSchema#") } },
}

app.register(
  async (app) => {
    app.get("/resource/", defaultRouteOptions, () => ({}))
  },
  { prefix: "/prefix1" }
)
app.register(
  async (app) => {
    app.get("/resource/", defaultRouteOptions, () => ({}))
  },
  { prefix: "/prefix2" }
)

try {
  await app.listen(4000)
} catch (err) {
  app.log.error(err)
  process.exit(1)
}
```

**Comment by Eomm** [comment]
This is useful, thanks!
I will test your use case in the upcoming PR 👍

**Comment by boyander** [comment]
Thanks @Eomm for working on this :)

**Comment by tcharlat** [comment]
Hi @Eomm ,
I have an issue with the serializer.
It may be trying to add schemas already added beforehand eg:

`
UnhandledPromiseRejectionWarning: Error: schema with 
key or id "Date" already exists
    at checkUnique
`
I can track down the issue in the lib by deactivating the serializer 

```./lib/schema-compiler.js

function serializerFactory (externalSchemas, serializerOpts) {
  const opts = Object.assign({}, serializerOpts, { schema: externalSchemas })
  return function responseSchemaCompiler ({ schema /* method, url, httpStatus */ }) {
    // return fastJsonStringify(schema, opts)
  }
}
```

I had to disable it in my application

```ts
fastifyInstance.setSerializerCompiler(
  (/* { schema, method, url, httpStatus } */) => JSON.stringify
);
```

The issued started to appear when I use a $ref in my response object and that this $ref points to an object with its own $ref to a third schema.

I tried to reproduce the issue but a simple foo.bar.baz nesting of refs is not enough to reproduce the bug so I'm at a lost (and running out of time to deliver)

**Comment by Eomm** [comment]
@tcharlat you have hit this issue https://github.com/fastify/fast-json-stringify/issues/242

**Comment by jaschaio** [comment]
I actually solved this by changing the order of the schema definitions, see https://github.com/fastify/fastify/issues/1043

**Comment by softyak** [comment]
I have already faced this issue as well. I actually resolved this issue with upgrading the ajv version to 8.12.0. As @Eomm said that there is a troubleshooting in https://github.com/fastify/fast-json-stringify/issues/242 with the old versions of ajv.
