### ISSUE TITLE
ECONNRESET on close inside a container

### ISSUE THREAD

**Issue by artur-ma** [fastify/fastify#3045]
Hey, not sure this issue is related to fastify itself, but I will try my luck

I'm investigating socket hang up errors in our k8s cluster, 
We are using fastify-reply-from a proxy and fastify on another side

We are subscribed to SIGINT/SIGTERM with a call for `await fastify.close()` on that signals, but we still see a lot of ECONNRESET errors

So I ran some stupid test on my local machine (Mac)
1. Created fastify server (target.js)

```
'use strict'

const util =  require('util');
const sleep = util.promisify(setTimeout);

const Fastify = require('fastify');

const target = Fastify({
  logger: true
})

const handleSignal = (signal) => {

  console.log('closing')
  target.close(() => {
   console.log('closed');
   process.exit();
  });
};

process.on('SIGTERM', handleSignal);

target.all('*', async (request, reply) => {
  await sleep(1000)
  reply.send('hello world')
})

target.listen(3010, '0.0.0.0', (err) => {
  if (err) {
    throw err
  }
})
```

2. proxy service using fastify-reply-from (app.js)
```
'use strict'

const Fastify = require('fastify')
const http = require('http');
const proxy = Fastify({
  logger: false
})

const agent = new http.Agent({
    keepAlive: true,
    maxSockets: 1,
    keepAliveMsecs:  5 * 60 * 1000,
    scheduling: 'lifo',  
});

let timeout;

const subscribeToEnd = () => {
   if (!Object.values(agent.sockets).length) return;

   const socket = Object.values(agent.sockets)[0][0]

   socket.on('end', () => console.log('got FIN'))

   if (timeout) clearInterval(timeout)
}

timeout = setInterval(subscribeToEnd, 1000);

proxy.register(require('fastify-reply-from'), {
  base: 'http://localhost:3010/',
  http: {
    agents: {
      'http:': agent
    }
  }
})



proxy.all('*', (request, reply) => {
  return reply.from(request.raw.url, {
    onError: function (reply, { error }) {
      if (error.code === 'ECONNRESET') console.error(error);
      reply.send(error)
    }
  })
});

proxy.listen(3000, (err) => {
  if (err) {
    throw err
  }
})
```

Dockerfile

```
FROM node:16

COPY package.json package.json  
COPY package-lock.json package-lock.json
RUN npm install

COPY target.js target.js

CMD ["node", "target.js"]
```

I ran two scenarios 

**first scenario:**
```
node app.js
```
then
```
node target.js
```
then
```
autocannon http://localhost:3000/alive -d 30
```
then

```
kill <PID>
```

result:

```
>node app.js 
got FIN
```

**Second scenario**

```
node app.js
```
then

```
docker build . -t test
docker run --rm -p 3010:3010 test
```
then
```
autocannon http://localhost:3000/alive -d 30
```
then

```
docker stop -t 30 <CONTAINER ID>
```

results:

```
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  expose: false,
  statusCode: 500,
  status: 500
}
```

no FIN , a lot of ECONNRESET

ps. I tried to run container with --init to solve Node's issue with PID 1, but the same results

**Comment by RafaelGSS** [comment]
Hey! I've tried you reproduction code, but something is wrong in the process:

- The docker container to `target.js` can't redirect `localhost:3010` since is a different network. It would be better with a `docker-compose` to reproduce.
- At least for me, I don't get the same behavior as you. It has worked as expected.
- In your example:
>
 ```
>node app.js 
got FIN
```

the `app.js` mustn't provide a `got FIN`, should be `target.js`, right?

Anyway, I recommend that you put these files in a reproducible repository to allow us to reproduce it.

**Comment by artur-ma** [comment]
@RafaelGSS Thanks for testing, actually it should work since u forward localhost port 3010 to container port 3010 by using 
`-p 3010:3010`

Can I ask u please on which OS u are testing it, please?

**Comment by mcollina** [comment]
Given that the difference is _just_ in containers, I'm feeling this might be a Node core bug instead, or something else related to networking.

Did you see if the target server finish properly or is it abruptly closed? As you can see we do not destroy the socket: https://github.com/fastify/fastify/blob/2356c1672c3a042744d8951adfcf8ff20937302b/lib/route.js#L340.

Have you tried:

1. use undici instead of the node core http agent in fastify-reply-from configuration - it was built for this use case and it might solve the problem.
2. setting the server keepAliveTimeout (https://www.fastify.io/docs/latest/Server/#keepalivetimeout) to a value _greater_ than your client setting.
3. reproducing with only Node.js.

**Comment by mcollina** [comment]
cc @ronag - he might have seen thisas well!

**Comment by ronag** [comment]
I'm not that familiar with fastify. But. There is a keep alive race in node core that can cause spurious ECONNRESET errors if you are unlucky with timing. I would recommend you try undici which does not suffer from this and see if you still encounter the problem.

I agree with @mcollina's suggestions. You can also try to disable keepAlive on the node core client and see if that makes any difference.

**Comment by artur-ma** [comment]
@mcollina I really want to see if someone else has this issue, and its not related if it some mac specific issue
so maybe on our k8s cluster is something else 

I see "Service unavailable" I also tried server timeout to 0 
the interesting part is I do see FIN packets on tcpdump
![image](https://user-images.githubusercontent.com/57314588/116518748-54435300-a8d9-11eb-9bac-d67986eee7d6.png)

**Comment by mcollina** [comment]
I really recommend using undici and see if it helps.

**Comment by artur-ma** [comment]
Too the settings from undici example
```
  undici: {
    connections: 128,
    pipelining: 1,
    keepAliveTimeout: 60 * 1000,
    tls: {
      rejectUnauthorized: false
    }
  }
 ```
 
 looks good, no errors 
 
  the only problem is that we use Newrelic but they do not have undici  instrumentation, so we will be blind on production :\

**Comment by mcollina** [comment]
I would recommend to open an issue on New Relic, and potentially look into how to manually instrument Undici. I think it might just be needed to pass down the headers to the next service.

**Comment by artur-ma** [comment]
Thanks, closing!

Yeah, did it two weeks ago https://github.com/newrelic/node-newrelic/issues/730
I will check about custom but AFAIK HTTP is something internal that can not be instrumented (web frameworks and datastores can have custom instrumentation)
