### ISSUE TITLE
declaring route with empty url crashes node

### ISSUE THREAD

**Issue by m-ronchi** [fastify/fastify#3047]
## 🐛 Bug Report

if you declare a route with an empty url, fastify raises uncatchable exception that:
- crashes node if you run it directly
- causes a timeout if you run it with mocha

## To Reproduce

```js
import fastify from "fastify";

try {
  fastify().route({
    method: "GET",
    url: "",
    async handler() { return {}; }
  }).ready().then(null, e => console.log(e, "catched async"));

} catch (e) {
  console.log(e, "catched sync");
}

```

output:
```
% ts-node src

{PWD}/node_modules/avvio/boot.js:545
      func(err, cb)
      ^
TypeError: Cannot read property '0' of undefined
    at {PWD}/node_modules/fastify/lib/route.js:175:22
    at Object._encapsulateThreeParam ({PWD}/node_modules/avvio/boot.js:545:7)
    at Boot.timeoutCall ({PWD}/node_modules/avvio/boot.js:447:5)
    at Boot.callWithCbOrNextTick ({PWD}/node_modules/avvio/boot.js:428:19)
    at Boot._after ({PWD}/node_modules/avvio/boot.js:273:26)
    at Plugin.exec ({PWD}/node_modules/avvio/plugin.js:131:17)
    at Boot.loadPlugin ({PWD}/node_modules/avvio/plugin.js:266:10)
    at Task.release ({PWD}/node_modules/fastq/queue.js:147:16)
    at worked ({PWD}/node_modules/fastq/queue.js:199:10)
    at {PWD}/node_modules/avvio/plugin.js:269:7
% echo $?
1
```
## Expected behavior

error results in rejected promise

## Your Environment

- *node version*: 12
- *fastify version*: 3.15.0
- *os*: Mac

**Comment by RafaelGSS** [comment]
Good catch. It does not happen when calling the shorthand method, right? Example:

```js
  fastify().get(
    '',
    async function handler() { return {}; }
  ).ready()
```

**Comment by amitgilad3** [comment]
on it 👍

**Comment by amitgilad3** [comment]
@RafaelGSS  - it does not happen when calling the shorthand method,

**Comment by zekth** [comment]
Fixed in https://github.com/fastify/fastify/commit/eff4e38c76fda54c8f50c86dcb9312b4c4db9bc1
