### ISSUE TITLE
Parse Error: Expected HTTP/ when HTTP2 is enabled

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify#3131]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Node.js version

16.3.0 and 14.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

I can't make a http2 request with [Got](https://github.com/sindresorhus/got) or [fetch-h2](https://github.com/grantila/fetch-h2). In both cases, I get the same error message.

Making a call with https://github.com/mcollina/h2url works!

```
http://localhost:44539
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RequestError: Parse Error: Expected HTTP/
    at ClientRequest.<anonymous> (/home/starptech/repositories/starptech/apollo-datasource-rest/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/home/starptech/repositories/starptech/apollo-datasource-rest/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketOnData (node:_http_client:494:9)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at Socket.socketOnData (node:_http_client:487:22)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'HPE_INVALID_CONSTANT',
  timings: {
    start: 1623520887009,
    socket: 1623520887010,
    lookup: 1623520887011,
    connect: 1623520887012,
    secureConnect: undefined,
    upload: 1623520887012,
    response: undefined,
    end: undefined,
    error: 1623520887013,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 1,
      tcp: 1,
      tls: undefined,
      request: 0,
      firstByte: undefined,
      download: undefined,
      total: 4
    }
  }
}
```

### Steps to Reproduce

Followed the instruction [here](https://github.com/fastify/fastify/blob/main/docs/HTTP2.md#plain-or-insecure) to create an insecure http2 server.
```js
'use strict'
const got = require('got')
const fastify = require('fastify')({
  http2: true,
})

fastify.get('/', function (request, reply) {
  reply.code(200).send({ hello: 'world' })
})

fastify.listen(async () => {
  const url = `http://localhost:${fastify.server.address().port}`
  console.log(url)
  const { headers } = await got(url, { http2: true })
  console.log(headers)
})
```

**Comment by StarpTech** [comment]
This seems not related to fastify. I can reproduce it with:

```js
'use strict'
const got = require('got')
const { createServer } = require('http2')

const server = createServer((req, res) => {
  console.log("Request");
  process.nextTick(() => {
    res.end('{}')
  })
})

server.listen(async () => {
  const url = `http://localhost:${server.address().port}`
  const { headers } = await got(url, { http2: true })
  console.log(headers)
})
```

**Comment by szmarczak** [comment]
You're running an insecure HTTP/2 server. Got doesn't support insecure HTTP/2 servers.
