### ISSUE TITLE
Re-definitions of routes are not being validated when using `fastify.ready` method

### ISSUE THREAD

**Issue by juanarbol** [fastify/fastify#3411]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Node.js version

14.18.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

21.04

### Description

You expect to throw an exception when you declare the same route twice or more. eg:

`Method 'VERB' already declared for route '/route' with constraints '{}'`

This thing does not happen when you use the `fastify.ready()` method.

I'm open to sending a PR fixing this, I just need a few instructions or just a bit of time.

### Steps to Reproduce

This fails, as expected:

```js
const Fastify = require('fastify')

const fastify = Fastify()

fastify.get('/ping', (req, reply) => reply.send('Heloo'))
fastify.get('/ping', (req, reply) => reply.send('Helo 2'))

fastify.listen(3000)
```

This does not throws:

```js
const Fastify = require('fastify')

const fastify = Fastify()

fastify.get('/ping', (req, reply) => reply.send('Heloo'))
fastify.get('/ping', (req, reply) => reply.send('Helo 2'))

fastify.ready(() => console.log(fastify.printRoutes()))

fastify.listen(3000)
```

### Expected Behavior

This piece of code should throws the error bellow:

```js
const Fastify = require('fastify')

const fastify = Fastify()

fastify.get('/ping', (req, reply) => reply.send('Heloo'))
fastify.get('/ping', (req, reply) => reply.send('Helo 2'))

fastify.ready(() => console.log(fastify.printRoutes()))

fastify.listen(3000)
```
```bash
(node:45543) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Method 'GET' already declared for route '/ping' with constraints '{}'                                              
    at Router._insert (/tmp/fastify-repro/node_modules/find-my-way/index.js:285:7)                                                                                                                  
    at Router._on (/tmp/fastify-repro/node_modules/find-my-way/index.js:213:8)                                                                                                                      
    at Router.on (/tmp/fastify-repro/node_modules/find-my-way/index.js:82:8)                                                                                                                        
    at Object.afterRouteAdded (/tmp/fastify-repro/node_modules/fastify/lib/route.js:254:16)                                                                                                         
    at /tmp/fastify-repro/node_modules/fastify/lib/route.js:181:25
    at Object._encapsulateThreeParam (/tmp/fastify-repro/node_modules/avvio/boot.js:551:7)
    at Boot.timeoutCall (/tmp/fastify-repro/node_modules/avvio/boot.js:447:5)
    at Boot.callWithCbOrNextTick (/tmp/fastify-repro/node_modules/avvio/boot.js:428:19)
    at Boot._after (/tmp/fastify-repro/node_modules/avvio/boot.js:273:26)
    at Plugin.exec (/tmp/fastify-repro/node_modules/avvio/plugin.js:132:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(nsolid:45543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(nsolid:45543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MetCoder95** [comment]
Hi! I think this is solved in the `next` branch, I think I touched on while moving the route definition from sync to async, can you give it a try on the `next` branch? 🤔

**Comment by mcollina** [comment]
The ready callback has an error as first argument: that’s your error.

**Comment by juanarbol** [comment]
Yeap :( sorry :facepalm: 

Anyway, it's fixed in the next branch:

```bash
            throw new FST_ERR_DUPLICATED_ROUTE(opts.method, opts.url)
            ^
FastifyError [Error]: Method 'GET' already declared for route '/ping'
    at Object.addNewRoute (/home/juanarbol/GitHub/fastify/lib/route.js:236:19)
    at Object.route (/home/juanarbol/GitHub/fastify/lib/route.js:176:19)
    at Object.prepareRoute (/home/juanarbol/GitHub/fastify/lib/route.js:123:18)
    at Object._get [as get] (/home/juanarbol/GitHub/fastify/fastify.js:222:34)
    at Object.<anonymous> (/tmp/fastify-repro/index.js:6:9)
    at Module._compile (internal/modules/cjs/loader.js:1099:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1128:10)
    at Module.load (internal/modules/cjs/loader.js:964:32)
    at Function.Module._load (internal/modules/cjs/loader.js:804:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'FST_ERR_DUPLICATED_ROUTE',
  statusCode: 500
}
            throw new FST_ERR_DUPLICATED_ROUTE(opts.method, opts.url)
            ^
FastifyError [Error]: Method 'GET' already declared for route '/ping'
    at Object.addNewRoute (/home/juanarbol/GitHub/fastify/lib/route.js:236:19)
    at Object.route (/home/juanarbol/GitHub/fastify/lib/route.js:176:19)
    at Object.prepareRoute (/home/juanarbol/GitHub/fastify/lib/route.js:123:18)
    at Object._get [as get] (/home/juanarbol/GitHub/fastify/fastify.js:222:34)
    at Object.<anonymous> (/tmp/fastify-repro/index.js:6:9)
    at Module._compile (internal/modules/cjs/loader.js:1099:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1128:10)
    at Module.load (internal/modules/cjs/loader.js:964:32)
    at Function.Module._load (internal/modules/cjs/loader.js:804:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'FST_ERR_DUPLICATED_ROUTE',
  statusCode: 500
}
```

Closing, this is a misuse of the API and it's fixed in `next` branch
