### ISSUE TITLE
The server crashes if the socket is undefined and try to access attributes 

### ISSUE THREAD

**Issue by codeflyer** [fastify/fastify#3419]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Node.js version

14.15.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Docker image node:14

### Description

The app restart randomly with this error:

```
Cannot read property 'remoteAddress' of null
stack
TypeError: Cannot read property 'remoteAddress' of null
    at _Request.get (/home/app/node_modules/fastify/lib/request.js:161:26)
    at Object.asReqValue [as req] (/home/app/node_modules/fastify/lib/logger.js:55:26)
    at Pino.asJson (/home/app/node_modules/pino/lib/tools.js:118:50)
    at Pino.write (/home/app/node_modules/pino/lib/proto.js:202:28)
    at Pino.LOG [as error] (/home/app/node_modules/pino/lib/tools.js:55:21)
    at defaultErrorHandler (/home/app/node_modules/fastify/fastify.js:81:15)
    at handleError (/home/app/node_modules/fastify/lib/reply.js:553:20)
    at onErrorHook (/home/app/node_modules/fastify/lib/reply.js:524:5)
    at _Reply.Reply.send (/home/app/node_modules/fastify/lib/reply.js:128:5)
    at onErrorDefault (/home/app/node_modules/fastify-reply-from/index.js:209:9)
```

Checking the code it seems that the `socket` attribute of the request is `undefined` and fails when try to log the error in this accessor:

```
  ip: {
    get () {
        return this.socket.remoteAddress
     }
  },
```

### Steps to Reproduce

I couldn't find a way to reproduce the issue. It happens only inside a docker pod in a Kubernetes infrastructure.

**Comment by zekth** [comment]
Interesting, i wonder why the `socket` is undefined in this context. I'm running into K8s too and never experienced this.
