### ISSUE TITLE
Recursive schema definition causes infinite recursion

### ISSUE THREAD

**Issue by m-ronchi** [fastify/fastify#3643]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.0

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

if I try to use a schema with a recursive definition as a response schema, this error is thrown:
```
FastifyError: Failed building the serialization schema for GET: /, due to error Maximum call stack size exceeded
    at Boot.<anonymous> (node_modules/fastify/lib/route.js:320:19)
    at Boot.EventEmitter.emit (domain.js:483:12)
    at /Users/***/Workspace/Platform/experiments-api/node_modules/avvio/boot.js:153:12
    at /Users/***/Workspace/Platform/experiments-api/node_modules/avvio/plugin.js:270:7
    at done (node_modules/avvio/plugin.js:202:5)
    at check (node_modules/avvio/plugin.js:226:9)
    at internal/process/task_queues.js:153:7
    at AsyncResource.runInAsyncScope (async_hooks.js:189:9)
```

### Steps to Reproduce

```
const recType = {
    "$id": "recursive",
    "$ref": "recursive#/$defs/self",
    "$defs": {
      "self": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "left": {
                "type": "string"
              },
              "right": {
                "type": "string"
              },
              "operator": {
                "type": "string"
              }
            },
            "required": [
              "left",
              "right",
              "operator"
            ]
          },
          {
            "type": "object",
            "properties": {
              "and": {
                "type": "array",
                "items": {
                  "$ref": "recursive#/$defs/self"
                }
              }
            },
            "required": [
              "and"
            ]
          },
          {
            "type": "object",
            "properties": {
              "or": {
                "type": "array",
                "items": {
                  "$ref": "recursive#/$defs/self"
                }
              }
            },
            "required": [
              "or"
            ]
          },
          {
            "type": "object",
            "properties": {
              "not": {
                "$ref": "recursive#/$defs/self"
              }
            },
            "required": [
              "not"
            ]
          }
        ]
      }
    }
  };
  await fastify().addSchema(recType).route({
    method: "GET", url: "/", handler() { void 0; },
    schema: { response: { 200: recType } }
  }).ready();
```

### Expected Behavior

fastify starts and can handle the schema

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
