### ISSUE TITLE
streaming response + client closed connection is treated as an error

### ISSUE THREAD

**Issue by baadc0de** [fastify/fastify#371]
Server side code:
```
res.code(200).send(stream)
```

Client side is the `ffprobe` program from FFMpeg

```
$ ffprobe http://server:port/path/to/file
```

It seems to crash fastify because `ffprobe` closes connection once it knows enough about the file.

Fastify versions:
```
    "fastify": "^0.30.2",
    "fastify-auth": "^0.1.0",
    "fastify-helmet": "^1.0.1",
    "fastify-jwt": "^0.1.0",
    "fastify-multipart": "^0.2.0",
```

Console output:
```
06:44:49 🚨  client error
06:44:49 🚨  premature close
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:489:11)
    at ServerResponse.setHeader (_http_outgoing.js:496:3)
    at Immediate.wrapReplyEnd (node_modules/fastify/lib/reply.js:145:15)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mcollina** [comment]
Can you please upload an example to demonstrate your problem? (ideally without ffmpeg).

**Comment by gillesdemey** [comment]
Currently having the same issue, I've figured out a repro:

```javascript
const fastify = require('fastify')
const fs = require('fs')
const server = fastify()

server.get('/', (req, res) => {
  return res.send(fs.createReadStream('/dev/random'))
})

server.listen(3000)
``` 

Curl the stream
``` bash
$ curl -o /dev/null http://localhost:3000/
```
Hitting `Ctrl+C` to cancel the client request will crash the server:

```
_http_outgoing.js:489
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
``` 

I'll dig around in the code to see if I can take a stab at this myself :)

**Comment by jsumners** [comment]
I vaguely remember a mention around the time of the release of the current LTS a note about client hang-ups being handled in core differently. But I can't find the release note I'm thinking of to research it. My suspicion is that this is something in core, not Fastify (or emission from core that Fastify needs to handle).
