### ISSUE TITLE
Startup error using fastify and Apollo server upgrading to 3.27.2 from 3.20.2

### ISSUE THREAD

**Issue by rhscjohn-dev** [fastify/fastify#3729]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.21.0

### Stopped working in version

3.22.0

### Node.js version

16x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### 💥 Regression Report

I tried upgrading from fastify 3.20.2 to 3.27.2 and got the following error when starting my server.

```
D:\Users\johni\Projects\fastify_graphql\node_modules\fastify\lib\decorate.js:40
    throw new FST_ERR_DEC_ALREADY_PRESENT(name)
          ^
FastifyError [Error]: The decorator 'corsPreflightEnabled' has already been added!
    at decorateConstructor (D:\Users\johni\Projects\fastify_graphql\node_modules\fastify\lib\decorate.js:40:11)
    at Object.decorateRequest (D:\Users\johni\Projects\fastify_graphql\node_modules\fastify\lib\decorate.js:118:3)
    at fastifyCors (D:\Users\johni\Projects\fastify_graphql\node_modules\fastify-cors\index.js:20:11)
    at Plugin.exec (D:\Users\johni\Projects\fastify_graphql\node_modules\avvio\plugin.js:132:19)
    at Boot.loadPlugin (D:\Users\johni\Projects\fastify_graphql\node_modules\avvio\plugin.js:267:10)
    at Task.release (D:\Users\johni\Projects\fastify_graphql\node_modules\fastq\queue.js:149:1  code: 'FST_ERR_DEC_ALREADY_PRESENT',
  statusCode: 500
}
```

I then  went back to version 3.20.2 and every thing worked fine.
Installed fastify version 3.21.0 and everything worked fine.
Installed fastify version 3.22.0 and the above error appeared.

Possible conflict with apollo-server-fastify which default to CORS: true trying to add fastify-cors.

package.json
```
{
  "name": "fastify_graphql",
  "version": "1.0.0",
  "description": "server for nextPVR with Graphql",
  "main": "server.js",
  "scripts": {
    "start": "set NODE_ENV=production&& node src/server.js",
    "dev": "set NODE_ENV=development&& nodemon --delay 1 src/server.js",
    "copydb": "run-p -n copydb:*",
    "copydb:npvr": "pwsh -NoProfile -ExecutionPolicy Unrestricted -Command Copy-Item 'D:\\Users\\Public\\NPVR-data\\npvr.db3' -Destination 'NPVR' -Force",
    "copydb:config": "pwsh -NoProfile -ExecutionPolicy Unrestricted -Command Copy-Item 'D:\\Users\\Public\\NPVR-data\\config.xml' -Destination 'NPVR' -Force",
    "copydb:channels": "pwsh -NoProfile -ExecutionPolicy Unrestricted -Command Copy-Item -Path 'D:\\Users\\Public\\NPVR-data\\media\\channels' -Destination 'NPVR\\media\\' -Recurse -Container -Force ",
    "copydb:shows": "pwsh -NoProfile -ExecutionPolicy Unrestricted -Command Copy-Item -Path 'D:\\Users\\Public\\NPVR-data\\media\\shows' -Destination 'NPVR\\media\\' -Recurse -Container -Force",
    "test": "tap"
  },
  "author": "rhscjohn",
  "license": "ISC",
  "dependencies": {
    "@graphql-tools/load-files": "^6.4.0",
    "@graphql-tools/merge": "^8.1.1",
    "@graphql-tools/schema": "^8.2.0",
    "apollo-server-core": "^3.3.0",
    "apollo-server-fastify": "^3.3.0",
    "date-fns": "^2.23.0",
    "dotenv": "^10.0.0",
    "fastify": "^3.22.0",
    "fastify-autoload": "^3.8.0",
    "fastify-compress": "^3.6.0",
    "fastify-cors": "^6.0.2",
    "fastify-favicon": "^3.1.0",
    "fastify-static": "^4.2.3",
    "fs-extra": "^10.0.0",
    "got": "^11.8.2",
    "graphql": "^15.5.3",
    "ip": "^1.1.5",
    "js-camelcase": "^1.1.1",
    "js-snakecase": "^1.2.0",
    "knex": "^0.95.10",
    "node-cache": "^5.1.2",
    "sqlite3": "^5.0.2",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.5",
    "xml2js": "^0.4.23",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "nodemon": "^2.0.12",
    "npm-run-all": "^4.1.5"
  }
}
```

### Steps to Reproduce

`npm upgrade`
`npm run dev`

Complete console output.
```
> Executing task: npm run dev <


> fastify_graphql@1.0.0 dev
> set NODE_ENV=development&& nodemon --delay 1 src/server.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/server.js`
info [server.js]: Logger: Name - console, Level - info, dirname - undefined, filename -undefined
info [server.js]: Logger: Name - dailyRotateFile, Level - verbose, dirname - D:\Users\johni\Projects\fastify_graphql\Logs, filename -graphql-server-development-%DATE%.log
info [server.js]: NODE_ENV: development
info [server.js]: OS type: Windows_NT
info [server.js]: OS hostname: HP-DESKTOP
info [server.js]: IP: 192.168.0.103
info [knex.js]: Knex setup ......
info [knex.js]: Knex using client: sqlite3 connecting to db D:\Users\johni\Projects\fastify_graphql\NPVR\npvr.DB3
info [server.js]: Checking Knex
info [server.js]: Setting up NodeCache ...
info [server.js]: NodeCache statistics: { hits: 0, misses: 0, keys: 0, ksize: 0, vsize: 0 }   
info [server.js]: In-memory DB for Users created in NodeCache
info [server.js]: Setting up Fastify serving static files
info [server.js]: appDir: D:\Users\johni\Projects\fastify_graphql
info [server.js]: srcDir: D:\Users\johni\Projects\fastify_graphql\src
info [server.js]: Fastify static path channel logos: D:\Users\johni\Projects\fastify_graphql\NPVR\media\channels
info [server.js]: Fastify static path shows artwork: D:\Users\johni\Projects\fastify_graphql\NPVR\media\shows
info [server.js]: Fastify static path live streaming: D:\Users\johni\Projects\fastify_graphql\stream
info [server.js]: Fastify static path public: D:\Users\johni\Projects\fastify_graphql\public  
info [server.js]: Setting up Graphql
info [typeDefs.js]: Entering module: D:\Users\johni\Projects\fastify_graphql\src\graphql\typeDefs.js
info [resolvers.js]: Entering module: D:\Users\johni\Projects\fastify_graphql\src\graphql\resolvers.js
info [server.js]: ffmpeg path exists.
info [server.js]: QSVEnc path exists.
info [server.js]: Query: select `type`, `name` from `sqlite_master` where `type` = ?
info [utils.js]: child_process[node]: on.exit with code: 0
info [server.js]: child-process[node] resp: 0 v16.13.0

info [server.js]: knex returned 27 tables(rows)

D:\Users\johni\Projects\fastify_graphql\node_modules\fastify\lib\decorate.js:40
    throw new FST_ERR_DEC_ALREADY_PRESENT(name)
          ^
FastifyError [Error]: The decorator 'corsPreflightEnabled' has already been added!
    at decorateConstructor (D:\Users\johni\Projects\fastify_graphql\node_modules\fastify\lib\decorate.js:40:11)
    at Object.decorateRequest (D:\Users\johni\Projects\fastify_graphql\node_modules\fastify\lib\decorate.js:118:3)
    at fastifyCors (D:\Users\johni\Projects\fastify_graphql\node_modules\fastify-cors\index.js:20:11)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jsumners** [comment]
Can you show this problem with standard Fastify?

**Comment by rhscjohn-dev** [comment]
I do not understand what you mean by "standard Fastify".  Would you please elaborate.

I did come across this [issue](https://github.com/nestjs/nest/issues/8280) which has a very similar error to mine. But I did not see anything the release notes for version 3.22.0 that would involve the usage of fastify-cors.

I can comment out the following code in my server.js and the error goes away when running version 3.22.0.
```
// setup cors
f.register(require('fastify-cors'), {
  orgin: '*'
})
```1

**Comment by jsumners** [comment]
> I do not understand what you mean by "standard Fastify"

```
> npm install --save fastify fastify-cors
> # write code in a javascript file, e.g. server.js
> node server.js
```

We do not write, nor support, `apollo-server-fastify`.

**Comment by zekth** [comment]
@rhscjohn-dev this problem comes from `apollo-server-fastify`, it embdeds `fastify-cors` and include it underneath. Please raise an issue in this project instead of fastify.
