### ISSUE TITLE
Error: Cannot add route when fastify instance is already started! while starting npm run start

### ISSUE THREAD

**Issue by srikanthpoojarytechphysic** [fastify/fastify#3840]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

while starting the npm server in mac os iam getting this strange below error, we have used fastly for our routes

`Error: Cannot add route when fastify instance is already started!
    at throwIfAlreadyStarted (/Users/demouser/Documents/testapp/node_modules/fastify/fastify.js:386:40)
    at Object.route (/Users/demouser/Documents/testapp/node_modules/fastify/lib/route.js:130:5)
    at Object._route [as route] (/Users/demouser/Documents/testapp/node_modules/fastify/fastify.js:241:27)
    at addMetricsRoute (/Users/demouser/Documents/testapp/build/server.js:76:7)
    at /Users/demouser/Documents/testapp/build/server.js:16413:66`

**Comment by climba03003** [comment]
I don't know what is `fastly`, but you can not add routes after the server start.
