### ISSUE TITLE
Fastify (more specifically avvio) crashes if chartjs-node-canvas is imported.

### ISSUE THREAD

**Issue by ItzDerock** [fastify/fastify#3888]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Node.js version

16.11.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

This issue originates in the avvio module, but I am unfamiliar with that module and how fastify uses it so I'm unable to create some sort of test only involving avvio to check if it is avvio or fastify that causes the crash, was hoping to see if someone here is able to help.

Basically, when importing and using `chartjs-node-canvas`, fastify crashes with:
```
C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\node_modules\avvio\plugin.js:18
    if (cache[keys[i]].exports === func) {
                       ^
TypeError: Cannot read properties of undefined (reading 'exports')
    at getName (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\node_modules\avvio\plugin.js:18:24)
    at new Plugin (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\node_modules\avvio\plugin.js:50:15)
    at Boot._addPlugin (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\node_modules\avvio\boot.js:243:15)
    at Boot.after (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\node_modules\avvio\boot.js:270:8)
    at Object.server.<computed> [as after] (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\node_modules\avvio\boot.js:44:14)
    at Object.addHook (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\fastify\fastify.js:545:12)
    at Object.<anonymous> (C:\Users\deroc\Documents\Code\Typescript\Testing\src\index.ts:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\deroc\Documents\Code\Typescript\Testing\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
 ```

### Steps to Reproduce

1. Install fastify, chartjs-node-canvas, and canvas
2. Run the following (typescript) 
```ts
import fastify from 'fastify';
const app = fastify();

// import chartjs, make sure to create an instance
// since it may be one of the chartjs dependencies that breaks
// the app if instead of chartjs itself
import { ChartJSNodeCanvas } from "chartjs-node-canvas";
const Chart = new ChartJSNodeCanvas({ 
    width: 800, 
    height: 600,
    backgroundColour: "#2d2f34"
});

// simple hello world endpoint
app.get('/', (req, res) => void res.send('Hello World!'));

// start the server
app.listen(3000, (err, address) => console.log(err || `Listening on ${address}`));
```
3. Observe

### Expected Behavior

Fastify starts normally and accepts connections.

**Comment by climba03003** [comment]
The problem related to `chartjs-node-canvas` itself.
It is mutating the `require.cache` that shouldn't be expected.

https://github.com/SeanSobey/ChartjsNodeCanvas/blob/59174b04f1c89735e303c3ed6829a1799b10780c/src/freshRequire.ts#L3-L11
https://github.com/SeanSobey/ChartjsNodeCanvas/blob/a0ae665e4c98cc53bbd8b3f20ca33d635289ef3e/src/index.ts#L235-L240
