### ISSUE TITLE
404 OPTIONS error only on one request

### ISSUE THREAD

**Issue by semoal** [fastify/fastify#3957]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0-rc.3 and 4.0.0-rc.4

### Plugin version

Fastify-cors, 8.0.0

### Node.js version

16.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Description

Upgraded an API of my company from Fastify 3.x to Fastify 4 and everything apparently just worked fine, until I found that one request which the URL is larger than usual fails by CORS error.

I'm using the @fastify/cors@8.0.0 package.

### Screenshots

<table>
<tr>
	<td><img width="824" alt="Screenshot 2022-05-31 at 10 36 31 PM" src="https://user-images.githubusercontent.com/22656541/171280351-982eae00-9063-4b8d-9d83-7a748ab2b74f.png">
 </td>
	<td><img width="1105" alt="Screenshot 2022-05-31 at 10 36 22 PM" src="https://user-images.githubusercontent.com/22656541/171280369-4b67bd03-57ab-431e-bb90-38cc50e20881.png">
</td>
</table></td>

### Interesting things

Found that the request via Postman or cURL works fine, but not through fetch/axios. Probably the bug is related to CORS package? On 3.x worked fine and I didn't change anything else.

### Logs

```
[1654029168827] INFO (33657 on Sergios-MacBook-Pro.local): incoming request
    reqId: "req-5"
    req: {
      "method": "OPTIONS",
      "url": "/v1/portfolios/b5859fb9-6c76-4db8-b3d1-337c5be3fd8b/instruments/2a694406-b43f-439d-aa11-0c814805c930/positions?kind=fifo&currency=USD&dateTo=2022-04-05T22:00:00.000Z",
      "remotePort": 51313
    }
[1654029168827] WARN (33657 on Sergios-MacBook-Pro.local): the default handler for 404 did not catch this, this is likely a fastify bug, please report it
    reqId: "req-5"
[1654029168828] WARN (33657 on Sergios-MacBook-Pro.local): └── / (ACL)
    / (BIND)
    / (CHECKOUT)
    / (CONNECT)
    / (COPY)
    / (DELETE)
    / (GET)
    / (HEAD)
    / (LINK)
    / (LOCK)
    / (M-SEARCH)
    / (MERGE)
    / (MKACTIVITY)
    / (MKCALENDAR)
    / (MKCOL)
    / (MOVE)
    / (NOTIFY)
    / (OPTIONS)
    / (PATCH)
    / (POST)
    / (PROPFIND)
    / (PROPPATCH)
    / (PURGE)
    / (PUT)
    / (REBIND)
    / (REPORT)
    / (SEARCH)
    / (SOURCE)
    / (SUBSCRIBE)
    / (TRACE)
    / (UNBIND)
    / (UNLINK)
    / (UNLOCK)
    / (UNSUBSCRIBE)
    └── * (ACL)
        * (BIND)
        * (CHECKOUT)
        * (CONNECT)
        * (COPY)
        * (DELETE)
        * (GET)
        * (HEAD)
        * (LINK)
        * (LOCK)
        * (M-SEARCH)
        * (MERGE)
        * (MKACTIVITY)
        * (MKCALENDAR)
        * (MKCOL)
        * (MOVE)
        * (NOTIFY)
        * (OPTIONS)
        * (PATCH)
        * (POST)
        * (PROPFIND)
        * (PROPPATCH)
        * (PURGE)
        * (PUT)
        * (REBIND)
        * (REPORT)
        * (SEARCH)
        * (SOURCE)
        * (SUBSCRIBE)
        * (TRACE)
        * (UNBIND)
        * (UNLINK)
        * (UNLOCK)
        * (UNSUBSCRIBE)

    reqId: "req-5"
[1654029168828] INFO (33657 on Sergios-MacBook-Pro.local): Not Found
    reqId: "req-5"
    res: {
      "statusCode": 404
    }
    err: {
      "type": "Error",
      "message": "Not Found",
      "stack":
          Error: Not Found
              at Router.fourOhFourFallBack [as defaultRoute] (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.0.0-rc.4/node_modules/fastify/lib/fourOhFour.js:179:26)
              at Router._defaultRoute (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/find-my-way@6.2.0/node_modules/find-my-way/index.js:500:14)
              at Router.lookup (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/find-my-way@6.2.0/node_modules/find-my-way/index.js:351:36)
              at Router.defaultRoute (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.0.0-rc.4/node_modules/fastify/fastify.js:617:23)
              at Router._defaultRoute (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/find-my-way@6.2.0/node_modules/find-my-way/index.js:500:14)
              at Router.lookup (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/find-my-way@6.2.0/node_modules/find-my-way/index.js:351:36)
              at Server.emit (node:events:526:28)
              at parserOnIncoming (node:_http_server:951:12)
              at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    }
```

### Steps to Reproduce

1. Clone https://github.com/semoal/fastify-4-repro-issue
2. `pnpm install`
3. `node index.mjs`
4. From a browser 
```
fetch("http://localhost:4000/portfolios/b5859fb9-6c76-4db8-b3d1-337c5be3fd8b/instruments/2a694406-b43f-439d-aa11-0c814805c930/positions?kind=fifo&currency=USD&dateTo=2022-04-05T22:00:00.000Z", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\""
  },
  "referrer": "http://localhost:3000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors"
});
```

Will fail

**Comment by climba03003** [comment]
I cannot reproduce the issue using `chrome` and `firefox`.

Can you provide which browser and the clear step of "From a browser".

**Comment by semoal** [comment]
> I cannot reproduce the issue using `chrome` and `firefox`.
> 
> Can you provide which browser and the clear step of "From a browser".
> 
> Note: I do not have `pnpm` on my machine, Can you check if it is only reproducible on `pnpm`. I will take it a shot again if it only reproduce on `pnpm`.

Just checked with Yarn and doesn't throw that error :o I'm going to clean up the main virtual store. Will post the fix when I resolve it!

**Comment by climba03003** [comment]
From the sentence you post, I expect the `@fastify/cors` and `@fastify/jwt` is working properly.
The problem exist on the checking method for `preValidation` hooks.

**Comment by semoal** [comment]
> From the sentence you post, I expect the `@fastify/cors` and `@fastify/jwt` is working properly. The problem exist on the checking method for `preValidation` hooks.

Not exactly, just commented out the prevalidation hook, and still fails. I don't want to lose your time guys, I'll modify the reproduction repository and will ping you back. Tricky problem ^^

**Comment by climba03003** [comment]
I see where is the problem.
