### ISSUE TITLE
JSON schema validation doesn't work with `multipart/form-data`

### ISSUE THREAD

**Issue by FlameWolf** [fastify/fastify#4127]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

`fastify-multer` 2.0.3
`@fastify/swagger` 7.4.1

### Node.js version

18.2.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I have a route that accepts `multipart/form-data` input. I have added a JSON schema to the route for validation/documentation purpose. Every time I invoke the route, I get the below error.

```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "body must be object"
}
```

### Steps to Reproduce

1. Clone the repository [@FlameWolf/fastify-upload](https://github.com/FlameWolf/fastify-upload).
2. Run `npm install` and then `nodemon`.
3. Go to `http://127.0.0.1:3072/swagger`.
4. Try out the endpoint `/posts/create`.
5. Try again with line **54** in `index.ts` commented out.

### Expected Behavior

When I invoke the route, `request.body` should contain the `content` field and `request.file` should include the file selected.

**Comment by mcollina** [comment]
Have you enabled the logs? Have you got a stacktrace for us? It looks like a bug that's somewhere either in fastify-swagger or fastify-multer.

cc @fox1t

**Comment by fox1t** [comment]
This must be a compatibility issue with v4 of Fastify. I need to check it out. Thanks for repro repository @FlameWolf.

**Comment by FlameWolf** [comment]
> Have you enabled the logs? Have you got a stacktrace for us? It looks like a bug that's somewhere either in fastify-swagger or fastify-multer.
> 
> cc @fox1t

Stack trace:

```
Error: body must be object
    at defaultSchemaErrorFormatter (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\context.js:69:10)
    at wrapValidationError (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\validation.js:114:17)
    at validate (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\validation.js:94:12)
    at preValidationCallback (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\handleRequest.js:90:18)
    at handler (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\handleRequest.js:74:7)
    at C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\contentTypeParser.js:169:9
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at done (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\contentTypeParser.js:163:14)
    at Parser.setMultipart [as fn] (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify-multer\src\lib\content-parser.ts:15:3)
    at ContentTypeParser.run (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\contentTypeParser.js:154:27)
```

**Comment by FlameWolf** [comment]
> This must be a compatibility issue with v4 of Fastify. I need to check it out. Thanks for repro repository @FlameWolf.

I got the same issue when I used `@fastify/multipart` instead of `fastify-multer` too. I will try to add a code sample for that also in the repo.

**Comment by FlameWolf** [comment]
Stack trace for `@fastify/multipart`:

```
Error: body must be object
    at defaultSchemaErrorFormatter (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\context.js:69:10)
    at wrapValidationError (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\validation.js:114:17)
    at validate (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\validation.js:94:12)
    at preValidationCallback (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\handleRequest.js:90:18)
    at handler (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\handleRequest.js:74:7)
    at C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\contentTypeParser.js:169:9
    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at done (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\contentTypeParser.js:163:14)
    at Parser.setMultipart [as fn] (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\@fastify\multipart\index.js:26:3)
    at ContentTypeParser.run (C:\Users\FlameWolf\source\repos\Fastify\fastify-upload\node_modules\fastify\lib\contentTypeParser.js:154:27)
```

**Comment by FlameWolf** [comment]
I was able to fix the issue by switching to `@fastify/multipart` and updating the schema like this:

```jsx
	body: {
		type: "object",
		properties: {
			content: {
				type: "string"
			},
			media: {
				format: "binary"
			}
		}
	}
```
