### ISSUE TITLE
The decorator 'awsLambda' has been added after start!. Code: FST_ERR_DEC_AFTER_START

### ISSUE THREAD

**Issue by thegoliathgeek** [fastify/fastify#4213]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey, 
Am trying to deploy NestJs with amplify. Am using Fastify adapter.
Here's the code `main.ts`
```ts
import {APIGatewayProxyEvent, APIGatewayProxyResult, Context} from 'aws-lambda'
import {fastify, FastifyInstance, FastifyServerOptions} from 'fastify'

import awsLambdaFastify from '@fastify/aws-lambda'
import {NestFactory} from '@nestjs/core'
import {FastifyAdapter, NestFastifyApplication} from '@nestjs/platform-fastify'

import {AppModule} from './app/app.module'

interface NestApp {
  app: NestFastifyApplication
  instance: FastifyInstance
}

let cachedNestApp: NestApp

async function bootstrapServer(): Promise<NestApp> {
  const serverOptions: FastifyServerOptions = {logger: true}
  const instance: FastifyInstance = fastify(serverOptions)
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(instance)
  )
  // app.setGlobalPrefix(process.env.API_PREFIX)
  await app.init()
  return {app, instance}
}

export const handler = async (
  event: APIGatewayProxyEvent,
  context: Context
): Promise<APIGatewayProxyResult> => {
  if (!cachedNestApp) {
    cachedNestApp = await bootstrapServer()
  }
  const proxy = awsLambdaFastify(cachedNestApp.instance)
  return proxy(event, context)
}

```

Build is happening properly but am see this error logs in the AWS console

```json
{
    "errorType": "FastifyError",
    "errorMessage": "The decorator 'awsLambda' has been added after start!",
    "code": "FST_ERR_DEC_AFTER_START",
    "name": "FastifyError",
    "message": "The decorator 'awsLambda' has been added after start!",
    "statusCode": 500,
    "stack": [
        "FastifyError: The decorator 'awsLambda' has been added after start!",
        "    at assertNotStarted (/opt/nodejs/node_modules/fastify/lib/decorate.js:129:11)",
        "    at Object.decorateRequest (/opt/nodejs/node_modules/fastify/lib/decorate.js:121:3)",
        "    at module.exports (/opt/nodejs/node_modules/@fastify/aws-lambda/index.js:19:9)",
        "    at /var/task/main.js:1:3352",
        "    at Generator.next (<anonymous>)",
        "    at /opt/nodejs/node_modules/tslib/tslib.js:118:75",
        "    at new Promise (<anonymous>)",
        "    at Object.__awaiter (/opt/nodejs/node_modules/tslib/tslib.js:114:16)",
        "    at Runtime.exports.handler (/var/task/main.js:1:2926)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"
    ]
}
```

What am i doing wrong here ??

**Comment by climba03003** [comment]
I assume the problematic statement is `await app.init()`.
It start the `fastify` instance, so `@fastify/aws-lambda` cannot be decorating `fastify` anymore.

**Comment by thegoliathgeek** [comment]
@climba03003
So what changed is required ?

**Comment by climba03003** [comment]
> So what changed is required ?

I think comment out `await app.init()` or move it under `const proxy = awsLambdaFastify(cachedNestApp.instance)`.

I do not use `nestjs` and I believe most of the member here are same as me.
If the question is related to `nestjs`, it would be better to ask in `nestjs` community.

**Comment by adampolczynski** [comment]
hey, error clearly states you have registered a plugin after initiating a fastify instance, so to fix the problem register plugin before app.init()

**Comment by Uzlopak** [comment]
Closing as the is stale and there was no feedback since the response from climba
