### ISSUE TITLE
Regsiter Route / can no longer use question marks

### ISSUE THREAD

**Issue by hitmands** [fastify/fastify#4306]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.6.0

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

Using _question marks_ in router definition now throws the following error:

```
/xx/xx/xx/node_modules/find-my-way/index.js:190
      currentNode = currentNode.createStaticChild(staticNodePath)
                                ^

TypeError: currentNode.createStaticChild is not a function
    at Router._on (/xx/xx/xx/node_modules/find-my-way/index.js:190:33)
    at Router.on (/xx/xx/xx/node_modules/find-my-way/index.js:136:10)
    at Object.addNewRoute (/xx/xx/xx/node_modules/fastify/lib/route.js:271:16)
    at Object.route (/xx/xx/xx/node_modules/fastify/lib/route.js:203:19)
    at Object.prepareRoute (/xx/xx/xx/node_modules/fastify/lib/route.js:142:18)
    at Object._get [as get] (/xx/xx/xx/node_modules/fastify/fastify.js:244:34)
    at registerHomeRoute (/xx/xx/xx/core/engine/dist/development/index.js:268:12)
    at createServer (/xx/xx/xx/core/engine/dist/development/index.js:484:67)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /xx/xx/xx/core/engine/index.js:11:18
```

### Steps to Reproduce

// Error disappears by removing the `?`
```ts
  server.get('/*?', async (req, reply) => {
    return { hello: 'world' };
  });
```

### Expected Behavior

It should support optional segments.

**Comment by mcollina** [comment]
What's the last version this worked?

@ivan-tymoshenko could you take a look? This might be due to some of the refactorings you did in find-my-way.

**Comment by ivan-tymoshenko** [comment]
@hitmands What do you want to do? As I understand, you want to create a route that would match all urls. You can try `*` instead of `/*?`.
