### ISSUE TITLE
Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by flleeppyy** [fastify/fastify#4308]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.6.0

### Node.js version

16.15.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

After running Fastify, I get this error. I don't know if this has anything to do with my 
```
/media/chen/storage/development/relatrack-backend/node_modules/.pnpm/fastify@4.6.0/node_modules/fastify/lib/route.js:300
              .map(h => h.bind(this))
               ^
TypeError: Cannot read properties of undefined (reading 'bind')
    at /media/chen/storage/development/relatrack-backend/node_modules/.pnpm/fastify@4.6.0/node_modules/fastify/lib/route.js:300:27
    at Array.map (<anonymous>)
    at Boot.<anonymous> (/media/chen/storage/development/relatrack-backend/node_modules/.pnpm/fastify@4.6.0/node_modules/fastify/lib/route.js:300:16)
    at Object.onceWrapper (node:events:641:28)
    at Boot.emit (node:events:539:35)
    at Boot.emit (node:domain:475:12)
    at /media/chen/storage/development/relatrack-backend/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/boot.js:160:12
    at /media/chen/storage/development/relatrack-backend/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plugin.js:275:7
    at done (/media/chen/storage/development/relatrack-backend/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plugin.js:200:5)
    at check (/media/chen/storage/development/relatrack-backend/node_modules/.pnpm/avvio@8.2.0/node_modules/avvio/plugin.js:224:9)
```

### Steps to Reproduce

I don't exactly know, and I'm not comfortable with publishing my code repo for this.

I haven't been able to pinpoint the cause other than any route that has an `onRequest: [fastify.....]` option

I reduced it down to just my authentication decorator, and a protected ping route. if i comment out `onRequest`, the error doesn't get thrown, but if I add it, it throws the error.

Here's my auth logic stuff
```ts
import db from "../database/knex";
import fjwt from "@fastify/jwt";
import { FastifyInstance } from "fastify";
import fp from "fastify-plugin";

export default fp(async (fastify: FastifyInstance, opts) => {
  fastify.register(fjwt, {
    secret: opts.jwtSecret,
    sign: {
      iss: "relatrack-backend",
    },
  });

  (fastify.decorate as FastifyInstance["post"])("authenticate", async (req, res) => {
    if (!req.headers.authorization) {
      return res.status(401).send({
        error: "AUTH_REQUIRED",
        message: "Authorization is required to use this endpoint.",
      });
    }
    const authToken = req.headers?.authorization?.split("Bearer ")?.pop();
    if (!authToken) {
      return res.status(400).send({
        error: "BAD_AUTH_HEADER",
        message: "The Authorization header is not valid, it must match `Bearer tokenHere`",
      });
    }

    try {
      fastify.jwt.verify(authToken);
    } catch (error) {
      if (error.code)
        return res.status(401).send({
          error: error.code,
          message: error.message,
        });
      console.log(error);
    }

    const tokenPayload = fastify.jwt.decode(authToken) as userTokenPayload | userPermTokenPayload;
    if ((tokenPayload as userPermTokenPayload).permTokenId) {
      const query = await db<PermToken>("permtokens")
        .select("revoked")
        .where("tokenid", (tokenPayload as userPermTokenPayload).permTokenId)
        .first();
      if (!query || query.revoked) {
        return res.status(401).send({
          error: "BAD_AUTH_TOKEN",
          message: "Bad authorization token",
          authTokenRevoked: true,
        });
      }
    }

    const user = await db<User>("users").select("*").where("id", tokenPayload.id).first();

    if (!user) {
      return res.status(401).send({
        error: "USER_NOT_FOUND",
        message: "User not found/has been deleted.",
      });
    }

    req.user = user;
  });
});

export type userTokenPayload = {
  id: number;
  username: string;
  permissions: string;
};

export type userPermTokenPayload = userTokenPayload & {
  permTokenId: string;
};
```

And this is my typings file

```ts
import {userTokenPayload} from "../decorations/authLogic";

declare module "fastify" {
  interface FastifyInstance {
    authenticate: RouteHandlerMethod;
    bodyvalidation: RouteHandlerMethod;
  }
}

declare module "@fastify/jwt" {
  interface FastifyJWT {
    user: User;
  }
}
```

``

**Comment by Uzlopak** [comment]
Arrow Functions do not have this-Reference.

**Comment by flleeppyy** [comment]
I've replaced every single function on fastity routes or decorators to regular functions, I'm still getting errors

**Comment by flleeppyy** [comment]
So commenting out this ping route for testing, I believe this is what is causing the error.

```ts
fastify.get(
    "/api/protectedPing",
    {
      onRequest: [fastify.authenticate],
    },
    function (req, res) {
      res.send("pong");
    },
  );
  ```

**Comment by Eomm** [comment]
Did you `console.log(fastify.authenticate)`?
I think it will be `undefined`, so the debug process should start from there

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different files, create a new repository on GitHub and add a link to that.

**Comment by flleeppyy** [comment]
So I'm using Typescript, and the authentication decoration I have (which is supposed to be an onRequest hook) wasn't working currently with types, so I overrided the decorate function as a post route method, but after trying to figure out what was wrong, I realized didn't have `done` in the function params, but I couldnt add it because of the funky typing, and then after trying to fix it, the reason why i did that funky typing was because typescript did not like fastify-plugin and the function params inside the `fp` function were set to any so I had to set them myself.

Anyway that probably makes no sense, so here's my code for the authentication decorator. 

```ts
import db from "../database/knex";
import fjwt from "@fastify/jwt";
import { FastifyInstance, FastifyPluginCallback, onRequestHookHandler } from "fastify";
import fp from "fastify-plugin";

export default fp(async function (fastify, opts: Record<any,any>, next) {
  fastify.register(fjwt, {
    secret: opts.jwtSecret,
    sign: {
      iss: "relatrack-backend",
    },
  });

  fastify.decorate("authenticate", async function (req, res, done) {
    // ......
    done();
  } as onRequestHookHandler);
  return;
} as FastifyPluginCallback);

export type userTokenPayload = {
  id: number;
  username: string;
  permissions: string;
};

export type userPermTokenPayload = userTokenPayload & {
  permTokenId: string;
};
```

Problem solved I guess.

**Comment by flleeppyy** [comment]
If you're using decorators and you have routes that use those decorators in the same context,  **await** your decorators before you use those routes, otherwise it will throw that error.

I believe this is the solution.

**Comment by climba03003** [comment]
`decorator` is sync function, it doesn't need to `await`.
`plugin` is `async`, it does need to `await`.
