### ISSUE TITLE
Running tests produces: "Error: root plugin has already booted"

### ISSUE THREAD

**Issue by mikemfleming** [fastify/fastify#431]
```
Error: root plugin has already booted
      at Boot._init (node_modules/avvio/boot.js:113:11)
      at Boot._addPlugin (node_modules/avvio/boot.js:168:8)
      at Boot.use (node_modules/avvio/boot.js:148:10)
      at Function.server.(anonymous function) [as register] (node_modules/avvio/boot.js:30:14)
      at Object.exports.listen (server/index.js:19:11)
      at Context.<anonymous> (test/integration_tests/api.test.js:12:12)
```

I'm trying to write my tests in such a way that they spin up a new server, but I can't find my way around this error. It seems to be coming from `avvio`. Am I missing something in my configuration?

run tests
`mocha --recursive`

test.js
```
'use strict';

const expect = require('chai').expect;

const TEST_PORT = require('../../config/main.config').PORT + 1;
const TEST_TOKEN = 'I-WANT-2-BELIEVE';
const server = require('../../server');

describe('MY API', () => {

  before(function () {
    server.listen(TEST_PORT, TEST_TOKEN);
  });

  after(function () {
    server.close(function () {
      console.log('SERVER CLOSED')
    })
  });

  it('Should assert true to be true', () => {
    expect(true).to.be.true;
  });
});

```

server.js
```
'use strict';

const bearerAuthPlugin = require('fastify-bearer-auth');
const log = require('./log').child({ file: __filename });

const fastify = require('fastify')({ logger: log });

exports.listen = function (port, token) {
  // Set insures all keys are unique
  const keys = new Set([ token ]);

  // format schema error messages
  fastify.setErrorHandler((error, reply) => {
    error.message = JSON.parse(error.message);
    reply.send(error);
  });

  // require authorization
  fastify.register(bearerAuthPlugin, { keys }, (error) => {
    if (error) {
      log.fatal(error, 'Error registering bearer authorization strategy');
      process.exit(1);
    }
  });

  // register our API routes
  fastify.register(require('./routes/v1'), { prefix: '/v1' });

  // spin up server
  fastify.listen(port, function (error) {
    if (error) {
      log.fatal(error, 'Error starting server');
      throw error
    }
    log.info(`MY API is listening on port ${port}`);
  });
};

exports.close = function (cb) {
  log.info('Closing server');
  fastify.close(cb);
};

```

Thanks!

**Comment by mcollina** [comment]
Exporting your server is an antipattern, it leads to fragile applications that are hard to test (because of shared state).

Fastify boots once, you can boot it twice. Wrap your application in a plugin, then boot a new instance of fastify and register that plugin.

**Comment by mcollina** [comment]
Or use a factory to build your fastify instance.

**Comment by mikemfleming** [comment]
Thanks!

**Comment by araujo-luis** [comment]
> Wrap your application in a plugin, then boot a new instance of fastify and register that plugin.

What do you mean by wrapping my app in a plugin? I'm having this issue
