### ISSUE TITLE
Do not know how to serialize a BigInt while working with Prisma

### ISSUE THREAD

**Issue by iliakostichenko** [fastify/fastify#4423]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

"@nestjs/platform-fastify": "^9.2.0"

### Node.js version

18.12.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0 (22A380)

### Description

After upgrading to the latest version of fastify and prisma encountered issue with response processing.

TypeError: Do not know how to serialize a BigInt.

According to the prisma [documentation](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields) for this specific case `JSON.stringify` should be updated.

[File](https://github.com/fastify/fastify/blob/main/lib/reply.js)

Changing to
```
function serialize (context, data, statusCode, contentType) {
  const fnSerialize = getSchemaSerializer(context, statusCode, contentType)
  if (fnSerialize) {
    return fnSerialize(data)
  }

  return JSON.stringify(
    data,
    (key, value) => (typeof value === 'bigint' ? value.toString() : value)
  )
}
```
 solves the issue.

### Steps to Reproduce

Query any object ( with `prisma` ) returning plain JavaScript objects with `BigInt` field.

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at serialize (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/fastify/lib/reply.js:826:15)
    at preserializeHookEnd (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/fastify/lib/reply.js:504:17)
    at preserializeHook (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/fastify/lib/reply.js:488:5)
    at Reply.send (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/fastify/lib/reply.js:191:7)
    at FastifyAdapter.reply (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:167:29)
    at RouterResponseController.apply (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
    at /Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/@nestjs/core/router/router-execution-context.js:176:48
    at /Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/@nestjs/core/router/router-execution-context.js:47:13
    at Object.<anonymous> (/Users/iliakostichenko/Projects/tech-girl/techgirl-api/node_modules/@nestjs/core/router/router-proxy.js:9:17)

```

### Expected Behavior

Returning plain Javascript objects with `BigInt` fields without throwing error.

**Comment by jsumners** [comment]
We will not be patching `JSON.stringify`. If you need to work with `BigInt`, create your own object with a `toJSON` method that handles the conversion.

http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior

**Comment by GorlikItsMe** [comment]
I had similar problem.
In my case the problem was with schema. For problematic field you have to change type from `number` to `integer` and all starts works.

Doesn't  work:
```js
{
  summary: "foo",
  body: {
    type: "object",
    properties: {
      id: {type: "number"},
    }
  }
}
```

Work:
```js
{
  summary: "foo",
  body: {
    type: "object",
    properties: {
      id: {type: "integer"},
    }
  }
}
```

I wish that will help you 😄
