### ISSUE TITLE
ERROR: lru is not a function

### ISSUE THREAD

**Issue by cloi37** [fastify/fastify#4447]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.9.2

### Plugin version

^4.3.0

### Node.js version

18.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

node:18.4-bullseye

### Description

ERROR: lru is not a function
[App]     err: {
[App]       "type": "TypeError",
[App]       "message": "lru is not a function",
[App]       "stack":
[App]           TypeError: lru is not a function
[App]               at from (/usr/src/app/node_modules/@fastify/reply-from/index.js:28:49)
[App]               at Plugin.exec (/usr/src/app/node_modules/avvio/plugin.js:130:19)
[App]               at Boot.loadPlugin (/usr/src/app/node_modules/avvio/plugin.js:272:10)
[App]               at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[App]     }

### Steps to Reproduce

cleared out docker image and rebuild it, the server crashed without starting

**Comment by Uzlopak** [comment]
This happens when the tiny-lru package is not updated.
