### ISSUE TITLE
reply.send is not a function

### ISSUE THREAD

**Issue by BrozyGL** [fastify/fastify#4574]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm using the fastify version on v^4.12.0 and it still gives this error

my code:

```js
(async () => 
    const app = fastify();

    await app.register(require('@fastify/middie'));

    app.use(bodyParser.urlencoded({ extended: false }));
    app.use(bodyParser.json());

    app.use('/', (request, reply) => {
        reply.send("teste")
    })

    app.listen({ port: process.env.API_PORT })
})()
```
```js
Reciver:

        reply.send("teste")
              ^

TypeError: reply.send is not a function
    at C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\index.js:37:15
    at Holder.done (C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\@fastify\middie\engine.js:107:13)     
    at jsonParser (C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\body-parser\lib\types\json.js:101:7)   
    at Holder.done (C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\@fastify\middie\engine.js:112:11)     
    at C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\user\Documents\OTTO API GLOBAL EXTENDS FASTIFY\node_modules\raw-body\index.js:280:7)    
    at IncomingMessage.emit (node:events:513:28)
    ```

**Comment by climba03003** [comment]
As I said, it is a expected behavior.
The syntax is same as express / connect in `.use(req, res, next)`.
Do not mix it up with `fastify` request and reply.

**Comment by shaypep** [comment]
@climba03003 @mcollina 
I wonder, is it fine to add to the reply object express methods? 
For example, with express we use res.json() to return json object, in fastify we will do it using reply.send()
Can I just add .json() method to reply object which will use the reply.send()? will it have effect on performance?

**Comment by mcollina** [comment]
There will be no noticeable overhead.

**Comment by Eomm** [comment]
Shy opinion: maybe I would add it to the [`sensible`](https://github.com/fastify/fastify-sensible) plugin
