### ISSUE TITLE
Error after JSON schema compilation optimization

### ISSUE THREAD

**Issue by nmstone** [fastify/fastify#4739]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have implemented the JSON schema compilation optimization in the following blog post and am running into an issue for only certain schemas.

https://backend.cafe/how-to-unlock-the-fastest-fastify-server-startup

When I make certain requests, I get the following error:

```
TypeError: func2 is not a function
    at validate138 (.../generated-POST-params-v1mypath.js:1:1586)
    at validateParam (.../node_modules/fastify/lib/validation.js:100:36)
    at validate (.../node_modules/fastify/lib/validation.js:108:18)
    at preValidationCallback (.../node_modules/fastify/lib/handleRequest.js:92:18)
    at next (.../node_modules/fastify/lib/hooks.js:176:7)
    at handleResolve (.../node_modules/fastify/lib/hooks.js:193:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Where func2 is defined in the compiled validator as:

`const func2 = require("ajv/dist/runtime/ucs2length").default;`

What is strange is that I don't get this error when I recompile the routes, only when I try to use the compiled routes, and it only errors on certain routes.

The path (`ajv/dist/runtime/ucs2length`) does not seem to exist in `node_modules/ajv`, and I have tried to manually patch the ajv library to include the `ajv/dist/runtime/ucs2length` file, but this only works in a few specific distributions (basically after I [`pkg`](https://github.com/vercel/pkg) my project into an executable). However it does work on the compiled routes which is also strange.

Here is a snippet of the validator that uses `func2`. Nothing too crazy, just a minLength.

```
...}else {if(func2(data0) < 1){validate138.errors = [{instancePath:instancePath+\"/domain\",schemaPath:\"#/properties/domain/minLength\",keyword:\"minLength\",params:{limit: 1},message:\"must NOT have fewer than 1 characters\"}];return false;}}}}...
```

Any ideas? Or any further info I can provide?

**Comment by mcollina** [comment]
What requests do trigger the error? It would be good to have a. example to reproduce the problem.

**Comment by Uzlopak** [comment]
Closing due to inactivity.
