### ISSUE TITLE
Router.prettyPrint uncaught exceptions

### ISSUE THREAD

**Issue by GaryWilber** [fastify/fastify#4790]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

18.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows Server 2022

### Description

My service is seeing some uncaught exceptions with the following stack trace:

```
TypeError: Cannot read properties of undefined (reading 'prefix')
    at prettyPrintTree ({redacted}\index.js:20:195386)
    at Router.prettyPrint ({redacted}\index.js:20:185387)
    at Router.fourOhFourFallBack [as defaultRoute] ({redacted}\index.js:20:5278930)
    at Router._defaultRoute ({redacted}\index.js:20:184547)
    at Router.callHandler ({redacted}\index.js:20:181739)
    at Router.lookup ({redacted}\index.js:20:181359)
    at Router.defaultRoute ({redacted}\index.js:20:5213655)
    at Router._defaultRoute ({redacted}\index.js:20:184547)
    at Router.callHandler ({redacted}\index.js:20:181739)
    at Router.lookup ({redacted}\index.js:20:181359)
```

I do have a simple not found handler configured so I'm curious why that `fourOhFourFallBack` method is called -
```typescript
		instance.setNotFoundHandler((request, response) => {
			response.code(404).send();
		});
```

### Steps to Reproduce

Unfortunately, I am unable to reproduce it myself. I'm not sure what request is causing it.

**Comment by mcollina** [comment]
Thanks for reporting. We would need some more info to fix this, ideally a way to reproduce the problem.

**Comment by Uzlopak** [comment]
Closing due to inactivity.
