### ISSUE TITLE
Returning headers gives error "Header name must be a valid HTTP token" for OPTIONS

### ISSUE THREAD

**Issue by g-wozniak** [fastify/fastify#4791]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Node.js version

18.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Ventura 13

### Description

Route definition:

```
   fastify.route({
      method: 'OPTIONS',
      url: '/*',
      handler: async (request, reply) => {
         reply.code(204)
            .header('Content-Length', '0')
            .header('Access-Control-Allow-Origin', '*')
            .header('Access-Control-Allow-Methods', 'GET,HEAD,PUT,PATCH,POST,DELETE')
            .send()
      }
   })
```

returns the following error upon response attempt:

```json
{
  "level": 50,
  "time": 1686065201358,
  "pid": 90996,
  "hostname": "xxx",
  "reqId": "req-1",
  "req": {
    "method": "OPTIONS",
    "url": "/user",
    "hostname": "localhost:3000",
    "remoteAddress": "::1",
    "remotePort": 53490
  },
  "res": {
    "statusCode": 500
  },
  "err": {
    "type": "TypeError",
    "message": "Header name must be a valid HTTP token [\"access-control-allow-origin:\"]",
    "stack": "TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [\"access-control-allow-origin:\"]\n    at processHeader (node:_http_outgoing:545:5)\n    at ServerResponse._storeHeader (node:_http_outgoing:449:11)\n    at ServerResponse.writeHead (node:_http_server:417:8)\n    at onSendEnd (/reply.js:571:9)\n    at wrapOnSendEnd (/reply.js:537:5)\n    at next (/hooks.js:224:7)\n    at Object.<anonymous> (/api/server.ts:73:13)\n    at next (/hooks.js:230:30)\n    at onSendHookRunner (/hooks.js:252:3)\n    at onSendHook (/reply.js:521:5)",
    "code": "ERR_INVALID_HTTP_TOKEN"
  },
  "msg": "Header name must be a valid HTTP token [\"access-control-allow-origin:\"]"
}
```

### Steps to Reproduce

Create Fastify instance without CORS and add the following route definition.

### Expected Behavior

response should be 204 and successful.

**Comment by ydv-ankit** [comment]
can i help with this issue?

**Comment by shayff** [comment]
@ydv-ankit Are you working on it? if not I can help

**Comment by Uzlopak** [comment]
I  could not reproduce this.
