### ISSUE TITLE
Pino is converting an "error" object by removing fields from it.

### ISSUE THREAD

**Issue by GeorgiiGalechyan** [fastify/fastify#4937]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When logging inside try...catch, an 'error' object with fields 'type', 'stack', 'message' is created.  
However, the 'type' field becomes 'undefined' when you try to access it. And in some cases, the 'stack' and 'message' fields are also removed from the 'error' object.

```javascript
export const regNewUser = async (app) => {
  await app.post('/reg', regNewUserOpts, async function (request, reply) {
    try {
      const { login, password, email } = request.body // get a data 
      await createNewUser(login, password, email)

      async function createNewUser(login, password, email) {
        try {
          await app.pg.dev.transact(async (client) => {
            await client.query(
              `INSERT INTO users (login, password, email) VALUES ('${login}', '${password}', '${email}') RETURNING *;`
            )
            await app.log.info({ msg: `User'${login}' added in table 'users'` })
          })
        } catch (err) {

            // We're interested in this part!

            app.log.error(err) // object 'err' contains fields 'type', 'message' and 'stack'
            app.log.error({ err: err }) // object 'err' contains fields 'type', 'message' and 'stack'
            app.log.error({ error: err }) // prints the 'err' object without the fields 'type ', 'message' and 'stack'
            app.log.error(`${err.type}`) // undefined

            app.log.error({
              msg: `Error adding user '${login}' to table 'users'`,
              'Error code': err.code,
              'Error type': err.type,
              'Message': err.message,
              'Detail': err.detail,
              'DB table': err.table,
              'DB constraint': err.constraint,
              'Stack': err.stack,
            })

          })
        }
      }

    } catch (err) {
      await app.log.error(err)
    }
  })
}
```

**Result of error logging:**

**1) Object 'err' contains fields 'type', 'message' and 'stack':**
```javascript
// app.log.error(err)

    err: {
      "type": "DatabaseError", // the 'type' field exists
      "message": "duplicate key value violates unique constraint \"users_login_key\"",
      "stack":
          error: duplicate key value violates unique constraint "users_login_key"
              at C:\Users\galec\Dev\Lottery\backend-lottery\node_modules\pg\lib\client.js:526:17
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///C:/Users/galec/Dev/Lottery/backend-lottery/src/routes/register.js:46:13     
      "length": 202,
      "name": "error",
      "severity": "ERROR",
      "code": "23505",
      "detail": "Key (login)=(alaverdyan) already exists.",
      "schema": "public",
      "table": "users",
      "constraint": "users_login_key",
      "file": "nbtinsert.c",
      "line": "649",
      "routine": "_bt_check_unique"
    }
```

**2) Object 'err' contains fields 'type', 'message' and 'stack':**
```javascript
// app.log.error({ err: err })

    err: {
      "type": "DatabaseError", // the 'type' field exists
      "message": "duplicate key value violates unique constraint \"users_login_key\"",
      "stack":
          error: duplicate key value violates unique constraint "users_login_key"
              at C:\Users\galec\Dev\Lottery\backend-lottery\node_modules\pg\lib\client.js:526:17
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///C:/Users/galec/Dev/Lottery/backend-lottery/src/routes/register.js:46:13     
      "length": 202,
      "name": "error",
      "severity": "ERROR",
      "code": "23505",
      "detail": "Key (login)=(alaverdyan) already exists.",
      "schema": "public",
      "table": "users",
      "constraint": "users_login_key",
      "file": "nbtinsert.c",
      "line": "649",
      "routine": "_bt_check_unique"
    }

```

**3) The 'type', 'stack' and 'message' fields have disappeared**
```javascript
// app.log.error({ error: err })

error: {
      "length": 202,
      "name": "error",
      "severity": "ERROR",
      "code": "23505",
      "detail": "Key (login)=(alaverdyan) already exists.",
      "schema": "public",
      "table": "users",
      "constraint": "users_login_key",
      "file": "nbtinsert.c",
      "line": "649",
      "routine": "_bt_check_unique"
    }
```

**4) err.type is now undefined:**
```javascript
// app.log.error(`${err.type}`)
undefined
```

**The 'stack' and 'message' fields remain, the 'type' field has disappeared:**
```javascript
// app.log.error({
//   msg: `Error adding user '${login}' to table 'users'`,
//   'Error code': err.code,
//   'Error type': err.type,
//   'Message': err.message,
//   'Detail': err.detail,
//   'DB table': err.table,
//   'DB constraint': err.constraint,
//   'Stack': err.stack,
//  })

Error adding user 'alaverdyan' to table 'users'

    Error code: "23505"
    Message: "duplicate key value violates unique constraint \"users_login_key\""
    Detail: "Key (login)=(alaverdyan) already exists."
    DB table: "users"
    DB constraint: "users_login_key"
    Stack: "error: duplicate key value violates unique constraint \"users_login_key\"\n    at C:\Users\galec\Dev\Lottery\backend-lottery\node_modules\pg\lib\client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///C:/Users/galec/Dev/Lottery/backend-lottery/src/routes/register.js:46:13"
```

**Comment by jsumners** [comment]
Please do not open multiple issues for the same thing. You have already opened one in https://github.com/pinojs/pino/issues/1758?notification_referrer_id=NT_kwDOAATmsbE3MjE4MjQxNjI1OjMyMTIwMQ#issuecomment-1656736718
