### ISSUE TITLE
PROPFIND and PROPPATCH requests log 'likely a fastify bug' and crash

### ISSUE THREAD

**Issue by heskew** [fastify/fastify#505]
Saw this in logs on a test deployment that's open to external traffic. Nice testing ground for random requests.

Simple repro:
```
require('fastify')({ logger: console }).inject({ method: 'PROPFIND', url: '/' });
require('fastify')({ logger: console }).inject({ method: 'PROPPATCH', url: '/' });
```

Expected: don't crash

Actual: logs the following and crashes
```
{"level":30,"time":1512149021147,"msg":"incoming request","pid":26800,"hostname":"badger","reqId":1,"req":{"id":1,"method":"PROPFIND","url":"/","remoteAddress":"127.0.0.1"},"v":1}
{"level":40,"time":1512149021148,"msg":"the default handler for 404 did not catch this, this is likely a fastify bug, please report it","pid":26800,"hostname":"badger","reqId":1,"v":1}
{"level":40,"time":1512149021148,"msg":"└── / (DELETE|GET|HEAD|PATCH|POST|PUT|OPTIONS|TRACE|CONNECT)\n    └── * (DELETE|GET|HEAD|PATCH|POST|PUT|OPTIONS|TRACE|CONNECT)\n","pid":26800,"hostname":"badger","reqId":1,"v":1}
{"level":30,"time":1512149021148,"msg":"Not found","pid":26800,"hostname":"badger","reqId":1,"res":{"statusCode":404},"err":{"type":"Error","message":"Not found","stack":"Error: Not found\n    at Router.fourOhFourFallBack [as defaultRoute] (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:573:26)\n    at Router._defaultRoute (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:365:10)\n    at Router.lookup (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:228:28)\n    at Router.defaultRoute (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:558:16)\n    at Router._defaultRoute (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:365:10)\n    at Router.lookup (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:228:28)\n    at Object.fastify (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:165:12)\n    at req.prepare (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/index.js:77:38)\n    at Request.prepare (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/lib/request.js:72:12)\n    at Promise (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/index.js:77:11)"},"v":1}
{"level":30,"time":1512149021149,"msg":"incoming request","pid":26800,"hostname":"badger","reqId":1,"req":{"id":1,"method":"PROPPATCH","url":"/","remoteAddress":"127.0.0.1"},"v":1}
{"level":40,"time":1512149021149,"msg":"the default handler for 404 did not catch this, this is likely a fastify bug, please report it","pid":26800,"hostname":"badger","reqId":1,"v":1}
{"level":40,"time":1512149021149,"msg":"└── / (DELETE|GET|HEAD|PATCH|POST|PUT|OPTIONS|TRACE|CONNECT)\n    └── * (DELETE|GET|HEAD|PATCH|POST|PUT|OPTIONS|TRACE|CONNECT)\n","pid":26800,"hostname":"badger","reqId":1,"v":1}
{"level":30,"time":1512149021149,"msg":"Not found","pid":26800,"hostname":"badger","reqId":1,"res":{"statusCode":404},"err":{"type":"Error","message":"Not found","stack":"Error: Not found\n    at Router.fourOhFourFallBack [as defaultRoute] (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:573:26)\n    at Router._defaultRoute (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:365:10)\n    at Router.lookup (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:228:28)\n    at Router.defaultRoute (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:558:16)\n    at Router._defaultRoute (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:365:10)\n    at Router.lookup (/home/ramon/src/AgaDevs/dundee/node_modules/find-my-way/index.js:228:28)\n    at Object.fastify (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:165:12)\n    at req.prepare (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/index.js:77:38)\n    at Request.prepare (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/lib/request.js:72:12)\n    at Promise (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/index.js:77:11)"},"v":1}
/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:174
    if (ctx.onResponse !== null) {
            ^

TypeError: Cannot read property 'onResponse' of null
    at Response.onResFinished (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/fastify.js:174:13)
    at emitNone (events.js:111:20)
    at Response.emit (events.js:208:7)
    at Response.end (/home/ramon/src/AgaDevs/dundee/node_modules/light-my-request/lib/response.js:58:8)
    at onSendEnd (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/lib/reply.js:185:13)
    at Reply.wrapOnSendEnd (/home/ramon/src/AgaDevs/dundee/node_modules/fastify/lib/reply.js:161:3)
    at Holder._next (/home/ramon/src/AgaDevs/dundee/node_modules/fast-iterator/index.js:34:19)
    at Immediate._fast [as _onImmediate] (/home/ramon/src/AgaDevs/dundee/node_modules/fast-iterator/index.js:17:14)
    at runCallback (timers.js:795:20)
    at tryOnImmediate (timers.js:751:5)
```

**Comment by allevo** [comment]
Hi and thank you for this report! 

Nice catch!

For the time being, PROFIND and PROPATCH http methods are not supported. That produces an "internal" error. During the handling of that error, fastify crashes.

Anyway, the only supported http methods are listed in the above output

So, this is a fastify bug definitely! But, I suggest you to don't inject custom http methods!

**Comment by heskew** [comment]
No problem! This repro is overly simplified, I originally noticed it in a deployed service where I don’t always have control over who could poke at it. :)

**Comment by delvedor** [comment]
Hi @heskew thank you for the bug report!
Can you check if the issue is solved with [fastify#fix-505](https://github.com/fastify/fastify/tree/fix-505) branch?

**Comment by heskew** [comment]
Looks good @delvedor. Returns a 404 and doesn't crash. :1st_place_medal:
