### ISSUE TITLE
bug: FST_ERR_HOOK_INVALID_ASYNC_HANDLER not thrown

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify#5068]
The following code should break:

```
const app = require("fastify")({ logger: !true });

// 🤬 DO NOT MIX ASYNC AND CALLBACK STYLE:
async function wrongHook(request, reply, done) {
  console.log("preHandler");
  done();
}

// FastifyError [Error]: Async function has too many arguments. Async hooks should not use the 'done' argument.
// 🚀 app.addHook("preHandler", wrongHook);

app.get(
  "/",
  {
    preHandler: [
      wrongHook, // does not throw
    ],
  },
  async (request, reply) => {
    return { hello: "world" };
  }
);

app.listen({ port: 3000 });
```

If I uncomment the 🚀 line, it will throw an error as expected.
We should validate the route's hook array

**Comment by metcoder95** [comment]
It seems we are missing that check right here: https://github.com/fastify/fastify/blob/7d97dcdf2643bcfbdcf4850867139db8189b82e2/lib/route.js#L273

**Comment by giuliowaitforitdavide** [comment]
I'm working on this

**Comment by itsazzad** [comment]
```
./node_modules/.pnpm/fastify@4.24.3/node_modules/fastify/lib/route.js:289
                  throw new FST_ERR_HOOK_INVALID_ASYNC_HANDLER()
                        ^
FastifyError [Error]: Async function has too many arguments. Async hooks should not use the 'done' argument.
    at Object.addNewRoute (./node_modules/.pnpm/fastify@4.24.3/node_modules/fastify/lib/route.js:289:25)
    at Object.route (./node_modules/.pnpm/fastify@4.24.3/node_modules/fastify/lib/route.js:241:19)
    at Object.prepareRoute (./node_modules/.pnpm/fastify@4.24.3/node_modules/fastify/lib/route.js:163:18)
    at Object._post [as post] (./node_modules/.pnpm/fastify@4.24.3/node_modules/fastify/fastify.js:265:34)
    at Object.post (./src/http/router.ts:29:15)
    at authRouterHandler (./src/routes/auth.ts:347:10)
    at routerHandlers (./src/routes/index.ts:27:7)
    at start (./src/index.ts:12:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'FST_ERR_HOOK_INVALID_ASYNC_HANDLER',
  statusCode: 500
}
```

**Comment by Eomm** [comment]
@itsazzad, your message is cryptic.

Anyway: the application has an anonymous hook function that is async AND has the `done` argument. Fix it.

**Comment by itsazzad** [comment]
> @itsazzad, your message is cryptic.
> 
> Anyway: the application has an anonymous hook function that is async AND has the `done` argument. Fix it.

@Eomm
I tried to debug and is getting error in https://github.com/fastify/fastify/blob/main/lib/route.js#L289
Here is the output of:
```
hook:  preHandler, 
func:  [AsyncFunction: jtwMiddleware], 
func.constructor.name: AsyncFunction, 
func.length: 3
```

**Comment by Eomm** [comment]
I'm pretty confident that `jtwMiddleware` has this signature:

```
async function jtwMiddleware(app, opts, done){}
```

This signature is incorrect, change it to:

```
async function jtwMiddleware(app, opts){}
```

**Comment by itsazzad** [comment]
> I'm pretty confident that `jtwMiddleware` has this signature:
> 
> ```
> async function jtwMiddleware(app, opts, done){}
> ```
> 
> This signature is incorrect, change it to:
> 
> ```
> async function jtwMiddleware(app, opts){}
> ```

@Eomm 
```ts
import type { FastifyReply, HookHandlerDoneFunction } from "fastify";
import createError from "http-errors";
import { verifyJwtAccessToken } from "../helpers";
import type { FastifyRequestGeneric } from "../http/types";

export const jtwMiddleware = async (req: FastifyRequestGeneric, reply: FastifyReply, next: HookHandlerDoneFunction) => {
  const bearerToken = req.headers.authorization;

  if (!bearerToken) {
    next(new createError.Unauthorized());
  }
  const accessToken = bearerToken?.replace("Bearer ", "");
  const isVerify = await verifyJwtAccessToken(accessToken as string);
  if (!isVerify) {
    next(new createError.Unauthorized());
  }

  if (isVerify?.user.role === "USER" && req.url.includes("admin")) {
    next(new createError.Forbidden());
  }

  req.user = isVerify;
  // next();
};
```

**Comment by Eomm** [comment]
Are you reading my messages?


```diff
-async (req: FastifyRequestGeneric, reply: FastifyReply, next: HookHandlerDoneFunction) => {
+async (req: FastifyRequestGeneric, reply: FastifyReply) => {
```

![image](https://github.com/fastify/fastify/assets/11404065/0d24472f-fc6e-4ac4-9931-70ef1f861027)

**Comment by itsazzad** [comment]
@Eomm 
-async (req: FastifyRequestGeneric, reply: FastifyReply, next: HookHandlerDoneFunction) => {
+async (req: FastifyRequestGeneric, next: HookHandlerDoneFunction) => {

**Comment by Uzlopak** [comment]
No! 

```js
import type { FastifyReply, HookHandlerDoneFunction } from "fastify";
import createError from "http-errors";
import { verifyJwtAccessToken } from "../helpers";
import type { FastifyRequestGeneric } from "../http/types";

export const jtwMiddleware = async (req: FastifyRequestGeneric, reply: FastifyReply) => {
  const bearerToken = req.headers.authorization;

  if (!bearerToken) {
    throw new createError.Unauthorized();
  }
  const accessToken = bearerToken?.replace("Bearer ", "");
  const isVerify = await verifyJwtAccessToken(accessToken as string);
  if (!isVerify) {
    throw new createError.Unauthorized();
  }

  if (isVerify?.user.role === "USER" && req.url.includes("admin")) {
    throw new createError.Forbidden();
  }

  req.user = isVerify;
};
```

**Comment by Uzlopak** [comment]
You should really investigate into async await and how it works. 

Also your function is named wrong. jtwMiddleware, but it should be jwt. And in fastify we don't use middlewares but plugins. 

Also consider using @fastify/error instead of http-errors.
