### ISSUE TITLE
Error with version mismatch on fastify flash with v5

### ISSUE THREAD

**Issue by prince829** [fastify/fastify#5724]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

6.0.0

### Node.js version

20

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22

### Description

FastifyError [Error]: fastify-plugin: @fastify/flash - expected '4.x' fastify version, '5.0.0' is installed
    at Object.checkVersion (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginUtils.js:125:11)
    at Object.registerPlugin (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Boot._loadPlugin (/home/webskitters/projects/jobreef/node_modules/avvio/boot.js:425:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
} route build error
FastifyError [Error]: fastify-plugin: @fastify/flash - expected '4.x' fastify version, '5.0.0' is installed
    at Object.checkVersion (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginUtils.js:125:11)
    at Object.registerPlugin (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Boot._loadPlugin (/home/webskitters/projects/jobreef/node_modules/avvio/boot.js:425:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
FastifyError [Error]: fastify-plugin: @fastify/flash - expected '4.x' fastify version, '5.0.0' is installed
    at Object.checkVersion (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginUtils.js:125:11)
    at Object.registerPlugin (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (/home/webskitters/projects/jobreef/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Boot._loadPlugin (/home/webskitters/projects/jobreef/node_modules/avvio/boot.js:425:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}

Node.js v20.10.0

### Expected Behavior

When we go ahead with Fastify 5 then it gives the error with fastify/flash with version mismatch rather I had installed the latest version of Fastify Flash.

**Comment by climba03003** [comment]
Please provide the dependent tree you have. Or a reproducible example.

**Comment by prince829** [comment]
.
├── docker-compose.yaml
├── jobreef.ts
├── package.json
├── package-lock.json
├── README.md
├── secret-key
├── test.html
└── tsconfig.json
This one is my working tree where jobreef.ts represents the server file.
Node Version: 20 
Npm version:10.2.3
I am trying to use Fastify with the version of: 5.0.0
And trying to sink @fastify/flash: 6.0.0
along with "@fastify/secure-session": 8.1.0,
Feel free if you need more information

**Comment by prince829** [comment]
I resolved the issue by update the version of @fastify/passport as @fastify/flash had dependency with that

thanks for your response
