### ISSUE TITLE
error: logger options only accepts a configuration object

### ISSUE THREAD

**Issue by Jamchello** [fastify/fastify#5737]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Node.js version

20.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.6.1

### Description

Looks like a regression, when passing a pino logger instance into the Fastify constructor I am getting the following error:

```bash
FastifyError [Error]: logger options only accepts a configuration object.
    at FastifyError (/Users/fishy/Documents/solana/node_modules/@fastify/error/index.js:18:14)
    at createLogger (/Users/fishy/Documents/solana/node_modules/fastify/lib/logger.js:98:11)
    at fastify (/Users/fishy/Documents/solana/node_modules/fastify/fastify.js:137:33)
    at createFastifyServer (file:///Users/fishy/Documents/solana/build/api/createFastifyServer.js:11:21)
```

Typescript compiler is totally happy with my initialisation of the fastify app:

```bash
  const fastify = Fastify({
    logger,
  });
```

**Comment by mcollina** [comment]
https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/
