### ISSUE TITLE
Passing a pino instance to fastify's logger option causes error using 5.0.0

### ISSUE THREAD

**Issue by onosendi** [fastify/fastify#5747]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

5.0.1

### Node.js version

20.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.6.1 (23G93)

### Description

This error is new to version 5.*. The same code works on Fastify version 4.28.1.

```javascript
const Fastify = require('fastify');
const pino = require('pino');

const logger = pino();

const fastify = Fastify({ logger })
```
Results in:

```
/Users/work/Downloads/foo/node_modules/fastify/lib/logger.js:98
    throw FST_ERR_LOG_INVALID_LOGGER_CONFIG()
    ^
FastifyError [Error]: logger options only accepts a configuration object.
    at FastifyError (/Users/work/Downloads/foo/node_modules/@fastify/error/index.js:18:14)
    at createLogger (/Users/work/Downloads/foo/node_modules/fastify/lib/logger.js:98:11)
    at fastify (/Users/work/Downloads/foo/node_modules/fastify/fastify.js:137:33)
    at Object.<anonymous> (/Users/work/Downloads/foo/index.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'FST_ERR_LOG_INVALID_LOGGER_CONFIG',
  statusCode: 500
}
```

**Comment by jsumners** [comment]
https://github.com/fastify/fastify/blob/ef1c7184099a6ab869ebf17b651b2d6517a6f75d/docs/Guides/Migration-Guide-V5.md

**Comment by onosendi** [comment]
> https://github.com/fastify/fastify/blob/ef1c7184099a6ab869ebf17b651b2d6517a6f75d/docs/Guides/Migration-Guide-V5.md

Meh, sorry. Thank you.
