### ISSUE TITLE
`Error: write after end` using websockets

### ISSUE THREAD

**Issue by shkumbin** [fastify/fastify#587]
Hi there,

I wanted to use [websockets](https://github.com/websockets/ws) in fastify but I get an error in the second request. I'm not sure if this is fastify-related or not so I just wanted to make sure.

### Reproducable in
Node version(s): 8.9.3

### Steps to reproduce

1. Setup fastify
```javascript
const fastify = require('fastify')()

const WebSocketServer = require('ws').Server

const wss = new WebSocketServer({
  server: fastify.server
})

fastify.get('/', (req, reply) => {
  const html = `
    <script type='text/javascript'>
      var host = location.origin.replace(/^(http|https):/, 'ws:') + location.pathname;
      var ws = new WebSocket(host);
    </script>
  `
  reply.type('text/html').send(html)
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log('listening on %d', fastify.server.address().port)
})

```

2. Open `http://localhost:3000`

3. Server should be down after second refresh in browser.

Here's the stack trace
```
Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:704:40)
    at Socket.Writable.end (_stream_writable.js:553:10)
    at Socket.end (net.js:496:31)
    at Server.handleClientError (/Users/shkumbinmaksuti/code/javascript/fastify-ws-test/node_modules/fastify/fastify.js:581:12)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at Socket.socketOnError (_http_server.js:458:20)
    at emitOne (events.js:121:20)
```

**Comment by mcollina** [comment]
Have you tried reproducing this without fastify? I think you are not listening to the events of WebSocketServer. The websocket is received there.

**Comment by shkumbin** [comment]
The issue was caused by the lack of error listener:
```
ws.on('error', () => console.log('error'));
```

Closing the issue.
