### ISSUE TITLE
Support 'onClose' without the instance object

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify#629]
if `onClose(func)` is called with a function with 1 parameter, pass the callback and not the instance as the first one. Or the user might find some very hard to debug bugs like:

```
aa Error
    at fastify (C:\Users\Matteo\Repositories\fastify-http-forward\node_modules\fastify\fastify.js:158:23)
    at fastify.onClose (C:\Users\Matteo\Repositories\fastify-http-forward\index.js:38:5)
    at Function._encapsulateTwoParam (C:\Users\Matteo\Repositories\fastify-http-forward\node_modules\avvio\boot.js:328:7)
    at Boot.closeWithCbOrNextTick (C:\Users\Matteo\Repositories\fastify-http-forward\node_modules\avvio\boot.js:319:7)
    at release (C:\Users\Matteo\Repositories\fastify-http-forward\node_modules\fastq\queue.js:127:16)
    at Object.resume (C:\Users\Matteo\Repositories\fastify-http-forward\node_modules\fastq\queue.js:61:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by allevo** [comment]
May this be an `avvio` issue?

See https://github.com/mcollina/avvio/blob/master/boot.js#L53

**Comment by mcollina** [comment]
Yes definitely. Would you like to send a PR there?

**Comment by jimmiehansson** [comment]
Could perhaps send both to destruct as needed?

**Comment by mcollina** [comment]
@jimmiehansson what do you mean?

**Comment by jimmiehansson** [comment]
I missed the **if** in your description, can ignore my comment. I was suggesting to pass the cb and fn instance in a destructable object instead for versatility on the user facing end to defer the logic to the next iteration but that would be a rather bad proposal.

```javascript
onClose({...o}
```

**Comment by jsumners** [comment]
I really don't care for this stale bot business. This issue is important and shouldn't be closed just because someone hasn't had time to get around to it. Plus, *when* will it be closed if no further activity occurs? Right now it just says "it will be closed" without any indication of the threshold.

**Comment by delvedor** [comment]
@jsumners 7 more days after it is marked as *stale*.
You can flag this issue with one of the tags present [here](https://github.com/fastify/fastify/blob/master/.github/stale.yml) and it won't be marked as stale anymore.

**Comment by mcollina** [comment]
The implementation of this is semver-major, and we should include it in v2.0.0

**Comment by mcollina** [comment]
https://github.com/mcollina/avvio/pull/76 should solve this.

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fastify/pull/1201.
