### ISSUE TITLE
AssertionError cannot be caught

### ISSUE THREAD

**Issue by charlesread** [fastify/fastify#777]
Good day, I am trying to do some integration testing and have found what I think is a bug somewhere along the lines.  I can't seem to catch an `AssertionError` in the code below, it always throws the `AssertionError` also listed below.

```js
try {
  fastify.register(
    require('fastify-plugin')(
      function (f, o, next) {
        next()
      },
      {
        decorators: {
          request: ['session']
        }
      }
    )
  )
  fastify.listen(0, function (err) {
    if (err) {
      console.error('error in listen callback: %s', err.message)
    }
  })
} catch (err) {
  console.error(err.message)
}
```

```bash
/Users/charles/Development/node/fastify-auth0/node_modules/fastify/lib/pluginUtils.js:46
    assert(
    ^
AssertionError [ERR_ASSERTION]: The decorator 'session' is not present in Request
    at decorators.forEach.decorator (/Users/charles/Development/node/fastify-auth0/node_modules/fastify/lib/pluginUtils.js:46:5)
    at Array.forEach (<anonymous>)
    at Function._checkDecorators (/Users/charles/Development/node/fastify-auth0/node_modules/fastify/lib/pluginUtils.js:45:14)
    at Object.checkDecorators (/Users/charles/Development/node/fastify-auth0/node_modules/fastify/lib/pluginUtils.js:39:44)
    at Object.registerPlugin (/Users/charles/Development/node/fastify-auth0/node_modules/fastify/lib/pluginUtils.js:64:19)
    at Boot.override (/Users/charles/Development/node/fastify-auth0/node_modules/fastify/fastify.js:327:59)
    at Plugin.exec (/Users/charles/Development/node/fastify-auth0/node_modules/avvio/plugin.js:36:29)
    at Boot.loadPlugin (/Users/charles/Development/node/fastify-auth0/node_modules/avvio/plugin.js:120:10)
    at Task.release (/Users/charles/Development/node/fastify-auth0/node_modules/fastq/queue.js:127:16)
    at worked (/Users/charles/Development/node/fastify-auth0/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/Users/charles/Development/node/fastify-auth0/node_modules/avvio/plugin.js:123:7)
    at done (/Users/charles/Development/node/fastify-auth0/node_modules/avvio/plugin.js:81:5)
    at check (/Users/charles/Development/node/fastify-auth0/node_modules/avvio/plugin.js:92:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    at Function.Module.runMain (module.js:678:11)

```

* *node version*: 8
* *fastify version*: >=1.0.0-rc.1
* *os*: Mac

**Comment by jsumners** [comment]
See #778

**Comment by mcollina** [comment]
Fixes in avvio 5.4.0. Just updated your dependencies and it should pick it up automatically.

**Comment by charlesread** [comment]
Thanks!

**Comment by erfanium** [comment]
@charlesread @Eomm 
I still have a problem like this in fastify@^3.7.0
```js
const fastify = require('fastify')()

try {
   fastify.get('a', () => {})
} catch(e) {
   console.error('Err', e)
}

fastify.listen(0)
```
output: 
```sh
UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The first character of a path should be `/` or `*`
```
Is it related to this? Another problem is that every time I see this error, I should check every route urls manually to find out what's wrong, because stack trace doesn't give me enough information to find the source of the error

**Comment by mcollina** [comment]
Open a new issue in help, this behavior is long fixed.
